// @generated by @full-stack-ds/iconography build/build.mjs — do not edit.
// Committed build output (drift-gated); the authoring source of truth is
// icons/<Name>/<Name>.icon.json. Rebuild with `pnpm run build` in this package.

export const alarm = {
  "name": "alarm",
  "ref": "fsds.icon.alarm",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M8 3A5.5 5.5 0 1 1 8 14A5.5 5.5 0 1 1 8 3",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M8 6.25V8.9L9.5 10.4",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M4.25 2.5L2.25 4.5M11.75 2.5L13.75 4.5M4.25 12.3L2.75 14M11.75 12.3L13.25 14",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M12 5A8 8 0 1 1 12 21A8 8 0 1 1 12 5",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M12 9V13L14 15",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M5 3L2 6M19 3L22 6M6.38 18.7L4 21M17.64 18.67L20 21",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    }
  }
};

export const arrowDown = {
  "name": "arrow-down",
  "ref": "fsds.icon.arrow-down",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M8 3V13",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round"
        },
        {
          "d": "M4 9L8 13L12 9",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M12 4V20",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round"
        },
        {
          "d": "M6 14L12 20L18 14",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    }
  }
};

export const arrowLeft = {
  "name": "arrow-left",
  "ref": "fsds.icon.arrow-left",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M13 8H3",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M7 4L3 8L7 12",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M20 12H4",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M10 6L4 12L10 18",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    }
  }
};

export const arrowRight = {
  "name": "arrow-right",
  "ref": "fsds.icon.arrow-right",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M3 8H13",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M9 4L13 8L9 12",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M4 12H20",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M14 6L20 12L14 18",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    }
  }
};

export const arrowUp = {
  "name": "arrow-up",
  "ref": "fsds.icon.arrow-up",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M8 13V3",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round"
        },
        {
          "d": "M4 7L8 3L12 7",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M12 20V4",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round"
        },
        {
          "d": "M6 10L12 4L18 10",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    }
  }
};

export const arrowUpDown = {
  "name": "arrow-up-down",
  "ref": "fsds.icon.arrow-up-down",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M14 10L11 13L8 10M11 13V3M2 6L5 3L8 6M5 3V13",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M21 16L17 20L13 16M17 20V4M3 8L7 4L11 8M7 4V20",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    }
  }
};

export const atSign = {
  "name": "at-sign",
  "ref": "fsds.icon.at-sign",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M8 5.33A2.67 2.67 0 1 1 8 10.67A2.67 2.67 0 1 1 8 5.33",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M10.67 5.33V8.67A2 2 0 0 0 14.67 8.67V8A6.67 6.67 0 1 0 12 13.33",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M12 8A4 4 0 1 1 12 16A4 4 0 1 1 12 8",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M16 8V13A3 3 0 0 0 22 13V12A10 10 0 1 0 18 20",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    }
  }
};

export const baseline = {
  "name": "baseline",
  "ref": "fsds.icon.baseline",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M2.5 13.5H13.5M4 11L8 3L12 11M5.33 8H10.67",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M4 20H20M6 16L12 4L18 16M8 12H16",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    }
  }
};

export const calculator = {
  "name": "calculator",
  "ref": "fsds.icon.calculator",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M4.5 1.5H11.5A1.5 1.5 0 0 1 13 3V13A1.5 1.5 0 0 1 11.5 14.5H4.5A1.5 1.5 0 0 1 3 13V3A1.5 1.5 0 0 1 4.5 1.5",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M5.5 4.5H10.5M10.5 7.5H10.51M8 7.5H8.01M5.5 7.5H5.51M8 10.5H8.01M5.5 10.5H5.51M8 13H8.01M5.5 13H5.51M10.5 10.5V13",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M6 2H18A2 2 0 0 1 20 4V20A2 2 0 0 1 18 22H6A2 2 0 0 1 4 20V4A2 2 0 0 1 6 2",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M8 6H16M16 10H16.01M12 10H12.01M8 10H8.01M12 14H12.01M8 14H8.01M12 18H12.01M8 18H8.01M16 14V18",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    }
  }
};

export const check = {
  "name": "check",
  "ref": "fsds.icon.check",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M3.5 8.5L6.5 11.5L12.5 4.5",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M5 12.5L9.5 17L19 6.5",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    }
  }
};

export const chevronDown = {
  "name": "chevron-down",
  "ref": "fsds.icon.chevron-down",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M4 6L8 10L12 6",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M6 9L12 15L18 9",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    }
  }
};

export const chevronRight = {
  "name": "chevron-right",
  "ref": "fsds.icon.chevron-right",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M6 4L10 8L6 12",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M9 6L15 12L9 18",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    }
  }
};

export const circle = {
  "name": "circle",
  "ref": "fsds.icon.circle",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M8 2.5A5.5 5.5 0 1 1 8 13.5A5.5 5.5 0 1 1 8 2.5",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M12 3.5A8.5 8.5 0 1 1 12 20.5A8.5 8.5 0 1 1 12 3.5",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round"
        }
      ]
    }
  }
};

export const circleDot = {
  "name": "circle-dot",
  "ref": "fsds.icon.circle-dot",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M8 2A6 6 0 1 1 8 14A6 6 0 1 1 8 2",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M8 8H8.01",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 2,
          "strokeLineCap": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M12 2A10 10 0 1 1 12 22A10 10 0 1 1 12 2",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M12 12H12.01",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 2,
          "strokeLineCap": "round"
        }
      ]
    }
  }
};

export const externalLink = {
  "name": "external-link",
  "ref": "fsds.icon.external-link",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M9 3H4.5A1.5 1.5 0 0 0 3 4.5V11.5A1.5 1.5 0 0 0 4.5 13H11.5A1.5 1.5 0 0 0 13 11.5V7",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M9 3H13V7M13 3L7 9",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M13 4H6.5A2.5 2.5 0 0 0 4 6.5V17.5A2.5 2.5 0 0 0 6.5 20H17.5A2.5 2.5 0 0 0 20 17.5V11",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M14 4H20V10M20 4L11 13",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    }
  }
};

export const home = {
  "name": "home",
  "ref": "fsds.icon.home",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M3 7.5L8 3L13 7.5V13H9.5V9.5H6.5V13H3V7.5Z",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M4.5 11L12 4.5L19.5 11V19.5H14.5V14.5H9.5V19.5H4.5V11Z",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    }
  }
};

export const info = {
  "name": "info",
  "ref": "fsds.icon.info",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M8 2.5A5.5 5.5 0 1 1 8 13.5A5.5 5.5 0 1 1 8 2.5",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M8 7.5V11",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M8 5.25H8.01",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M12 3.5A8.5 8.5 0 1 1 12 20.5A8.5 8.5 0 1 1 12 3.5",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M12 11V16",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M12 8H12.01",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    }
  }
};

export const maximize = {
  "name": "maximize",
  "ref": "fsds.icon.maximize",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M6 3H3V6M10 3H13V6M3 10V13H6M13 10V13H10",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M9 4H4V9M15 4H20V9M4 15V20H9M20 15V20H15",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    }
  }
};

export const menu = {
  "name": "menu",
  "ref": "fsds.icon.menu",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M3 4.5H13M3 8H13M3 11.5H13",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M4 6H20M4 12H20M4 18H20",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round"
        }
      ]
    }
  }
};

export const minimize = {
  "name": "minimize",
  "ref": "fsds.icon.minimize",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M3 6H6V3M13 6H10V3M3 10H6V13M13 10H10V13",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M4 9H9V4M20 9H15V4M4 15H9V20M20 15H15V20",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    }
  }
};

export const moreHorizontal = {
  "name": "more-horizontal",
  "ref": "fsds.icon.more-horizontal",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M3.5 8H3.51M8 8H8.01M12.5 8H12.51",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 2.5,
          "strokeLineCap": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M5 12H5.01M12 12H12.01M19 12H19.01",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 3,
          "strokeLineCap": "round"
        }
      ]
    }
  }
};

export const moreVertical = {
  "name": "more-vertical",
  "ref": "fsds.icon.more-vertical",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M8 3.5H8.01M8 8H8.01M8 12.5H8.01",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 2.5,
          "strokeLineCap": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M12 5H12.01M12 12H12.01M12 19H12.01",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 3,
          "strokeLineCap": "round"
        }
      ]
    }
  }
};

export const panelLeft = {
  "name": "panel-left",
  "ref": "fsds.icon.panel-left",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M3.5 3H12.5A1.5 1.5 0 0 1 14 4.5V11.5A1.5 1.5 0 0 1 12.5 13H3.5A1.5 1.5 0 0 1 2 11.5V4.5A1.5 1.5 0 0 1 3.5 3Z",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineJoin": "round"
        },
        {
          "d": "M6 3V13",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M5.5 4H18.5A2.5 2.5 0 0 1 21 6.5V17.5A2.5 2.5 0 0 1 18.5 20H5.5A2.5 2.5 0 0 1 3 17.5V6.5A2.5 2.5 0 0 1 5.5 4Z",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineJoin": "round"
        },
        {
          "d": "M9 4V20",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5
        }
      ]
    }
  }
};

export const panelRight = {
  "name": "panel-right",
  "ref": "fsds.icon.panel-right",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M3.5 3H12.5A1.5 1.5 0 0 1 14 4.5V11.5A1.5 1.5 0 0 1 12.5 13H3.5A1.5 1.5 0 0 1 2 11.5V4.5A1.5 1.5 0 0 1 3.5 3Z",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineJoin": "round"
        },
        {
          "d": "M10 3V13",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M5.5 4H18.5A2.5 2.5 0 0 1 21 6.5V17.5A2.5 2.5 0 0 1 18.5 20H5.5A2.5 2.5 0 0 1 3 17.5V6.5A2.5 2.5 0 0 1 5.5 4Z",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineJoin": "round"
        },
        {
          "d": "M15 4V20",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5
        }
      ]
    }
  }
};

export const placeholder = {
  "name": "placeholder",
  "ref": "fsds.icon.placeholder",
  "sizes": {
    "17": {
      "viewBox": "0 0 17 17",
      "paths": [
        {
          "d": "M16.5 8.5A8 8 0 1 1 0.5 8.5A8 8 0 1 1 16.5 8.5",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1,
          "strokeLineCap": "round",
          "strokeDasharray": "2 4"
        },
        {
          "d": "M11.5 8.5A3 3 0 1 1 5.5 8.5A3 3 0 1 1 11.5 8.5",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1,
          "strokeLineCap": "round",
          "strokeDasharray": ".125 3"
        }
      ]
    }
  }
};

export const search = {
  "name": "search",
  "ref": "fsds.icon.search",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M7 3A4 4 0 1 1 7 11A4 4 0 1 1 7 3",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M10 10L13.5 13.5",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M10.5 4.5A6 6 0 1 1 10.5 16.5A6 6 0 1 1 10.5 4.5",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M15 15L19.5 19.5",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    }
  }
};

export const triangleAlert = {
  "name": "triangle-alert",
  "ref": "fsds.icon.triangle-alert",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M8 2.25L14.5 13.25H1.5L8 2.25Z",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M8 6.5V9",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round"
        },
        {
          "d": "M8 11.25H8.01",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M12 3.5L21.5 19.5H2.5L12 3.5Z",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M12 9.5V14",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round"
        },
        {
          "d": "M12 16.75H12.01",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round"
        }
      ]
    }
  }
};

export const user = {
  "name": "user",
  "ref": "fsds.icon.user",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M8 4.25A2.25 2.25 0 1 1 8 8.75A2.25 2.25 0 1 1 8 4.25",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M3.5 13.5A4.5 4.5 0 0 1 12.5 13.5",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M12 6.5A3 3 0 1 1 12 12.5A3 3 0 1 1 12 6.5",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M5.5 20A6.5 6.5 0 0 1 18.5 20",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    }
  }
};

export const x = {
  "name": "x",
  "ref": "fsds.icon.x",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M4 4L12 12",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M12 4L4 12",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M6 6L18 18",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M18 6L6 18",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    }
  }
};

export const icons = {
  "alarm": alarm,
  "arrow-down": arrowDown,
  "arrow-left": arrowLeft,
  "arrow-right": arrowRight,
  "arrow-up": arrowUp,
  "arrow-up-down": arrowUpDown,
  "at-sign": atSign,
  "baseline": baseline,
  "calculator": calculator,
  "check": check,
  "chevron-down": chevronDown,
  "chevron-right": chevronRight,
  "circle": circle,
  "circle-dot": circleDot,
  "external-link": externalLink,
  "home": home,
  "info": info,
  "maximize": maximize,
  "menu": menu,
  "minimize": minimize,
  "more-horizontal": moreHorizontal,
  "more-vertical": moreVertical,
  "panel-left": panelLeft,
  "panel-right": panelRight,
  "placeholder": placeholder,
  "search": search,
  "triangle-alert": triangleAlert,
  "user": user,
  "x": x,
};

export function resolveIcon(name, sizePx) {
  const glyph = icons[name];
  if (!glyph) return undefined;
  const authored = Object.keys(glyph.sizes)
    .map(Number)
    .sort((a, b) => a - b);
  // Largest authored size <= the request; the smallest authored size when
  // the request undershoots every variant. Sizes are first-class authored
  // glyphs — selection picks a variant, it never synthesizes one.
  let chosen = authored[0];
  for (const size of authored) {
    if (size <= sizePx) chosen = size;
  }
  const variant = glyph.sizes[String(chosen)];
  return { name: glyph.name, size: chosen, viewBox: variant.viewBox, paths: variant.paths };
}
