// @generated by @full-stack-ds/iconography build/build.mjs — do not edit.
// Committed build output (drift-gated); the authoring source of truth is
// icons/<Name>/<Name>.icon.json. Rebuild with `pnpm run build` in this package.

export const check = {
  "name": "check",
  "ref": "fsds.icon.check",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M3.5 8.5L6.5 11.5L12.5 4.5",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M5 12.5L9.5 17L19 6.5",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        }
      ]
    }
  }
};

export const circle = {
  "name": "circle",
  "ref": "fsds.icon.circle",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M8 2.5A5.5 5.5 0 1 1 8 13.5A5.5 5.5 0 1 1 8 2.5",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M12 3.5A8.5 8.5 0 1 1 12 20.5A8.5 8.5 0 1 1 12 3.5",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round"
        }
      ]
    }
  }
};

export const placeholder = {
  "name": "placeholder",
  "ref": "fsds.icon.placeholder",
  "sizes": {
    "17": {
      "viewBox": "0 0 17 17",
      "paths": [
        {
          "d": "M16.5 8.5A8 8 0 1 1 0.5 8.5A8 8 0 1 1 16.5 8.5",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1,
          "strokeLineCap": "round",
          "strokeDasharray": "2 4"
        },
        {
          "d": "M11.5 8.5A3 3 0 1 1 5.5 8.5A3 3 0 1 1 11.5 8.5",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1,
          "strokeLineCap": "round",
          "strokeDasharray": ".125 3"
        }
      ]
    }
  }
};

export const triangleAlert = {
  "name": "triangle-alert",
  "ref": "fsds.icon.triangle-alert",
  "sizes": {
    "16": {
      "viewBox": "0 0 16 16",
      "paths": [
        {
          "d": "M8 2.25L14.5 13.25H1.5L8 2.25Z",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M8 6.5V9",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round"
        },
        {
          "d": "M8 11.25H8.01",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round"
        }
      ]
    },
    "24": {
      "viewBox": "0 0 24 24",
      "paths": [
        {
          "d": "M12 3.5L21.5 19.5H2.5L12 3.5Z",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round",
          "strokeLineJoin": "round"
        },
        {
          "d": "M12 9.5V14",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round"
        },
        {
          "d": "M12 16.75H12.01",
          "fill": "none",
          "stroke": "currentColor",
          "strokeWidth": 1.5,
          "strokeLineCap": "round"
        }
      ]
    }
  }
};

export const icons = {
  "check": check,
  "circle": circle,
  "placeholder": placeholder,
  "triangle-alert": triangleAlert,
};

export function resolveIcon(name, sizePx) {
  const glyph = icons[name];
  if (!glyph) return undefined;
  const authored = Object.keys(glyph.sizes)
    .map(Number)
    .sort((a, b) => a - b);
  // Largest authored size <= the request; the smallest authored size when
  // the request undershoots every variant. Sizes are first-class authored
  // glyphs — selection picks a variant, it never synthesizes one.
  let chosen = authored[0];
  for (const size of authored) {
    if (size <= sizePx) chosen = size;
  }
  const variant = glyph.sizes[String(chosen)];
  return { name: glyph.name, size: chosen, viewBox: variant.viewBox, paths: variant.paths };
}
