// @generated by @full-stack-ds/iconography build/build.mjs — do not edit.
// Committed build output (drift-gated); the authoring source of truth is
// icons/<Name>/<Name>.icon.json. Rebuild with `pnpm run build` in this package.

export interface IconGlyphPath {
  readonly d: string;
  readonly fill?: "none" | "currentColor";
  readonly stroke?: "none" | "currentColor";
  readonly strokeWidth?: number;
  readonly strokeLineCap?: "butt" | "round" | "square";
  readonly strokeLineJoin?: "arcs" | "bevel" | "miter" | "miter-clip" | "round";
  readonly strokeDasharray?: string;
  readonly fillRule?: "nonzero" | "evenodd";
  readonly clipRule?: "nonzero" | "evenodd";
}

export interface IconGlyphVariant {
  readonly viewBox: string;
  readonly paths: readonly IconGlyphPath[];
}

export interface IconGlyph {
  readonly name: string;
  readonly ref: string;
  readonly sizes: Readonly<Record<string, IconGlyphVariant>>;
}

export interface ResolvedIconGlyph extends IconGlyphVariant {
  readonly name: string;
  readonly size: number;
}

export declare const check: IconGlyph;
export declare const circle: IconGlyph;
export declare const placeholder: IconGlyph;
export declare const triangleAlert: IconGlyph;

export declare const icons: Readonly<Record<string, IconGlyph>>;

export declare function resolveIcon(name: string, sizePx: number): ResolvedIconGlyph | undefined;
