// @generated:start imports
import { LitElement, html, css, nothing } from 'lit';
import { property } from 'lit/decorators.js';
import { ifDefined } from 'lit/directives/if-defined.js';
import { styleMap } from 'lit/directives/style-map.js';
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type ProgressVariant = "linear" | "circular";
export type ProgressSize = "sm" | "md" | "lg";
export type ProgressIntent = "info" | "success" | "warning" | "danger";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
export class ProgressElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-component]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-component]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-component]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .progress {
      --fsds-progress-color-text-default: var(--fsds-semantic-color-foreground-secondary, #474647);
      --fsds-progress-spacing-gap: var(--fsds-core-spacing-size-02, 2px);
      --fsds-progress-motion-duration-indeterminate: var(--fsds-core-motion-duration-extra-long1, 1500ms);
      --fsds-progress-color-track-background: var(--fsds-semantic-color-background-secondary, #f7f7f7);
      --fsds-progress-color-fill-info: var(--fsds-semantic-color-status-info, #0566fe);
      --fsds-progress-color-fill-success: var(--fsds-semantic-color-status-success, #497f21);
      --fsds-progress-color-fill-warning: var(--fsds-semantic-color-status-warning, #ae5d00);
      --fsds-progress-color-fill-danger: var(--fsds-semantic-color-status-danger, #d92d2e);
    }

    @layer components.defaults {
    .progress {
      display: block;
      box-sizing: border-box;
      padding-block-start: var(--fsds-box-model-padding-block-start, 0);
      padding-block-end: var(--fsds-box-model-padding-block-end, 0);
      padding-inline-start: var(--fsds-box-model-padding-inline-start, 0);
      padding-inline-end: var(--fsds-box-model-padding-inline-end, 0);
      gap: var(--fsds-progress-design-root-spacing-gap, var(--fsds-progress-spacing-gap, 2px));
      width: var(--fsds-box-model-width, 100%);
      min-width: var(--fsds-box-model-min-width, 0);
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-box-model-height, 8px);
      min-height: var(--fsds-box-model-min-height, 0);
      max-height: var(--fsds-box-model-max-height, none);
      color: var(--fsds-progress-design-root-foreground-color, var(--fsds-progress-color-text-default, #474647));
      transition-duration: var(--fsds-progress-design-root-motion-duration, var(--fsds-progress-motion-duration-indeterminate, 1500ms));
    }

    .progress__track {
      background-color: var(--fsds-progress-design-track-background-fill, var(--fsds-progress-color-track-background, #f7f7f7));
      display: block;
      width: 100%;
      height: 100%;
      overflow: hidden;
    }

    .progress__fill {
      background-color: var(--fsds-progress-design-fill-background-fill, var(--fsds-progress-color-fill-info, #0566fe));
      display: block;
      height: 100%;
      width: calc(var(--fsds-progress-fill-width, 0) * 1%);
    }

    .progress__value {
      display: inline-block;
      color: var(--fsds-progress-design-value-foreground-color, var(--fsds-progress-color-text-default, #474647));
      font-size: var(--fsds-progress-design-value-typography-size, 0.875em);
      margin-left: var(--fsds-progress-spacing-gap, 2px);
    }

    .progress--info .progress__fill {
      background-color: var(--fsds-progress-design-condition-b054611f82c6-background-fill, var(--fsds-progress-color-fill-info, #0566fe));
    }

    .progress--success .progress__fill {
      background-color: var(--fsds-progress-design-condition-d88c0aa44206-background-fill, var(--fsds-progress-color-fill-success, #497f21));
    }

    .progress--warning .progress__fill {
      background-color: var(--fsds-progress-design-condition-542ca89dfc3d-background-fill, var(--fsds-progress-color-fill-warning, #ae5d00));
    }

    .progress--danger .progress__fill {
      background-color: var(--fsds-progress-design-condition-fdd1c2c16a8f-background-fill, var(--fsds-progress-color-fill-danger, #d92d2e));
    }
    }
  `;

  @property({ type: Number }) value?: number;
  @property({ type: String }) variant?: ProgressVariant;
  @property({ type: String }) size?: ProgressSize;
  @property({ type: String }) intent?: ProgressIntent;
  @property({ type: String }) label?: string;
  @property({ type: Boolean }) showValue?: boolean;
  @property({ attribute: false }) formatValue?: (value: number, max: number) => string;

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute("data-fsds-component", "progress");
  }

  private computeClasses(): string {
    return [
      "progress",
      this.variant ? `progress--${this.variant}` : null,
      this.size ? `progress--${this.size}` : null,
      this.intent ? `progress--${this.intent}` : null,
    ].filter(Boolean).join(" ");
  }

  override render() {
    return html`<div class="${this.computeClasses()}" role="progressbar" aria-valuenow=${ifDefined(this.value)} aria-valuemin="0" aria-valuemax="100" aria-label=${ifDefined(this.label)}>
  <span class=${'progress__track'} aria-hidden="true">
    <span class=${'progress__fill'} style=${styleMap({ '--fsds-progress-fill-width': this.value === undefined ? undefined : String(this.value) })}></span>
  </span>
  ${this.showValue ? html`
  <span class=${'progress__value'}>
    <slot></slot>
  </span>
  ` : nothing}
</div>`;
  }
}

customElements.define('fsds-progress', ProgressElement);

// @generated:end

// @custom:start trailing

// @custom:end