// @generated:start imports
import { LitElement, html, css, nothing } from 'lit';
import { property } from 'lit/decorators.js';
import { TextFieldBehavior } from './TextFieldBehavior.js';
import { ifDefined } from 'lit/directives/if-defined.js';
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
export class TextFieldElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .text-field {
      --fsds-text-field-spacing-gap: var(--fsds-core-spacing-size-04, 8px);
      --fsds-text-field-field-padding-block: var(--fsds-semantic-input-size-medium-padding-block, 4px);
      --fsds-text-field-field-padding-inline: var(--fsds-semantic-input-size-medium-padding-inline, 8px);
      --fsds-text-field-field-min-height: var(--fsds-semantic-input-size-medium-min-height, 32px);
      --fsds-text-field-border-width: var(--fsds-semantic-shape-control-border-default-width, 1px);
      --fsds-text-field-border-radius: var(--fsds-semantic-shape-control-radius-default, 6px);
      --fsds-text-field-color-input-background: var(--fsds-semantic-color-background-primary, #ffffff);
      --fsds-text-field-color-input-text: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-text-field-color-input-placeholder: var(--fsds-semantic-color-foreground-tertiary, #727272);
      --fsds-text-field-color-input-border: var(--fsds-semantic-color-border-default, #a0a0a1);
      --fsds-text-field-color-input-border-hover: var(--fsds-semantic-color-border-hover, #888889);
      --fsds-text-field-color-input-background-disabled: var(--fsds-semantic-interaction-background-disabled, #b8b8b8);
      --fsds-text-field-color-input-text-disabled: var(--fsds-semantic-color-foreground-disabled, #727272);
      --fsds-text-field-color-input-border-disabled: var(--fsds-semantic-color-border-disabled, #b8b8b8);
      --fsds-text-field-color-input-border-error: var(--fsds-semantic-color-status-danger, #d92d2e);
      --fsds-text-field-color-error: var(--fsds-semantic-color-foreground-danger, #d92d2e);
      --fsds-text-field-color-supporting-text: var(--fsds-semantic-color-foreground-tertiary, #727272);
      --fsds-text-field-typography-label-size: var(--fsds-semantic-typography-caption-01, 0.875rem);
      --fsds-text-field-typography-label-weight: var(--fsds-semantic-typography-font-weight-medium, 500);
      --fsds-text-field-typography-label-line-height: var(--fsds-semantic-typography-line-height-normal, 1.5);
      --fsds-text-field-typography-field-size: var(--fsds-semantic-typography-body-02, 1rem);
      --fsds-text-field-typography-field-line-height: var(--fsds-semantic-typography-line-height-body, 1.5);
      --fsds-text-field-typography-supporting-size: var(--fsds-semantic-typography-caption-01, 0.875rem);
      --fsds-text-field-typography-supporting-line-height: var(--fsds-semantic-typography-line-height-normal, 1.5);
      --fsds-text-field-opacity-disabled: var(--fsds-semantic-interaction-disabled-opacity, 0.5);
      --fsds-text-field-focus-ring-width: var(--fsds-semantic-focus-ring-width, 2px);
      --fsds-text-field-focus-ring-color: var(--fsds-semantic-focus-ring-color, #0566fe);
      --fsds-text-field-focus-ring-style: var(--fsds-semantic-focus-ring-style, solid);
      --fsds-text-field-focus-ring-offset: var(--fsds-semantic-focus-ring-offset, 2px);
      --fsds-text-field-motion-duration-fast: var(--fsds-core-motion-duration-short, 150ms);
      --fsds-text-field-motion-easing-standard: var(--fsds-core-motion-easing-standard, cubic-bezier(0.4, 0, 0.2, 1));
    }

    @layer components.defaults {
    .text-field {
      padding-block-start: var(--fsds-box-model-padding-block-start, var(--fsds-semantic-input-size-medium-padding-block, 4px));
      padding-block-end: var(--fsds-box-model-padding-block-end, var(--fsds-semantic-input-size-medium-padding-block, 4px));
      padding-inline-start: var(--fsds-box-model-padding-inline-start, var(--fsds-semantic-input-size-medium-padding-inline, 8px));
      padding-inline-end: var(--fsds-box-model-padding-inline-end, var(--fsds-semantic-input-size-medium-padding-inline, 8px));
      gap: var(--fsds-text-field-design-root-spacing-gap, var(--fsds-text-field-spacing-gap, 8px));
      width: var(--fsds-box-model-width, auto);
      min-width: var(--fsds-box-model-min-width, 0);
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, var(--fsds-semantic-input-size-medium-min-height, 32px));
      max-height: var(--fsds-box-model-max-height, none);
      display: flex;
      flex-direction: column;
    }

    .text-field__label {
      display: inline-block;
      font-size: var(--fsds-text-field-design-label-typography-size, var(--fsds-text-field-typography-label-size, 0.875rem));
      font-weight: var(--fsds-text-field-design-label-typography-weight, var(--fsds-text-field-typography-label-weight, 500));
      line-height: var(--fsds-text-field-design-label-typography-line-height, var(--fsds-text-field-typography-label-line-height, 1.5));
      color: var(--fsds-text-field-design-label-foreground-color, var(--fsds-text-field-color-input-text, #141414));
    }

    .text-field__field {
      display: block;
      width: 100%;
      box-sizing: border-box;
      border-style: var(--fsds-text-field-design-field-border-style, solid);
      background-color: var(--fsds-text-field-design-field-background-fill, var(--fsds-text-field-color-input-background, #ffffff));
      border-color: var(--fsds-text-field-design-field-border-color, var(--fsds-text-field-color-input-border, #a0a0a1));
      border-width: var(--fsds-text-field-design-field-border-width, var(--fsds-text-field-border-width, 1px));
      border-radius: var(--fsds-text-field-design-field-shape-radius, var(--fsds-text-field-border-radius, 6px));
      color: var(--fsds-text-field-design-field-foreground-color, var(--fsds-text-field-color-input-text, #141414));
      font-size: var(--fsds-text-field-design-field-typography-size, var(--fsds-text-field-typography-field-size, 1rem));
      line-height: var(--fsds-text-field-design-field-typography-line-height, var(--fsds-text-field-typography-field-line-height, 1.5));
      min-height: var(--fsds-text-field-design-field-sizing-min-height, var(--fsds-text-field-field-min-height, 32px));
      padding-block: var(--fsds-text-field-design-field-spacing-padding-block, var(--fsds-text-field-field-padding-block, 4px));
      padding-inline: var(--fsds-text-field-design-field-spacing-padding-inline, var(--fsds-text-field-field-padding-inline, 8px));
      transition-property: background-color, border-color, color, outline-color;
      transition-duration: var(--fsds-text-field-design-field-motion-duration, var(--fsds-text-field-motion-duration-fast, 150ms));
      transition-timing-function: var(--fsds-text-field-design-field-motion-easing, var(--fsds-text-field-motion-easing-standard, cubic-bezier(0.4, 0, 0.2, 1)));
    }

    .text-field__description {
      display: block;
      font-size: var(--fsds-text-field-design-description-typography-size, var(--fsds-text-field-typography-supporting-size, 0.875rem));
      line-height: var(--fsds-text-field-design-description-typography-line-height, var(--fsds-text-field-typography-supporting-line-height, 1.5));
      color: var(--fsds-text-field-design-description-foreground-color, var(--fsds-text-field-color-supporting-text, #727272));
    }

    .text-field__error {
      display: block;
      font-size: var(--fsds-text-field-design-error-typography-size, var(--fsds-text-field-typography-supporting-size, 0.875rem));
      line-height: var(--fsds-text-field-design-error-typography-line-height, var(--fsds-text-field-typography-supporting-line-height, 1.5));
      color: var(--fsds-text-field-design-error-foreground-color, var(--fsds-text-field-color-error, #d92d2e));
    }

    .text-field__field::placeholder {
      color: var(--fsds-text-field-design-condition-cd558e65951a-foreground-color, var(--fsds-text-field-color-input-placeholder, #727272));
    }

    .text-field__field:hover:not(:disabled) {
      border-color: var(--fsds-text-field-design-condition-42d441aafe9d-border-color, var(--fsds-text-field-color-input-border-hover, #888889));
    }

    .text-field__field:focus-visible:not([aria-disabled="true"]) {
      border-color: var(--fsds-text-field-design-condition-77dab6d6abaf-border-color, var(--fsds-text-field-focus-ring-color, #0566fe));
      outline-width: var(--fsds-text-field-design-condition-77dab6d6abaf-focus-width, var(--fsds-text-field-focus-ring-width, 2px));
      outline-color: var(--fsds-text-field-design-condition-77dab6d6abaf-focus-color, var(--fsds-text-field-focus-ring-color, #0566fe));
      outline-style: var(--fsds-text-field-design-condition-77dab6d6abaf-focus-style, var(--fsds-text-field-focus-ring-style, solid));
      outline-offset: var(--fsds-text-field-design-condition-77dab6d6abaf-focus-offset, var(--fsds-text-field-focus-ring-offset, 2px));
    }

    .text-field--invalid .text-field__field {
      border-color: var(--fsds-text-field-design-condition-552c09ee517a-border-color, var(--fsds-text-field-color-input-border-error, #d92d2e));
    }

    .text-field--invalid .text-field__field:focus-visible:not([aria-disabled="true"]) {
      border-color: var(--fsds-text-field-design-condition-2e4a716b9443-border-color, var(--fsds-text-field-color-input-border-error, #d92d2e));
      outline-color: var(--fsds-text-field-design-condition-2e4a716b9443-focus-color, var(--fsds-text-field-color-input-border-error, #d92d2e));
    }

    .text-field__field:disabled {
      background-color: var(--fsds-text-field-design-condition-6d2f506c00a2-background-fill, var(--fsds-text-field-color-input-background-disabled, #b8b8b8));
      border-color: var(--fsds-text-field-design-condition-6d2f506c00a2-border-color, var(--fsds-text-field-color-input-border-disabled, #b8b8b8));
      color: var(--fsds-text-field-design-condition-6d2f506c00a2-foreground-color, var(--fsds-text-field-color-input-text-disabled, #727272));
      opacity: var(--fsds-text-field-design-condition-6d2f506c00a2-appearance-opacity, var(--fsds-text-field-opacity-disabled, 0.5));
      cursor: not-allowed;
    }
    }
  `;

  @property({ type: String }) type?: string;
  @property({ type: String }) value?: string;
  @property({ type: String }) defaultValue?: string;
  @property({ attribute: false }) onChange?: (value: string) => void;
  @property({ type: Boolean }) invalid?: boolean;
  @property({ type: Boolean }) disabled?: boolean;
  @property({ type: Boolean }) required?: boolean;
  @property({ type: String }) name?: string;
  @property({ type: String }) ariaDescribedby?: string;

  private behavior = new TextFieldBehavior(this, {
    value: () => this.value,
    defaultValue: this.defaultValue,
    onChange: (v) => this.onChange?.(v),
  });

  private handleValueChange(event: Event): void {
    this.behavior.setValue((event.target as HTMLInputElement).value);
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute("data-fsds-component", "text-field");
  }

  private computeClasses(): string {
    return [
      "text-field",
      this.invalid ? "text-field--invalid" : null,
      this.disabled ? "text-field--disabled" : null,
    ].filter(Boolean).join(" ");
  }

  override render() {
    return html`<div class="${this.computeClasses()}" data-fsds-box="">
  <label class=${'text-field__label'} id="text-field-label">
    <slot name="label" @slotchange=${() => this.requestUpdate()}></slot>
  </label>
  <input class=${'text-field__field'} @input=${(e: Event) => this.handleValueChange(e)} type=${ifDefined(this.type)} .value=${this.behavior.value} ?disabled=${this.disabled ?? false} name=${ifDefined(this.name)} ?required=${this.required ?? false} aria-invalid=${ifDefined(this.invalid === undefined ? undefined : (this.invalid ? 'true' : 'false'))} aria-labelledby=${ifDefined([this.querySelector('[slot="label"]') !== null ? 'text-field-label' : null].filter(Boolean).join(' ') || undefined)} aria-describedby=${ifDefined([this.querySelector('[slot="description"]') !== null ? 'text-field-description' : null, this.querySelector('[slot="error"]') !== null && this.invalid ? 'text-field-error' : null, this.ariaDescribedby].filter(Boolean).join(' ') || undefined)} />
  <span class=${'text-field__description'} id="text-field-description">
    <slot name="description" @slotchange=${() => this.requestUpdate()}></slot>
  </span>
  <span class=${'text-field__error'} role="alert" id="text-field-error">
    <slot name="error" @slotchange=${() => this.requestUpdate()}></slot>
  </span>
</div>`;
  }
}

customElements.define('fsds-text-field', TextFieldElement);


export class TextFieldDescriptionElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .text-field {
      --fsds-text-field-spacing-gap: var(--fsds-core-spacing-size-04, 8px);
      --fsds-text-field-field-padding-block: var(--fsds-semantic-input-size-medium-padding-block, 4px);
      --fsds-text-field-field-padding-inline: var(--fsds-semantic-input-size-medium-padding-inline, 8px);
      --fsds-text-field-field-min-height: var(--fsds-semantic-input-size-medium-min-height, 32px);
      --fsds-text-field-border-width: var(--fsds-semantic-shape-control-border-default-width, 1px);
      --fsds-text-field-border-radius: var(--fsds-semantic-shape-control-radius-default, 6px);
      --fsds-text-field-color-input-background: var(--fsds-semantic-color-background-primary, #ffffff);
      --fsds-text-field-color-input-text: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-text-field-color-input-placeholder: var(--fsds-semantic-color-foreground-tertiary, #727272);
      --fsds-text-field-color-input-border: var(--fsds-semantic-color-border-default, #a0a0a1);
      --fsds-text-field-color-input-border-hover: var(--fsds-semantic-color-border-hover, #888889);
      --fsds-text-field-color-input-background-disabled: var(--fsds-semantic-interaction-background-disabled, #b8b8b8);
      --fsds-text-field-color-input-text-disabled: var(--fsds-semantic-color-foreground-disabled, #727272);
      --fsds-text-field-color-input-border-disabled: var(--fsds-semantic-color-border-disabled, #b8b8b8);
      --fsds-text-field-color-input-border-error: var(--fsds-semantic-color-status-danger, #d92d2e);
      --fsds-text-field-color-error: var(--fsds-semantic-color-foreground-danger, #d92d2e);
      --fsds-text-field-color-supporting-text: var(--fsds-semantic-color-foreground-tertiary, #727272);
      --fsds-text-field-typography-label-size: var(--fsds-semantic-typography-caption-01, 0.875rem);
      --fsds-text-field-typography-label-weight: var(--fsds-semantic-typography-font-weight-medium, 500);
      --fsds-text-field-typography-label-line-height: var(--fsds-semantic-typography-line-height-normal, 1.5);
      --fsds-text-field-typography-field-size: var(--fsds-semantic-typography-body-02, 1rem);
      --fsds-text-field-typography-field-line-height: var(--fsds-semantic-typography-line-height-body, 1.5);
      --fsds-text-field-typography-supporting-size: var(--fsds-semantic-typography-caption-01, 0.875rem);
      --fsds-text-field-typography-supporting-line-height: var(--fsds-semantic-typography-line-height-normal, 1.5);
      --fsds-text-field-opacity-disabled: var(--fsds-semantic-interaction-disabled-opacity, 0.5);
      --fsds-text-field-focus-ring-width: var(--fsds-semantic-focus-ring-width, 2px);
      --fsds-text-field-focus-ring-color: var(--fsds-semantic-focus-ring-color, #0566fe);
      --fsds-text-field-focus-ring-style: var(--fsds-semantic-focus-ring-style, solid);
      --fsds-text-field-focus-ring-offset: var(--fsds-semantic-focus-ring-offset, 2px);
      --fsds-text-field-motion-duration-fast: var(--fsds-core-motion-duration-short, 150ms);
      --fsds-text-field-motion-easing-standard: var(--fsds-core-motion-easing-standard, cubic-bezier(0.4, 0, 0.2, 1));
    }

    @layer components.defaults {
    .text-field {
      padding-block-start: var(--fsds-box-model-padding-block-start, var(--fsds-semantic-input-size-medium-padding-block, 4px));
      padding-block-end: var(--fsds-box-model-padding-block-end, var(--fsds-semantic-input-size-medium-padding-block, 4px));
      padding-inline-start: var(--fsds-box-model-padding-inline-start, var(--fsds-semantic-input-size-medium-padding-inline, 8px));
      padding-inline-end: var(--fsds-box-model-padding-inline-end, var(--fsds-semantic-input-size-medium-padding-inline, 8px));
      gap: var(--fsds-text-field-design-root-spacing-gap, var(--fsds-text-field-spacing-gap, 8px));
      width: var(--fsds-box-model-width, auto);
      min-width: var(--fsds-box-model-min-width, 0);
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, var(--fsds-semantic-input-size-medium-min-height, 32px));
      max-height: var(--fsds-box-model-max-height, none);
      display: flex;
      flex-direction: column;
    }

    .text-field__label {
      display: inline-block;
      font-size: var(--fsds-text-field-design-label-typography-size, var(--fsds-text-field-typography-label-size, 0.875rem));
      font-weight: var(--fsds-text-field-design-label-typography-weight, var(--fsds-text-field-typography-label-weight, 500));
      line-height: var(--fsds-text-field-design-label-typography-line-height, var(--fsds-text-field-typography-label-line-height, 1.5));
      color: var(--fsds-text-field-design-label-foreground-color, var(--fsds-text-field-color-input-text, #141414));
    }

    .text-field__field {
      display: block;
      width: 100%;
      box-sizing: border-box;
      border-style: var(--fsds-text-field-design-field-border-style, solid);
      background-color: var(--fsds-text-field-design-field-background-fill, var(--fsds-text-field-color-input-background, #ffffff));
      border-color: var(--fsds-text-field-design-field-border-color, var(--fsds-text-field-color-input-border, #a0a0a1));
      border-width: var(--fsds-text-field-design-field-border-width, var(--fsds-text-field-border-width, 1px));
      border-radius: var(--fsds-text-field-design-field-shape-radius, var(--fsds-text-field-border-radius, 6px));
      color: var(--fsds-text-field-design-field-foreground-color, var(--fsds-text-field-color-input-text, #141414));
      font-size: var(--fsds-text-field-design-field-typography-size, var(--fsds-text-field-typography-field-size, 1rem));
      line-height: var(--fsds-text-field-design-field-typography-line-height, var(--fsds-text-field-typography-field-line-height, 1.5));
      min-height: var(--fsds-text-field-design-field-sizing-min-height, var(--fsds-text-field-field-min-height, 32px));
      padding-block: var(--fsds-text-field-design-field-spacing-padding-block, var(--fsds-text-field-field-padding-block, 4px));
      padding-inline: var(--fsds-text-field-design-field-spacing-padding-inline, var(--fsds-text-field-field-padding-inline, 8px));
      transition-property: background-color, border-color, color, outline-color;
      transition-duration: var(--fsds-text-field-design-field-motion-duration, var(--fsds-text-field-motion-duration-fast, 150ms));
      transition-timing-function: var(--fsds-text-field-design-field-motion-easing, var(--fsds-text-field-motion-easing-standard, cubic-bezier(0.4, 0, 0.2, 1)));
    }

    .text-field__description {
      display: block;
      font-size: var(--fsds-text-field-design-description-typography-size, var(--fsds-text-field-typography-supporting-size, 0.875rem));
      line-height: var(--fsds-text-field-design-description-typography-line-height, var(--fsds-text-field-typography-supporting-line-height, 1.5));
      color: var(--fsds-text-field-design-description-foreground-color, var(--fsds-text-field-color-supporting-text, #727272));
    }

    .text-field__error {
      display: block;
      font-size: var(--fsds-text-field-design-error-typography-size, var(--fsds-text-field-typography-supporting-size, 0.875rem));
      line-height: var(--fsds-text-field-design-error-typography-line-height, var(--fsds-text-field-typography-supporting-line-height, 1.5));
      color: var(--fsds-text-field-design-error-foreground-color, var(--fsds-text-field-color-error, #d92d2e));
    }

    .text-field__field::placeholder {
      color: var(--fsds-text-field-design-condition-cd558e65951a-foreground-color, var(--fsds-text-field-color-input-placeholder, #727272));
    }

    .text-field__field:hover:not(:disabled) {
      border-color: var(--fsds-text-field-design-condition-42d441aafe9d-border-color, var(--fsds-text-field-color-input-border-hover, #888889));
    }

    .text-field__field:focus-visible:not([aria-disabled="true"]) {
      border-color: var(--fsds-text-field-design-condition-77dab6d6abaf-border-color, var(--fsds-text-field-focus-ring-color, #0566fe));
      outline-width: var(--fsds-text-field-design-condition-77dab6d6abaf-focus-width, var(--fsds-text-field-focus-ring-width, 2px));
      outline-color: var(--fsds-text-field-design-condition-77dab6d6abaf-focus-color, var(--fsds-text-field-focus-ring-color, #0566fe));
      outline-style: var(--fsds-text-field-design-condition-77dab6d6abaf-focus-style, var(--fsds-text-field-focus-ring-style, solid));
      outline-offset: var(--fsds-text-field-design-condition-77dab6d6abaf-focus-offset, var(--fsds-text-field-focus-ring-offset, 2px));
    }

    .text-field--invalid .text-field__field {
      border-color: var(--fsds-text-field-design-condition-552c09ee517a-border-color, var(--fsds-text-field-color-input-border-error, #d92d2e));
    }

    .text-field--invalid .text-field__field:focus-visible:not([aria-disabled="true"]) {
      border-color: var(--fsds-text-field-design-condition-2e4a716b9443-border-color, var(--fsds-text-field-color-input-border-error, #d92d2e));
      outline-color: var(--fsds-text-field-design-condition-2e4a716b9443-focus-color, var(--fsds-text-field-color-input-border-error, #d92d2e));
    }

    .text-field__field:disabled {
      background-color: var(--fsds-text-field-design-condition-6d2f506c00a2-background-fill, var(--fsds-text-field-color-input-background-disabled, #b8b8b8));
      border-color: var(--fsds-text-field-design-condition-6d2f506c00a2-border-color, var(--fsds-text-field-color-input-border-disabled, #b8b8b8));
      color: var(--fsds-text-field-design-condition-6d2f506c00a2-foreground-color, var(--fsds-text-field-color-input-text-disabled, #727272));
      opacity: var(--fsds-text-field-design-condition-6d2f506c00a2-appearance-opacity, var(--fsds-text-field-opacity-disabled, 0.5));
      cursor: not-allowed;
    }
    }
  `;

  override render() {
    return html`<fsds-stack as="p" class="text-field__description"><slot></slot></fsds-stack>`;
  }
}

customElements.define('fsds-text-field-description', TextFieldDescriptionElement);
// @generated:end

// @custom:start trailing

// @custom:end