/**
 * Pins the contract-driven primitive emit path (FEAT-STACK-PRIMITIVE-CODEGEN-01).
 *
 * The Stack layout primitive is generated from primitives/Stack.primitive.json
 * across five web frameworks. These tests pin the framework-neutral IR reader
 * and assert every framework emitter lowers the same contract facts — the
 * token-driven gap in particular, since that is the fact all gates would
 * otherwise miss (a hard-coded or dropped gap still typechecks and renders).
 */
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { createReactEmitter } from "./frameworks/react/factory.js";
import { createVueEmitter } from "./frameworks/vue/factory.js";
import { createSvelteEmitter } from "./frameworks/svelte/factory.js";
import { createAngularEmitter } from "./frameworks/angular/factory.js";
import { createLitEmitter } from "./frameworks/lit/factory.js";
import { readPrimitiveIR } from "./primitive-contract.js";

const CONTRACTS_ROOT = path.resolve(__dirname, "..", "..", "ds-contracts");
const GAP_VAR = "--fsds-semantic-spacing-gap-stack";

describe("readPrimitiveIR", () => {
  it("parses the Stack layout facts from the real contract", () => {
    const ir = readPrimitiveIR(CONTRACTS_ROOT);
    expect(ir.name).toBe("Stack");
    expect(ir.layout.classPrefix).toBe("stack");
    // display map carries the six layout modes, with `native` -> null.
    expect(ir.layout.displayByMode.stack).toBe("flex");
    expect(ir.layout.displayByMode["inline-stack"]).toBe("inline-flex");
    expect(ir.layout.displayByMode.native).toBeNull();
    // axis map: vertical -> column, horizontal -> row.
    expect(ir.layout.axisByVariant.vertical).toBe("column");
    expect(ir.layout.axisByVariant.horizontal).toBe("row");
    // gap is token-driven, not a literal dimension.
    expect(ir.layout.gap?.cssVar).toBe(GAP_VAR);
    expect(ir.layout.gap?.token).toBe("spacing.gap.stack");
  });

  it("derives axisModes as exactly the flex-bearing display modes", () => {
    const ir = readPrimitiveIR(CONTRACTS_ROOT);
    // block / inline / contents / native do not lay out on a flex axis.
    expect([...ir.axisModes].sort()).toEqual(["inline-stack", "stack"]);
  });

  it("throws when the contract is missing its layout facts", () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "prim-"));
    const prims = path.join(dir, "primitives");
    fs.mkdirSync(prims, { recursive: true });
    // A contract with no `layout` block — the schema is the first gate; this
    // asserts the reader is defense-in-depth and fails loud rather than
    // silently emitting a primitive with no display/gap facts.
    fs.writeFileSync(
      path.join(prims, "Stack.primitive.json"),
      JSON.stringify({ name: "Stack", props: [], implementation: { targets: {} } }),
    );
    expect(() => readPrimitiveIR(dir)).toThrow(/layout/i);
  });
});

describe("emitPrimitives across frameworks", () => {
  const ir = readPrimitiveIR(CONTRACTS_ROOT);
  const opts = { componentsRoot: "/x/components", contractsRoot: CONTRACTS_ROOT };

  const emitters = [
    ["react", createReactEmitter({ stackImportRelative: "../../primitives" })],
    ["vue", createVueEmitter()],
    ["svelte", createSvelteEmitter()],
    ["angular", createAngularEmitter()],
    ["lit", createLitEmitter()],
  ] as const;

  for (const [name, emitter] of emitters) {
    it(`${name} lowers the token-driven gap and marks output generated`, () => {
      const files = emitter.emitPrimitives?.(ir, opts) ?? [];
      expect(files.length).toBeGreaterThan(0);
      const joined = files.map((f) => f.contents).join("\n");
      // The gap must read the semantic token var, never a hard-coded value.
      expect(joined).toContain(`var(${GAP_VAR})`);
      // Every emitted primitive file carries the generated banner so it is
      // not mistaken for hand-authored source.
      for (const file of files) {
        expect(file.contents).toMatch(/@generated by ds-codegen/);
      }
    });

    it(`${name} preserves the layout class/attribute facts from the IR`, () => {
      const files = emitter.emitPrimitives?.(ir, opts) ?? [];
      const joined = files.map((f) => f.contents).join("\n");
      // flex-direction values come from axisByVariant; assert the axis
      // semantics survived the lowering (column/row) in every framework.
      expect(joined).toContain("column");
      expect(joined).toContain("row");
    });
  }
});
