// @generated:start imports
import { LitElement, html, css, nothing } from 'lit';
import { property } from 'lit/decorators.js';
import { ifDefined } from 'lit/directives/if-defined.js';
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type PostcardAuthor = { name: string; handle: string; avatar: string };
export type PostcardStats = { likes: number; replies: number; reposts: number };
export type PostcardEmbed = { type: 'image' | 'video' | 'audio'; url: string; aspectRatio: { width: number; height: number } };
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
export class PostcardElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .postcard {
      --fsds-postcard-color-background-default: var(--fsds-semantic-color-background-primary, #ffffff);
      --fsds-postcard-color-background-hover: var(--fsds-semantic-color-background-secondary, #f7f7f7);
      --fsds-postcard-color-border-default: var(--fsds-semantic-color-border-light, #b8b8b8);
      --fsds-postcard-color-border-hover: var(--fsds-semantic-color-border-bold, #888889);
      --fsds-postcard-color-foreground-primary: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-postcard-size-padding-default: var(--fsds-core-spacing-size-06, 16px);
      --fsds-postcard-size-radius-default: var(--fsds-semantic-shape-control-radius-default, 6px);
      --fsds-postcard-size-gap-default: var(--fsds-core-spacing-size-05, 12px);
      --fsds-postcard-size-border-default: var(--fsds-semantic-shape-control-border-default-width, 1px);
      --fsds-postcard-typography-display-name-font-size: var(--fsds-semantic-typography-body-02, 16px);
      --fsds-postcard-typography-display-name-font-weight: var(--fsds-semantic-typography-font-weight-medium, 500);
      --fsds-postcard-typography-handle-font-size: var(--fsds-semantic-typography-body-03, 14px);
      --fsds-postcard-typography-content-font-size: var(--fsds-semantic-typography-body-02, 16px);
      --fsds-postcard-typography-content-line-height: var(--fsds-semantic-typography-line-height-body, 1.5);
      --fsds-postcard-typography-footer-font-size: var(--fsds-semantic-typography-body-03, 14px);
    }

    .postcard__userInfo {
      --fsds-postcard-size-gap-default: var(--fsds-core-spacing-size-03, 4px);
    }

    .postcard__handle {
      --fsds-postcard-color-foreground-primary: var(--fsds-semantic-color-foreground-secondary, #474647);
    }

    .postcard__timestamp {
      --fsds-postcard-color-foreground-primary: var(--fsds-semantic-color-foreground-secondary, #474647);
    }

    .postcard__stat {
      --fsds-postcard-size-gap-default: var(--fsds-core-spacing-size-03, 4px);
      --fsds-postcard-color-foreground-primary: var(--fsds-semantic-color-foreground-secondary, #474647);
    }

    @layer components.defaults {
    .postcard {
      padding-block-start: var(--fsds-box-model-padding-block-start, var(--fsds-semantic-surface-size-padding-block, 16px));
      padding-block-end: var(--fsds-box-model-padding-block-end, var(--fsds-semantic-surface-size-padding-block, 16px));
      padding-inline-start: var(--fsds-box-model-padding-inline-start, var(--fsds-semantic-surface-size-padding-inline, 16px));
      padding-inline-end: var(--fsds-box-model-padding-inline-end, var(--fsds-semantic-surface-size-padding-inline, 16px));
      gap: var(--fsds-postcard-design-root-spacing-gap, var(--fsds-postcard-size-gap-default, 12px));
      width: var(--fsds-box-model-width, auto);
      min-width: var(--fsds-box-model-min-width, var(--fsds-semantic-surface-size-min-width, 64px));
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, 0);
      max-height: var(--fsds-box-model-max-height, none);
      background-color: var(--fsds-postcard-design-root-background-fill, var(--fsds-postcard-color-background-default, #ffffff));
      padding: var(--fsds-postcard-design-root-spacing-padding, var(--fsds-postcard-size-padding-default, 16px));
      border-radius: var(--fsds-postcard-design-root-shape-radius, var(--fsds-postcard-size-radius-default, 6px));
      line-height: var(--fsds-postcard-design-root-typography-line-height, var(--fsds-postcard-typography-content-line-height, 1.5));
      display: flex;
      flex-direction: column;
      border-style: var(--fsds-postcard-design-root-border-style, solid);
      border-width: var(--fsds-postcard-design-root-border-width, var(--fsds-postcard-size-border-default, 1px));
      box-sizing: border-box;
      border-color: var(--fsds-postcard-design-root-border-color, var(--fsds-postcard-color-border-default, #b8b8b8));
      color: var(--fsds-postcard-design-root-foreground-color, var(--fsds-postcard-color-foreground-primary, #141414));

      &:hover {
        background-color: var(--fsds-postcard-design-hover-background-fill, var(--fsds-postcard-color-background-hover, #f7f7f7));
        border-color: var(--fsds-postcard-design-hover-border-color, var(--fsds-postcard-color-border-hover, #888889));
      }
    }

    .postcard__content {
      line-height: var(--fsds-postcard-design-content-typography-line-height, var(--fsds-postcard-typography-content-line-height, 1.5));
      display: flex;
      flex-direction: column;
      gap: var(--fsds-postcard-design-content-spacing-gap, var(--fsds-postcard-size-gap-default, 12px));
      color: var(--fsds-postcard-design-content-foreground-color, var(--fsds-postcard-color-foreground-primary, #141414));
      font-size: var(--fsds-postcard-design-content-typography-size, var(--fsds-postcard-typography-content-font-size, 16px));
    }

    .postcard__header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: var(--fsds-postcard-design-header-spacing-gap, var(--fsds-postcard-size-gap-default, 12px));
    }

    .postcard__userInfo {
      display: flex;
      align-items: center;
      flex: 1 1 auto;
    }

    .postcard__displayName {
      font-weight: var(--fsds-postcard-design-display-name-typography-weight, var(--fsds-postcard-typography-display-name-font-weight, 500));
      font-size: var(--fsds-postcard-design-display-name-typography-size, var(--fsds-postcard-typography-display-name-font-size, 16px));
      color: var(--fsds-postcard-design-display-name-foreground-color, var(--fsds-postcard-color-foreground-primary, #141414));
    }

    .postcard__handle {
      font-size: var(--fsds-postcard-design-handle-typography-size, var(--fsds-postcard-typography-handle-font-size, 14px));
    }

    .postcard__timestamp {
      font-size: var(--fsds-postcard-design-timestamp-typography-size, var(--fsds-postcard-typography-footer-font-size, 14px));
      flex-shrink: 0;
    }

    .postcard__footer {
      display: flex;
      align-items: center;
      gap: var(--fsds-postcard-design-footer-spacing-gap, var(--fsds-postcard-size-gap-default, 12px));
      padding-top: var(--fsds-postcard-size-padding-default, 16px);
      border-top-color: var(--fsds-postcard-design-footer-border-top-color, var(--fsds-postcard-color-border-default, #b8b8b8));
      border-top-style: var(--fsds-postcard-design-footer-border-top-style, solid);
      border-top-width: var(--fsds-postcard-design-footer-border-top-width, var(--fsds-postcard-size-border-default, 1px));
      font-size: var(--fsds-postcard-design-footer-typography-size, var(--fsds-postcard-typography-footer-font-size, 14px));
    }

    .postcard__stats {
      display: flex;
      align-items: center;
      gap: var(--fsds-postcard-design-stats-spacing-gap, var(--fsds-postcard-size-gap-default, 12px));
    }

    .postcard__stat {
      display: inline-flex;
      align-items: center;
      font-size: var(--fsds-postcard-design-stat-typography-size, var(--fsds-postcard-typography-footer-font-size, 14px));
    }
    }
  `;

  @property({ type: String }) postId!: string;
  @property({ attribute: false }) author!: PostcardAuthor;
  @property({ type: String }) timestamp!: string;
  @property({ attribute: false }) stats!: PostcardStats;
  @property({ attribute: false }) embed?: PostcardEmbed;
  @property() type?: string;

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute("data-fsds-component", "postcard");
  }

  private computeClasses(): string {
    return [
      "postcard",
      this.type ? `postcard--${this.type}` : null,
    ].filter(Boolean).join(" ");
  }

  override render() {
    return html`<article class="${this.computeClasses()}" data-fsds-box="">
  <div class=${'postcard__header'}>
    <div class=${'postcard__userInfo'}>
      <span class=${'postcard__displayName'}>${this.author.name}</span>
      <span class=${'postcard__handle'}>${this.author.handle}</span>
    </div>
    <time class=${'postcard__timestamp'} datetime=${ifDefined(this.timestamp)}>${this.timestamp}</time>
  </div>
  <div class=${'postcard__content'}>
    <slot></slot>
  </div>
  <div class=${'postcard__footer'}>
    <div class=${'postcard__stats'}>
      <span class=${'postcard__stat'}>${this.stats.likes}</span>
    </div>
  </div>
</article>`;
  }
}

customElements.define('fsds-postcard', PostcardElement);


export class PostcardHeaderElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .postcard {
      --fsds-postcard-color-background-default: var(--fsds-semantic-color-background-primary, #ffffff);
      --fsds-postcard-color-background-hover: var(--fsds-semantic-color-background-secondary, #f7f7f7);
      --fsds-postcard-color-border-default: var(--fsds-semantic-color-border-light, #b8b8b8);
      --fsds-postcard-color-border-hover: var(--fsds-semantic-color-border-bold, #888889);
      --fsds-postcard-color-foreground-primary: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-postcard-size-padding-default: var(--fsds-core-spacing-size-06, 16px);
      --fsds-postcard-size-radius-default: var(--fsds-semantic-shape-control-radius-default, 6px);
      --fsds-postcard-size-gap-default: var(--fsds-core-spacing-size-05, 12px);
      --fsds-postcard-size-border-default: var(--fsds-semantic-shape-control-border-default-width, 1px);
      --fsds-postcard-typography-display-name-font-size: var(--fsds-semantic-typography-body-02, 16px);
      --fsds-postcard-typography-display-name-font-weight: var(--fsds-semantic-typography-font-weight-medium, 500);
      --fsds-postcard-typography-handle-font-size: var(--fsds-semantic-typography-body-03, 14px);
      --fsds-postcard-typography-content-font-size: var(--fsds-semantic-typography-body-02, 16px);
      --fsds-postcard-typography-content-line-height: var(--fsds-semantic-typography-line-height-body, 1.5);
      --fsds-postcard-typography-footer-font-size: var(--fsds-semantic-typography-body-03, 14px);
    }

    .postcard__userInfo {
      --fsds-postcard-size-gap-default: var(--fsds-core-spacing-size-03, 4px);
    }

    .postcard__handle {
      --fsds-postcard-color-foreground-primary: var(--fsds-semantic-color-foreground-secondary, #474647);
    }

    .postcard__timestamp {
      --fsds-postcard-color-foreground-primary: var(--fsds-semantic-color-foreground-secondary, #474647);
    }

    .postcard__stat {
      --fsds-postcard-size-gap-default: var(--fsds-core-spacing-size-03, 4px);
      --fsds-postcard-color-foreground-primary: var(--fsds-semantic-color-foreground-secondary, #474647);
    }

    @layer components.defaults {
    .postcard {
      padding-block-start: var(--fsds-box-model-padding-block-start, var(--fsds-semantic-surface-size-padding-block, 16px));
      padding-block-end: var(--fsds-box-model-padding-block-end, var(--fsds-semantic-surface-size-padding-block, 16px));
      padding-inline-start: var(--fsds-box-model-padding-inline-start, var(--fsds-semantic-surface-size-padding-inline, 16px));
      padding-inline-end: var(--fsds-box-model-padding-inline-end, var(--fsds-semantic-surface-size-padding-inline, 16px));
      gap: var(--fsds-postcard-design-root-spacing-gap, var(--fsds-postcard-size-gap-default, 12px));
      width: var(--fsds-box-model-width, auto);
      min-width: var(--fsds-box-model-min-width, var(--fsds-semantic-surface-size-min-width, 64px));
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, 0);
      max-height: var(--fsds-box-model-max-height, none);
      background-color: var(--fsds-postcard-design-root-background-fill, var(--fsds-postcard-color-background-default, #ffffff));
      padding: var(--fsds-postcard-design-root-spacing-padding, var(--fsds-postcard-size-padding-default, 16px));
      border-radius: var(--fsds-postcard-design-root-shape-radius, var(--fsds-postcard-size-radius-default, 6px));
      line-height: var(--fsds-postcard-design-root-typography-line-height, var(--fsds-postcard-typography-content-line-height, 1.5));
      display: flex;
      flex-direction: column;
      border-style: var(--fsds-postcard-design-root-border-style, solid);
      border-width: var(--fsds-postcard-design-root-border-width, var(--fsds-postcard-size-border-default, 1px));
      box-sizing: border-box;
      border-color: var(--fsds-postcard-design-root-border-color, var(--fsds-postcard-color-border-default, #b8b8b8));
      color: var(--fsds-postcard-design-root-foreground-color, var(--fsds-postcard-color-foreground-primary, #141414));

      &:hover {
        background-color: var(--fsds-postcard-design-hover-background-fill, var(--fsds-postcard-color-background-hover, #f7f7f7));
        border-color: var(--fsds-postcard-design-hover-border-color, var(--fsds-postcard-color-border-hover, #888889));
      }
    }

    .postcard__content {
      line-height: var(--fsds-postcard-design-content-typography-line-height, var(--fsds-postcard-typography-content-line-height, 1.5));
      display: flex;
      flex-direction: column;
      gap: var(--fsds-postcard-design-content-spacing-gap, var(--fsds-postcard-size-gap-default, 12px));
      color: var(--fsds-postcard-design-content-foreground-color, var(--fsds-postcard-color-foreground-primary, #141414));
      font-size: var(--fsds-postcard-design-content-typography-size, var(--fsds-postcard-typography-content-font-size, 16px));
    }

    .postcard__header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: var(--fsds-postcard-design-header-spacing-gap, var(--fsds-postcard-size-gap-default, 12px));
    }

    .postcard__userInfo {
      display: flex;
      align-items: center;
      flex: 1 1 auto;
    }

    .postcard__displayName {
      font-weight: var(--fsds-postcard-design-display-name-typography-weight, var(--fsds-postcard-typography-display-name-font-weight, 500));
      font-size: var(--fsds-postcard-design-display-name-typography-size, var(--fsds-postcard-typography-display-name-font-size, 16px));
      color: var(--fsds-postcard-design-display-name-foreground-color, var(--fsds-postcard-color-foreground-primary, #141414));
    }

    .postcard__handle {
      font-size: var(--fsds-postcard-design-handle-typography-size, var(--fsds-postcard-typography-handle-font-size, 14px));
    }

    .postcard__timestamp {
      font-size: var(--fsds-postcard-design-timestamp-typography-size, var(--fsds-postcard-typography-footer-font-size, 14px));
      flex-shrink: 0;
    }

    .postcard__footer {
      display: flex;
      align-items: center;
      gap: var(--fsds-postcard-design-footer-spacing-gap, var(--fsds-postcard-size-gap-default, 12px));
      padding-top: var(--fsds-postcard-size-padding-default, 16px);
      border-top-color: var(--fsds-postcard-design-footer-border-top-color, var(--fsds-postcard-color-border-default, #b8b8b8));
      border-top-style: var(--fsds-postcard-design-footer-border-top-style, solid);
      border-top-width: var(--fsds-postcard-design-footer-border-top-width, var(--fsds-postcard-size-border-default, 1px));
      font-size: var(--fsds-postcard-design-footer-typography-size, var(--fsds-postcard-typography-footer-font-size, 14px));
    }

    .postcard__stats {
      display: flex;
      align-items: center;
      gap: var(--fsds-postcard-design-stats-spacing-gap, var(--fsds-postcard-size-gap-default, 12px));
    }

    .postcard__stat {
      display: inline-flex;
      align-items: center;
      font-size: var(--fsds-postcard-design-stat-typography-size, var(--fsds-postcard-typography-footer-font-size, 14px));
    }
    }
  `;

  override render() {
    return html`<fsds-stack class="postcard__header"><slot></slot></fsds-stack>`;
  }
}

customElements.define('fsds-postcard-header', PostcardHeaderElement);

export class PostcardContentElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .postcard {
      --fsds-postcard-color-background-default: var(--fsds-semantic-color-background-primary, #ffffff);
      --fsds-postcard-color-background-hover: var(--fsds-semantic-color-background-secondary, #f7f7f7);
      --fsds-postcard-color-border-default: var(--fsds-semantic-color-border-light, #b8b8b8);
      --fsds-postcard-color-border-hover: var(--fsds-semantic-color-border-bold, #888889);
      --fsds-postcard-color-foreground-primary: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-postcard-size-padding-default: var(--fsds-core-spacing-size-06, 16px);
      --fsds-postcard-size-radius-default: var(--fsds-semantic-shape-control-radius-default, 6px);
      --fsds-postcard-size-gap-default: var(--fsds-core-spacing-size-05, 12px);
      --fsds-postcard-size-border-default: var(--fsds-semantic-shape-control-border-default-width, 1px);
      --fsds-postcard-typography-display-name-font-size: var(--fsds-semantic-typography-body-02, 16px);
      --fsds-postcard-typography-display-name-font-weight: var(--fsds-semantic-typography-font-weight-medium, 500);
      --fsds-postcard-typography-handle-font-size: var(--fsds-semantic-typography-body-03, 14px);
      --fsds-postcard-typography-content-font-size: var(--fsds-semantic-typography-body-02, 16px);
      --fsds-postcard-typography-content-line-height: var(--fsds-semantic-typography-line-height-body, 1.5);
      --fsds-postcard-typography-footer-font-size: var(--fsds-semantic-typography-body-03, 14px);
    }

    .postcard__userInfo {
      --fsds-postcard-size-gap-default: var(--fsds-core-spacing-size-03, 4px);
    }

    .postcard__handle {
      --fsds-postcard-color-foreground-primary: var(--fsds-semantic-color-foreground-secondary, #474647);
    }

    .postcard__timestamp {
      --fsds-postcard-color-foreground-primary: var(--fsds-semantic-color-foreground-secondary, #474647);
    }

    .postcard__stat {
      --fsds-postcard-size-gap-default: var(--fsds-core-spacing-size-03, 4px);
      --fsds-postcard-color-foreground-primary: var(--fsds-semantic-color-foreground-secondary, #474647);
    }

    @layer components.defaults {
    .postcard {
      padding-block-start: var(--fsds-box-model-padding-block-start, var(--fsds-semantic-surface-size-padding-block, 16px));
      padding-block-end: var(--fsds-box-model-padding-block-end, var(--fsds-semantic-surface-size-padding-block, 16px));
      padding-inline-start: var(--fsds-box-model-padding-inline-start, var(--fsds-semantic-surface-size-padding-inline, 16px));
      padding-inline-end: var(--fsds-box-model-padding-inline-end, var(--fsds-semantic-surface-size-padding-inline, 16px));
      gap: var(--fsds-postcard-design-root-spacing-gap, var(--fsds-postcard-size-gap-default, 12px));
      width: var(--fsds-box-model-width, auto);
      min-width: var(--fsds-box-model-min-width, var(--fsds-semantic-surface-size-min-width, 64px));
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, 0);
      max-height: var(--fsds-box-model-max-height, none);
      background-color: var(--fsds-postcard-design-root-background-fill, var(--fsds-postcard-color-background-default, #ffffff));
      padding: var(--fsds-postcard-design-root-spacing-padding, var(--fsds-postcard-size-padding-default, 16px));
      border-radius: var(--fsds-postcard-design-root-shape-radius, var(--fsds-postcard-size-radius-default, 6px));
      line-height: var(--fsds-postcard-design-root-typography-line-height, var(--fsds-postcard-typography-content-line-height, 1.5));
      display: flex;
      flex-direction: column;
      border-style: var(--fsds-postcard-design-root-border-style, solid);
      border-width: var(--fsds-postcard-design-root-border-width, var(--fsds-postcard-size-border-default, 1px));
      box-sizing: border-box;
      border-color: var(--fsds-postcard-design-root-border-color, var(--fsds-postcard-color-border-default, #b8b8b8));
      color: var(--fsds-postcard-design-root-foreground-color, var(--fsds-postcard-color-foreground-primary, #141414));

      &:hover {
        background-color: var(--fsds-postcard-design-hover-background-fill, var(--fsds-postcard-color-background-hover, #f7f7f7));
        border-color: var(--fsds-postcard-design-hover-border-color, var(--fsds-postcard-color-border-hover, #888889));
      }
    }

    .postcard__content {
      line-height: var(--fsds-postcard-design-content-typography-line-height, var(--fsds-postcard-typography-content-line-height, 1.5));
      display: flex;
      flex-direction: column;
      gap: var(--fsds-postcard-design-content-spacing-gap, var(--fsds-postcard-size-gap-default, 12px));
      color: var(--fsds-postcard-design-content-foreground-color, var(--fsds-postcard-color-foreground-primary, #141414));
      font-size: var(--fsds-postcard-design-content-typography-size, var(--fsds-postcard-typography-content-font-size, 16px));
    }

    .postcard__header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: var(--fsds-postcard-design-header-spacing-gap, var(--fsds-postcard-size-gap-default, 12px));
    }

    .postcard__userInfo {
      display: flex;
      align-items: center;
      flex: 1 1 auto;
    }

    .postcard__displayName {
      font-weight: var(--fsds-postcard-design-display-name-typography-weight, var(--fsds-postcard-typography-display-name-font-weight, 500));
      font-size: var(--fsds-postcard-design-display-name-typography-size, var(--fsds-postcard-typography-display-name-font-size, 16px));
      color: var(--fsds-postcard-design-display-name-foreground-color, var(--fsds-postcard-color-foreground-primary, #141414));
    }

    .postcard__handle {
      font-size: var(--fsds-postcard-design-handle-typography-size, var(--fsds-postcard-typography-handle-font-size, 14px));
    }

    .postcard__timestamp {
      font-size: var(--fsds-postcard-design-timestamp-typography-size, var(--fsds-postcard-typography-footer-font-size, 14px));
      flex-shrink: 0;
    }

    .postcard__footer {
      display: flex;
      align-items: center;
      gap: var(--fsds-postcard-design-footer-spacing-gap, var(--fsds-postcard-size-gap-default, 12px));
      padding-top: var(--fsds-postcard-size-padding-default, 16px);
      border-top-color: var(--fsds-postcard-design-footer-border-top-color, var(--fsds-postcard-color-border-default, #b8b8b8));
      border-top-style: var(--fsds-postcard-design-footer-border-top-style, solid);
      border-top-width: var(--fsds-postcard-design-footer-border-top-width, var(--fsds-postcard-size-border-default, 1px));
      font-size: var(--fsds-postcard-design-footer-typography-size, var(--fsds-postcard-typography-footer-font-size, 14px));
    }

    .postcard__stats {
      display: flex;
      align-items: center;
      gap: var(--fsds-postcard-design-stats-spacing-gap, var(--fsds-postcard-size-gap-default, 12px));
    }

    .postcard__stat {
      display: inline-flex;
      align-items: center;
      font-size: var(--fsds-postcard-design-stat-typography-size, var(--fsds-postcard-typography-footer-font-size, 14px));
    }
    }
  `;

  override render() {
    return html`<fsds-stack class="postcard__content"><slot></slot></fsds-stack>`;
  }
}

customElements.define('fsds-postcard-content', PostcardContentElement);

export class PostcardFooterElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .postcard {
      --fsds-postcard-color-background-default: var(--fsds-semantic-color-background-primary, #ffffff);
      --fsds-postcard-color-background-hover: var(--fsds-semantic-color-background-secondary, #f7f7f7);
      --fsds-postcard-color-border-default: var(--fsds-semantic-color-border-light, #b8b8b8);
      --fsds-postcard-color-border-hover: var(--fsds-semantic-color-border-bold, #888889);
      --fsds-postcard-color-foreground-primary: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-postcard-size-padding-default: var(--fsds-core-spacing-size-06, 16px);
      --fsds-postcard-size-radius-default: var(--fsds-semantic-shape-control-radius-default, 6px);
      --fsds-postcard-size-gap-default: var(--fsds-core-spacing-size-05, 12px);
      --fsds-postcard-size-border-default: var(--fsds-semantic-shape-control-border-default-width, 1px);
      --fsds-postcard-typography-display-name-font-size: var(--fsds-semantic-typography-body-02, 16px);
      --fsds-postcard-typography-display-name-font-weight: var(--fsds-semantic-typography-font-weight-medium, 500);
      --fsds-postcard-typography-handle-font-size: var(--fsds-semantic-typography-body-03, 14px);
      --fsds-postcard-typography-content-font-size: var(--fsds-semantic-typography-body-02, 16px);
      --fsds-postcard-typography-content-line-height: var(--fsds-semantic-typography-line-height-body, 1.5);
      --fsds-postcard-typography-footer-font-size: var(--fsds-semantic-typography-body-03, 14px);
    }

    .postcard__userInfo {
      --fsds-postcard-size-gap-default: var(--fsds-core-spacing-size-03, 4px);
    }

    .postcard__handle {
      --fsds-postcard-color-foreground-primary: var(--fsds-semantic-color-foreground-secondary, #474647);
    }

    .postcard__timestamp {
      --fsds-postcard-color-foreground-primary: var(--fsds-semantic-color-foreground-secondary, #474647);
    }

    .postcard__stat {
      --fsds-postcard-size-gap-default: var(--fsds-core-spacing-size-03, 4px);
      --fsds-postcard-color-foreground-primary: var(--fsds-semantic-color-foreground-secondary, #474647);
    }

    @layer components.defaults {
    .postcard {
      padding-block-start: var(--fsds-box-model-padding-block-start, var(--fsds-semantic-surface-size-padding-block, 16px));
      padding-block-end: var(--fsds-box-model-padding-block-end, var(--fsds-semantic-surface-size-padding-block, 16px));
      padding-inline-start: var(--fsds-box-model-padding-inline-start, var(--fsds-semantic-surface-size-padding-inline, 16px));
      padding-inline-end: var(--fsds-box-model-padding-inline-end, var(--fsds-semantic-surface-size-padding-inline, 16px));
      gap: var(--fsds-postcard-design-root-spacing-gap, var(--fsds-postcard-size-gap-default, 12px));
      width: var(--fsds-box-model-width, auto);
      min-width: var(--fsds-box-model-min-width, var(--fsds-semantic-surface-size-min-width, 64px));
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, 0);
      max-height: var(--fsds-box-model-max-height, none);
      background-color: var(--fsds-postcard-design-root-background-fill, var(--fsds-postcard-color-background-default, #ffffff));
      padding: var(--fsds-postcard-design-root-spacing-padding, var(--fsds-postcard-size-padding-default, 16px));
      border-radius: var(--fsds-postcard-design-root-shape-radius, var(--fsds-postcard-size-radius-default, 6px));
      line-height: var(--fsds-postcard-design-root-typography-line-height, var(--fsds-postcard-typography-content-line-height, 1.5));
      display: flex;
      flex-direction: column;
      border-style: var(--fsds-postcard-design-root-border-style, solid);
      border-width: var(--fsds-postcard-design-root-border-width, var(--fsds-postcard-size-border-default, 1px));
      box-sizing: border-box;
      border-color: var(--fsds-postcard-design-root-border-color, var(--fsds-postcard-color-border-default, #b8b8b8));
      color: var(--fsds-postcard-design-root-foreground-color, var(--fsds-postcard-color-foreground-primary, #141414));

      &:hover {
        background-color: var(--fsds-postcard-design-hover-background-fill, var(--fsds-postcard-color-background-hover, #f7f7f7));
        border-color: var(--fsds-postcard-design-hover-border-color, var(--fsds-postcard-color-border-hover, #888889));
      }
    }

    .postcard__content {
      line-height: var(--fsds-postcard-design-content-typography-line-height, var(--fsds-postcard-typography-content-line-height, 1.5));
      display: flex;
      flex-direction: column;
      gap: var(--fsds-postcard-design-content-spacing-gap, var(--fsds-postcard-size-gap-default, 12px));
      color: var(--fsds-postcard-design-content-foreground-color, var(--fsds-postcard-color-foreground-primary, #141414));
      font-size: var(--fsds-postcard-design-content-typography-size, var(--fsds-postcard-typography-content-font-size, 16px));
    }

    .postcard__header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: var(--fsds-postcard-design-header-spacing-gap, var(--fsds-postcard-size-gap-default, 12px));
    }

    .postcard__userInfo {
      display: flex;
      align-items: center;
      flex: 1 1 auto;
    }

    .postcard__displayName {
      font-weight: var(--fsds-postcard-design-display-name-typography-weight, var(--fsds-postcard-typography-display-name-font-weight, 500));
      font-size: var(--fsds-postcard-design-display-name-typography-size, var(--fsds-postcard-typography-display-name-font-size, 16px));
      color: var(--fsds-postcard-design-display-name-foreground-color, var(--fsds-postcard-color-foreground-primary, #141414));
    }

    .postcard__handle {
      font-size: var(--fsds-postcard-design-handle-typography-size, var(--fsds-postcard-typography-handle-font-size, 14px));
    }

    .postcard__timestamp {
      font-size: var(--fsds-postcard-design-timestamp-typography-size, var(--fsds-postcard-typography-footer-font-size, 14px));
      flex-shrink: 0;
    }

    .postcard__footer {
      display: flex;
      align-items: center;
      gap: var(--fsds-postcard-design-footer-spacing-gap, var(--fsds-postcard-size-gap-default, 12px));
      padding-top: var(--fsds-postcard-size-padding-default, 16px);
      border-top-color: var(--fsds-postcard-design-footer-border-top-color, var(--fsds-postcard-color-border-default, #b8b8b8));
      border-top-style: var(--fsds-postcard-design-footer-border-top-style, solid);
      border-top-width: var(--fsds-postcard-design-footer-border-top-width, var(--fsds-postcard-size-border-default, 1px));
      font-size: var(--fsds-postcard-design-footer-typography-size, var(--fsds-postcard-typography-footer-font-size, 14px));
    }

    .postcard__stats {
      display: flex;
      align-items: center;
      gap: var(--fsds-postcard-design-stats-spacing-gap, var(--fsds-postcard-size-gap-default, 12px));
    }

    .postcard__stat {
      display: inline-flex;
      align-items: center;
      font-size: var(--fsds-postcard-design-stat-typography-size, var(--fsds-postcard-typography-footer-font-size, 14px));
    }
    }
  `;

  override render() {
    return html`<fsds-stack variant="horizontal" class="postcard__footer"><slot></slot></fsds-stack>`;
  }
}

customElements.define('fsds-postcard-footer', PostcardFooterElement);
// @generated:end

// @custom:start trailing

// @custom:end