// @generated:start imports
import { LitElement, html, css, nothing } from 'lit';
import { property } from 'lit/decorators.js';
import { parseMarkdown, type MarkdownBlock, type MarkdownMark } from '../../primitives/markdown/markdown.js';
import { type TemplateResult } from 'lit';
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
export class MarkdownElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-component]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-component]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-component]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .markdown {
      --fsds-markdown-color-foreground-default: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-markdown-typography-font-size-default: var(--fsds-core-typography-ramp-3, 0.875rem);
      --fsds-markdown-typography-line-height-default: var(--fsds-semantic-typography-line-height-body, 1.5);
    }

    @layer components.defaults {
    .markdown {
      padding-block-start: var(--fsds-box-model-padding-block-start, 0);
      padding-block-end: var(--fsds-box-model-padding-block-end, 0);
      padding-inline-start: var(--fsds-box-model-padding-inline-start, 0);
      padding-inline-end: var(--fsds-box-model-padding-inline-end, 0);
      gap: var(--fsds-box-model-gap, 0);
      width: var(--fsds-box-model-width, auto);
      min-width: var(--fsds-box-model-min-width, 0);
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, 0);
      max-height: var(--fsds-box-model-max-height, none);
      color: var(--fsds-markdown-design-root-foreground-color, var(--fsds-markdown-color-foreground-default, #141414));
      font-size: var(--fsds-markdown-design-root-typography-size, var(--fsds-markdown-typography-font-size-default, 0.875rem));
      line-height: var(--fsds-markdown-design-root-typography-line-height, var(--fsds-markdown-typography-line-height-default, 1.5));
    }

    .markdown__codeBlock {
      white-space: pre;
    }
    }
  `;

  @property({ type: String }) content!: string;

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute("data-fsds-component", "markdown");
  }

  private computeClasses(): string {
    return [
      "markdown",
    ].filter(Boolean).join(" ");
  }

  override render() {
    return html`<div class="${this.computeClasses()}">${renderMarkdownBlocks(this.content)}</div>`;
  }
}

customElements.define('fsds-markdown', MarkdownElement);

function renderMarkdownBlocks(source: string): TemplateResult[] {
  return parseMarkdown(source ?? "").map((block, blockIndex) =>
    renderMarkdownBlock(block, blockIndex),
  );
}

function renderMarkdownBlock(block: MarkdownBlock, key: number): TemplateResult {
  switch (block.kind) {
    case "heading":
      return html`<h2 class="markdown__heading" data-block-kind="heading" data-block-kind-level=${block.level}>${block.children.map((mark, markIndex) => renderMarkdownMark(mark, markIndex))}</h2>`;
    case "paragraph":
      return html`<p class="markdown__paragraph" data-block-kind="paragraph">${block.children.map((mark, markIndex) => renderMarkdownMark(mark, markIndex))}</p>`;
    case "list":
      return block.ordered
        ? html`<ol class="markdown__orderedList" data-block-kind="orderedList">${block.items.map((item, itemIndex) => renderMarkdownBlock(item, itemIndex))}</ol>`
        : html`<ul class="markdown__unorderedList" data-block-kind="unorderedList">${block.items.map((item, itemIndex) => renderMarkdownBlock(item, itemIndex))}</ul>`;
    case "listItem":
      return html`<li class="markdown__listItem" data-block-kind="listItem">${block.children.map((mark, markIndex) => renderMarkdownMark(mark, markIndex))}</li>`;
    case "codeBlock":
      return html`<pre class="markdown__codeBlock" data-block-kind="codeBlock" data-language=${block.language}>${block.text}</pre>`;
    case "blockquote":
      return html`<blockquote class="markdown__blockquote" data-block-kind="blockquote">${block.children.map((mark, markIndex) => renderMarkdownMark(mark, markIndex))}</blockquote>`;
  }
}

function renderMarkdownMark(mark: MarkdownMark, key: number): TemplateResult {
  switch (mark.kind) {
    case "text":
      return html`${mark.text}`;
    case "code":
      return html`<code class="markdown__code" data-mark-kind="code">${mark.text}</code>`;
    case "emphasis":
      return html`<em class="markdown__emphasis" data-mark-kind="emphasis">${mark.children.map((child, childIndex) => renderMarkdownMark(child, childIndex))}</em>`;
    case "strong":
      return html`<strong class="markdown__strong" data-mark-kind="strong">${mark.children.map((child, childIndex) => renderMarkdownMark(child, childIndex))}</strong>`;
    case "link":
      return mark.href === null
        ? html`${mark.children.map((child, childIndex) => renderMarkdownMark(child, childIndex))}`
        : html`<a class="markdown__link" data-mark-kind="link" href=${mark.href}>${mark.children.map((child, childIndex) => renderMarkdownMark(child, childIndex))}</a>`;
  }
}

// @generated:end

// @custom:start trailing

// @custom:end