// @generated:start imports
import { LitElement, html, css, nothing } from 'lit';
import { property } from 'lit/decorators.js';
import { OTPBehavior } from './OTPBehavior.js';
import { ifDefined } from 'lit/directives/if-defined.js';
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type OTPMode = "numeric" | "alphanumeric";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
export class OTPElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .otp {
      --fsds-otp-color-background-default: var(--fsds-semantic-color-background-secondary, #f7f7f7);
      --fsds-otp-color-foreground-primary: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-otp-color-border-default: var(--fsds-semantic-color-border-light, #b8b8b8);
      --fsds-otp-size-radius-default: var(--fsds-semantic-shape-control-radius-default, 6px);
      --fsds-otp-color-border-accent: var(--fsds-semantic-color-border-accent, #d92d2e);
      --fsds-otp-focus-ring-width: var(--fsds-semantic-focus-ring-width, 2px);
      --fsds-otp-focus-ring-color: var(--fsds-semantic-focus-ring-color, #0566fe);
      --fsds-otp-focus-ring-style: var(--fsds-semantic-focus-ring-style, solid);
      --fsds-otp-focus-ring-offset: var(--fsds-semantic-focus-ring-offset, 2px);
    }

    @layer components.defaults {
    .otp {
      padding-block-start: var(--fsds-box-model-padding-block-start, var(--fsds-semantic-input-size-medium-padding-block, 4px));
      padding-block-end: var(--fsds-box-model-padding-block-end, var(--fsds-semantic-input-size-medium-padding-block, 4px));
      padding-inline-start: var(--fsds-box-model-padding-inline-start, var(--fsds-semantic-input-size-medium-padding-inline, 8px));
      padding-inline-end: var(--fsds-box-model-padding-inline-end, var(--fsds-semantic-input-size-medium-padding-inline, 8px));
      gap: var(--fsds-box-model-gap, var(--fsds-semantic-input-size-medium-gap, 8px));
      width: var(--fsds-box-model-width, auto);
      min-width: var(--fsds-box-model-min-width, 0);
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, var(--fsds-semantic-input-size-medium-min-height, 32px));
      max-height: var(--fsds-box-model-max-height, none);
      display: inline-flex;
      align-items: center;
    }

    .otp__group {
      display: inline-flex;
      align-items: center;
      gap: var(--fsds-otp-design-group-spacing-gap, 4px);
    }

    .otp__field {
      display: block;
      width: 40px;
      height: 40px;
      text-align: var(--fsds-otp-design-field-typography-alignment, center);
      font-size: var(--fsds-otp-design-field-typography-size, 1rem);
      box-sizing: border-box;
      border-style: var(--fsds-otp-design-field-border-style, solid);
      border-width: var(--fsds-otp-design-field-border-width, 1px);
      border-radius: var(--fsds-otp-design-field-shape-radius, var(--fsds-otp-size-radius-default, 6px));
      border-color: var(--fsds-otp-design-field-border-color, var(--fsds-otp-color-border-default, #b8b8b8));
      background-color: var(--fsds-otp-design-field-background-fill, var(--fsds-otp-color-background-default, #f7f7f7));
      color: var(--fsds-otp-design-field-foreground-color, var(--fsds-otp-color-foreground-primary, #141414));
    }

    .otp__field:focus-visible:not([aria-disabled="true"]) {
      border-color: var(--fsds-otp-design-condition-2b8ec1586f15-border-color, var(--fsds-otp-color-border-accent, #d92d2e));
      outline-width: var(--fsds-otp-design-condition-2b8ec1586f15-focus-width, var(--fsds-otp-focus-ring-width, 2px));
      outline-color: var(--fsds-otp-design-condition-2b8ec1586f15-focus-color, var(--fsds-otp-focus-ring-color, #0566fe));
      outline-style: var(--fsds-otp-design-condition-2b8ec1586f15-focus-style, var(--fsds-otp-focus-ring-style, solid));
      outline-offset: var(--fsds-otp-design-condition-2b8ec1586f15-focus-offset, var(--fsds-otp-focus-ring-offset, 2px));
    }

    .otp__field:disabled {
      opacity: var(--fsds-otp-design-condition-82e351952582-appearance-opacity, 0.5);
      cursor: not-allowed;
    }
    }
  `;

  @property({ type: Number }) length?: number = 6;
  @property({ type: String }) value?: string;
  @property({ type: String }) defaultValue?: string;
  @property({ attribute: false }) onChange?: (value: string) => void;
  @property({ attribute: false }) onComplete?: (value: string) => void;
  @property({ type: String }) mode?: OTPMode = "numeric";
  @property({ type: Boolean }) disabled?: boolean;
  @property({ type: Boolean }) readOnly?: boolean;
  @property({ type: String }) label?: string = "One-time password";
  @property({ type: String }) fieldLabel?: string = "One-time password digit";
  @property({ type: String }) ariaDescribedby?: string;

  private initializedBehavior?: OTPBehavior;
  private get behavior(): OTPBehavior {
    return this.initializedBehavior ??= new OTPBehavior(this, {
    value: () => this.value,
    defaultValue: this.defaultValue,
    onChange: (v) => this.onChange?.(v),
  });
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute("data-fsds-component", "otp");
  }

  private computeClasses(): string {
    return [
      "otp",
      (this.mode ?? "numeric") ? `otp--${(this.mode ?? "numeric")}` : null,
      this.disabled ? "otp--disabled" : null,
    ].filter(Boolean).join(" ");
  }

  override render() {
    return html`<div class="${this.computeClasses()}" role="group" aria-label=${ifDefined((this.label ?? "One-time password"))} aria-describedby=${ifDefined(this.ariaDescribedby)} data-fsds-box="">
  <div class=${'otp__group'}>
    ${Array.from({ length: (this.length ?? 6) }, (_, index) => html`
    <input class=${'otp__field'} type="text" inputmode="numeric" autocomplete="one-time-code" maxlength="1" @input=${(e: Event) => this.behavior.setValue(String(this.behavior.value ?? '').padEnd(index, ' ').slice(0, index) + String((e.target as HTMLInputElement).value ?? '').slice(-1) + String(this.behavior.value ?? '').slice(index + 1))} ?disabled=${this.disabled ?? false} aria-label=${ifDefined((this.fieldLabel ?? "One-time password digit"))} aria-readonly=${ifDefined(this.readOnly === undefined ? undefined : (this.readOnly ? 'true' : 'false'))} data-otp-index=${index} />
    `)}
  </div>
</div>`;
  }
}

customElements.define('fsds-otp', OTPElement);


export class OTPGroupElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .otp {
      --fsds-otp-color-background-default: var(--fsds-semantic-color-background-secondary, #f7f7f7);
      --fsds-otp-color-foreground-primary: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-otp-color-border-default: var(--fsds-semantic-color-border-light, #b8b8b8);
      --fsds-otp-size-radius-default: var(--fsds-semantic-shape-control-radius-default, 6px);
      --fsds-otp-color-border-accent: var(--fsds-semantic-color-border-accent, #d92d2e);
      --fsds-otp-focus-ring-width: var(--fsds-semantic-focus-ring-width, 2px);
      --fsds-otp-focus-ring-color: var(--fsds-semantic-focus-ring-color, #0566fe);
      --fsds-otp-focus-ring-style: var(--fsds-semantic-focus-ring-style, solid);
      --fsds-otp-focus-ring-offset: var(--fsds-semantic-focus-ring-offset, 2px);
    }

    @layer components.defaults {
    .otp {
      padding-block-start: var(--fsds-box-model-padding-block-start, var(--fsds-semantic-input-size-medium-padding-block, 4px));
      padding-block-end: var(--fsds-box-model-padding-block-end, var(--fsds-semantic-input-size-medium-padding-block, 4px));
      padding-inline-start: var(--fsds-box-model-padding-inline-start, var(--fsds-semantic-input-size-medium-padding-inline, 8px));
      padding-inline-end: var(--fsds-box-model-padding-inline-end, var(--fsds-semantic-input-size-medium-padding-inline, 8px));
      gap: var(--fsds-box-model-gap, var(--fsds-semantic-input-size-medium-gap, 8px));
      width: var(--fsds-box-model-width, auto);
      min-width: var(--fsds-box-model-min-width, 0);
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, var(--fsds-semantic-input-size-medium-min-height, 32px));
      max-height: var(--fsds-box-model-max-height, none);
      display: inline-flex;
      align-items: center;
    }

    .otp__group {
      display: inline-flex;
      align-items: center;
      gap: var(--fsds-otp-design-group-spacing-gap, 4px);
    }

    .otp__field {
      display: block;
      width: 40px;
      height: 40px;
      text-align: var(--fsds-otp-design-field-typography-alignment, center);
      font-size: var(--fsds-otp-design-field-typography-size, 1rem);
      box-sizing: border-box;
      border-style: var(--fsds-otp-design-field-border-style, solid);
      border-width: var(--fsds-otp-design-field-border-width, 1px);
      border-radius: var(--fsds-otp-design-field-shape-radius, var(--fsds-otp-size-radius-default, 6px));
      border-color: var(--fsds-otp-design-field-border-color, var(--fsds-otp-color-border-default, #b8b8b8));
      background-color: var(--fsds-otp-design-field-background-fill, var(--fsds-otp-color-background-default, #f7f7f7));
      color: var(--fsds-otp-design-field-foreground-color, var(--fsds-otp-color-foreground-primary, #141414));
    }

    .otp__field:focus-visible:not([aria-disabled="true"]) {
      border-color: var(--fsds-otp-design-condition-2b8ec1586f15-border-color, var(--fsds-otp-color-border-accent, #d92d2e));
      outline-width: var(--fsds-otp-design-condition-2b8ec1586f15-focus-width, var(--fsds-otp-focus-ring-width, 2px));
      outline-color: var(--fsds-otp-design-condition-2b8ec1586f15-focus-color, var(--fsds-otp-focus-ring-color, #0566fe));
      outline-style: var(--fsds-otp-design-condition-2b8ec1586f15-focus-style, var(--fsds-otp-focus-ring-style, solid));
      outline-offset: var(--fsds-otp-design-condition-2b8ec1586f15-focus-offset, var(--fsds-otp-focus-ring-offset, 2px));
    }

    .otp__field:disabled {
      opacity: var(--fsds-otp-design-condition-82e351952582-appearance-opacity, 0.5);
      cursor: not-allowed;
    }
    }
  `;

  override render() {
    return html`<fsds-stack class="otp__group"><slot></slot></fsds-stack>`;
  }
}

customElements.define('fsds-otpgroup', OTPGroupElement);
// @generated:end

// @custom:start trailing

// @custom:end