// @generated:start imports
import { LitElement, html, css, nothing } from 'lit';
import { ref } from 'lit/directives/ref.js';
import { canActivateInteraction } from "../../primitives/interaction.js";
import { property } from 'lit/decorators.js';
import { DialogBehavior } from './DialogBehavior.js';
import { ifDefined } from 'lit/directives/if-defined.js';
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type DialogSize = "sm" | "md" | "lg" | "xl" | "full";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
export class DialogElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .dialog {
      --fsds-dialog-color-background-default: var(--fsds-semantic-color-background-primary, #ffffff);
      --fsds-dialog-color-foreground-default: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-dialog-color-border-default: var(--fsds-semantic-color-border-subtle, #d0d0d0);
      --fsds-dialog-size-radius-default: var(--fsds-semantic-shape-radius-large, 16px);
      --fsds-dialog-size-sm-width: 400px;
      --fsds-dialog-size-sm-max-width: 90vw;
      --fsds-dialog-size-md-width: 500px;
      --fsds-dialog-size-md-max-width: 90vw;
      --fsds-dialog-size-lg-width: 700px;
      --fsds-dialog-size-lg-max-width: 90vw;
      --fsds-dialog-size-xl-width: 900px;
      --fsds-dialog-size-xl-max-width: 95vw;
      --fsds-dialog-size-full-width: 100vw;
      --fsds-dialog-size-full-height: 100vh;
      --fsds-dialog-size-close-button-size: var(--fsds-core-spacing-size-08, 32px);
      --fsds-dialog-elevation-default: var(--fsds-semantic-elevation-surface-dialog, 0px 12px 16px #0000000f, 0px 25px 50px #00000026);
      --fsds-dialog-spacing-header-padding-top: var(--fsds-core-spacing-size-06, 16px);
      --fsds-dialog-spacing-body-padding-right: var(--fsds-core-spacing-size-07, 24px);
      --fsds-dialog-spacing-footer-gap: var(--fsds-core-spacing-size-03, 4px);
      --fsds-dialog-typography-title-font-size: var(--fsds-semantic-typography-heading-04, 18px);
      --fsds-dialog-typography-title-font-weight: var(--fsds-semantic-typography-font-weight-bold, 700);
      --fsds-dialog-typography-title-line-height: var(--fsds-semantic-typography-line-height-heading, 1);
    }

    .dialog__backdrop {
      --fsds-dialog-color-background-default: var(--fsds-semantic-color-overlay-scrim, #00000066);
    }

    .dialog__body {
      --fsds-dialog-color-foreground-default: var(--fsds-semantic-color-foreground-secondary, #474647);
    }

    .dialog__closeButton {
      --fsds-dialog-color-foreground-default: var(--fsds-semantic-color-foreground-secondary, #474647);
    }

    .dialog__closeButton:hover {
      --fsds-dialog-color-background-default: var(--fsds-semantic-color-background-hover, #f7f7f7);
    }

    @layer components.defaults {
    .dialog {
      padding-block-start: var(--fsds-box-model-padding-block-start, var(--fsds-semantic-surface-size-padding-block, 16px));
      padding-block-end: var(--fsds-box-model-padding-block-end, var(--fsds-semantic-surface-size-padding-block, 16px));
      padding-inline-start: var(--fsds-box-model-padding-inline-start, var(--fsds-semantic-surface-size-padding-inline, 16px));
      padding-inline-end: var(--fsds-box-model-padding-inline-end, var(--fsds-semantic-surface-size-padding-inline, 16px));
      gap: var(--fsds-box-model-gap, var(--fsds-semantic-surface-size-gap, 8px));
      width: var(--fsds-box-model-width, auto);
      min-width: var(--fsds-box-model-min-width, var(--fsds-semantic-surface-size-min-width, 64px));
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, 0);
      max-height: var(--fsds-box-model-max-height, none);
      position: fixed;
      inset: 0;
      z-index: 1000;
      display: flex;
      align-items: center;
      justify-content: center;
      pointer-events: none;

      &:has(> .dialog__modal[aria-modal="false"]) > .dialog__backdrop {
        display: none;
      }
    }

    .dialog__backdrop {
      position: absolute;
      inset: 0;
      pointer-events: auto;
    }

    .dialog__modal {
      position: relative;
      display: flex;
      flex-direction: column;
      background-color: var(--fsds-dialog-design-modal-background-fill, var(--fsds-dialog-color-background-default, #ffffff));
      color: var(--fsds-dialog-design-modal-foreground-color, var(--fsds-dialog-color-foreground-default, #141414));
      border-color: var(--fsds-dialog-design-modal-border-color, var(--fsds-dialog-color-border-default, #d0d0d0));
      border-style: var(--fsds-dialog-design-modal-border-style, solid);
      border-width: var(--fsds-dialog-design-modal-border-width, 1px);
      border-radius: var(--fsds-dialog-design-modal-shape-radius, var(--fsds-dialog-size-radius-default, 16px));
      box-shadow: var(--fsds-dialog-design-modal-elevation-shadow, var(--fsds-dialog-elevation-default, 0px 12px 16px #0000000f, 0px 25px 50px #00000026));
      width: var(--fsds-dialog-design-modal-sizing-width, var(--fsds-dialog-size-md-width, 500px));
      max-width: var(--fsds-dialog-design-modal-sizing-max-width, var(--fsds-dialog-size-md-max-width, 90vw));
      max-height: var(--fsds-dialog-design-modal-sizing-max-height, 90dvh);
      pointer-events: auto;
      box-sizing: border-box;
      overflow: hidden;
      min-width: var(--fsds-dialog-design-modal-sizing-min-width, 0);
    }

    .dialog__header {
      display: flex;
      align-items: center;
      padding-top: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-right: var(--fsds-dialog-spacing-body-padding-right, 24px);
      padding-bottom: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-left: var(--fsds-dialog-spacing-body-padding-right, 24px);
      border-bottom-color: var(--fsds-dialog-design-header-border-bottom-color, var(--fsds-dialog-color-border-default, #d0d0d0));
      border-bottom-style: var(--fsds-dialog-design-header-border-bottom-style, solid);
      border-bottom-width: var(--fsds-dialog-design-header-border-bottom-width, 1px);
      flex-shrink: 0;
    }

    .dialog__title {
      margin: 0;
      font-size: var(--fsds-dialog-design-title-typography-size, var(--fsds-dialog-typography-title-font-size, 18px));
      font-weight: var(--fsds-dialog-design-title-typography-weight, var(--fsds-dialog-typography-title-font-weight, 700));
      line-height: var(--fsds-dialog-design-title-typography-line-height, var(--fsds-dialog-typography-title-line-height, 1));
      color: var(--fsds-dialog-design-title-foreground-color, var(--fsds-dialog-color-foreground-default, #141414));
    }

    .dialog__body {
      flex: 1 1 auto;
      padding-top: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-right: var(--fsds-dialog-spacing-body-padding-right, 24px);
      padding-bottom: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-left: var(--fsds-dialog-spacing-body-padding-right, 24px);
      overflow-y: auto;
      min-width: var(--fsds-dialog-design-body-sizing-min-width, 0);
      min-height: var(--fsds-dialog-design-body-sizing-min-height, 0);
      overflow-wrap: anywhere;
    }

    .dialog__footer {
      display: flex;
      justify-content: flex-end;
      align-items: center;
      gap: var(--fsds-dialog-design-footer-spacing-gap, var(--fsds-dialog-spacing-footer-gap, 4px));
      padding-top: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-right: var(--fsds-dialog-spacing-body-padding-right, 24px);
      padding-bottom: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-left: var(--fsds-dialog-spacing-body-padding-right, 24px);
      border-top-color: var(--fsds-dialog-design-footer-border-top-color, var(--fsds-dialog-color-border-default, #d0d0d0));
      border-top-style: var(--fsds-dialog-design-footer-border-top-style, solid);
      border-top-width: var(--fsds-dialog-design-footer-border-top-width, 1px);
      flex-shrink: 0;
    }

    .dialog__closeButton {
      position: absolute;
      top: var(--fsds-dialog-spacing-header-padding-top, 16px);
      right: var(--fsds-dialog-spacing-body-padding-right, 24px);
      width: var(--fsds-dialog-design-close-button-sizing-width, var(--fsds-dialog-size-close-button-size, 32px));
      height: var(--fsds-dialog-design-close-button-sizing-height, var(--fsds-dialog-size-close-button-size, 32px));
      display: inline-flex;
      align-items: center;
      justify-content: center;
      background-color: var(--fsds-dialog-design-close-button-background-fill, transparent);
      border: 0;
      border-radius: var(--fsds-dialog-design-close-button-shape-radius, 9999px);
      cursor: pointer;
    }

    .dialog--sm .dialog__modal {
      width: var(--fsds-dialog-design-condition-c6049c96ab74-sizing-width, var(--fsds-dialog-size-sm-width, 400px));
      max-width: var(--fsds-dialog-design-condition-c6049c96ab74-sizing-max-width, var(--fsds-dialog-size-sm-max-width, 90vw));
    }

    .dialog--lg .dialog__modal {
      width: var(--fsds-dialog-design-condition-3fb7229a17a8-sizing-width, var(--fsds-dialog-size-lg-width, 700px));
      max-width: var(--fsds-dialog-design-condition-3fb7229a17a8-sizing-max-width, var(--fsds-dialog-size-lg-max-width, 90vw));
    }

    .dialog--xl .dialog__modal {
      width: var(--fsds-dialog-design-condition-81887f72fc05-sizing-width, var(--fsds-dialog-size-xl-width, 900px));
      max-width: var(--fsds-dialog-design-condition-81887f72fc05-sizing-max-width, var(--fsds-dialog-size-xl-max-width, 95vw));
    }

    .dialog--full .dialog__modal {
      width: var(--fsds-dialog-design-condition-aa10b66155cb-sizing-width, var(--fsds-dialog-size-full-width, 100vw));
      height: var(--fsds-dialog-design-condition-aa10b66155cb-sizing-height, var(--fsds-dialog-size-full-height, 100vh));
      max-width: 100vw;
      max-height: 100vh;
      border-radius: var(--fsds-dialog-design-condition-aa10b66155cb-shape-radius, 0);
    }
    }
  `;

  @property({ type: Boolean }) open?: boolean;
  @property({ type: Boolean }) defaultOpen?: boolean;
  @property({ attribute: false }) onOpenChange?: (open: boolean) => void;
  @property({ type: Boolean }) modal?: boolean = true;
  @property({ type: String }) size?: DialogSize = "md";
  @property({ type: Boolean }) dismissible?: boolean = true;
  @property({ type: Boolean }) closeOnEscape?: boolean = true;
  @property({ type: Boolean }) closeOnBackdropClick?: boolean = true;
  @property({ type: String }) initialFocus?: string;
  @property({ type: String }) returnFocus?: string;
  @property({ attribute: 'aria-label', reflect: true })
  override ariaLabel: string | null = null;
  @property({ type: String }) ariaLabelledby?: string;
  @property({ type: String }) ariaDescribedby?: string;
  private interactionPanel?: HTMLElement;

  private initializedBehavior?: DialogBehavior;
  private get behavior(): DialogBehavior {
    const host = this;
    return this.initializedBehavior ??= new DialogBehavior(this, {
    get containerEl() { return host.interactionPanel; },
    open: () => this.open,
    defaultOpen: this.defaultOpen,
    onOpenChange: (v) => this.onOpenChange?.(v),
    closeOnEscape: this.closeOnEscape,
    closeOnBackdropClick: this.closeOnBackdropClick,
    modal: () => this.modal,
  });
  }

  private _handleOverlayClick = (): void => {
    if (this.closeOnBackdropClick !== false) {
      this.behavior.setOpenness(false);
    }
  };

  private _moving = false;
  private _portaled = false;
  private _portalOriginParent: Node | null = null;
  private _portalOriginNext: Node | null = null;

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute("data-fsds-component", "dialog");
    this.addEventListener('click', this._handleOverlayClick);
    if (!this._portaled && typeof document !== "undefined" && this.parentNode && this.parentNode !== document.body) {
      this._portalOriginParent = this.parentNode;
      this._portalOriginNext = this.nextSibling;
      this._portaled = true;
      this._moving = true;
      document.body.appendChild(this);
      this._moving = false;
    }
  }

  override disconnectedCallback(): void {
    this.removeEventListener('click', this._handleOverlayClick);
    if (!this._moving) {
      if (this._portalOriginParent && this._portalOriginParent.isConnected) {
        this._portalOriginParent.insertBefore(this, this._portalOriginNext);
      }
      this._portaled = false;
      this._portalOriginParent = null;
      this._portalOriginNext = null;
    }
    super.disconnectedCallback();
  }

  private computeClasses(): string {
    return [
      "dialog",
      (this.size ?? "md") ? `dialog--${(this.size ?? "md")}` : null,
    ].filter(Boolean).join(" ");
  }

  override render() {
    return html`<div class="${this.computeClasses()}" data-fsds-box="">
  ${this.behavior.openness ? html`
  <div class=${'dialog__backdrop'} aria-hidden="true" data-fsds-channel-renders="openness"></div>
  ` : nothing}
  ${this.behavior.openness ? html`
  <div class=${'dialog__modal'} ${ref(element => { this.interactionPanel = element instanceof HTMLElement ? element : undefined; })} role="dialog" aria-modal=${ifDefined((this.modal ?? true) === undefined ? undefined : ((this.modal ?? true) ? 'true' : 'false'))} aria-label=${ifDefined(this.ariaLabel ?? undefined)} aria-labelledby=${ifDefined([this.querySelector('[slot="title"]') !== null && !this.ariaLabel ? 'dialog-title' : null, this.ariaLabelledby].filter(Boolean).join(' ') || undefined)} aria-describedby=${ifDefined(['dialog-body', this.ariaDescribedby].filter(Boolean).join(' ') || undefined)} data-fsds-channel-renders="openness" @click=${(e: Event) => e.stopPropagation()}>
    <div class=${'dialog__header'}>
      <h2 class=${'dialog__title'} id="dialog-title">
        <slot name="title" @slotchange=${() => this.requestUpdate()}></slot>
      </h2>
      <button class=${'dialog__closeButton'} type="button" aria-label="Close dialog" @click=${(e: MouseEvent) => { if (canActivateInteraction(e, false)) this.behavior.setOpenness(false); }}></button>
    </div>
    <div class=${'dialog__body'} id="dialog-body">
      <slot></slot>
    </div>
    <div class=${'dialog__footer'}>
      <slot name="footer"></slot>
    </div>
  </div>
  ` : nothing}
</div>`;
  }
}

customElements.define('fsds-dialog', DialogElement);


export class DialogHeaderElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .dialog {
      --fsds-dialog-color-background-default: var(--fsds-semantic-color-background-primary, #ffffff);
      --fsds-dialog-color-foreground-default: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-dialog-color-border-default: var(--fsds-semantic-color-border-subtle, #d0d0d0);
      --fsds-dialog-size-radius-default: var(--fsds-semantic-shape-radius-large, 16px);
      --fsds-dialog-size-sm-width: 400px;
      --fsds-dialog-size-sm-max-width: 90vw;
      --fsds-dialog-size-md-width: 500px;
      --fsds-dialog-size-md-max-width: 90vw;
      --fsds-dialog-size-lg-width: 700px;
      --fsds-dialog-size-lg-max-width: 90vw;
      --fsds-dialog-size-xl-width: 900px;
      --fsds-dialog-size-xl-max-width: 95vw;
      --fsds-dialog-size-full-width: 100vw;
      --fsds-dialog-size-full-height: 100vh;
      --fsds-dialog-size-close-button-size: var(--fsds-core-spacing-size-08, 32px);
      --fsds-dialog-elevation-default: var(--fsds-semantic-elevation-surface-dialog, 0px 12px 16px #0000000f, 0px 25px 50px #00000026);
      --fsds-dialog-spacing-header-padding-top: var(--fsds-core-spacing-size-06, 16px);
      --fsds-dialog-spacing-body-padding-right: var(--fsds-core-spacing-size-07, 24px);
      --fsds-dialog-spacing-footer-gap: var(--fsds-core-spacing-size-03, 4px);
      --fsds-dialog-typography-title-font-size: var(--fsds-semantic-typography-heading-04, 18px);
      --fsds-dialog-typography-title-font-weight: var(--fsds-semantic-typography-font-weight-bold, 700);
      --fsds-dialog-typography-title-line-height: var(--fsds-semantic-typography-line-height-heading, 1);
    }

    .dialog__backdrop {
      --fsds-dialog-color-background-default: var(--fsds-semantic-color-overlay-scrim, #00000066);
    }

    .dialog__body {
      --fsds-dialog-color-foreground-default: var(--fsds-semantic-color-foreground-secondary, #474647);
    }

    .dialog__closeButton {
      --fsds-dialog-color-foreground-default: var(--fsds-semantic-color-foreground-secondary, #474647);
    }

    .dialog__closeButton:hover {
      --fsds-dialog-color-background-default: var(--fsds-semantic-color-background-hover, #f7f7f7);
    }

    @layer components.defaults {
    .dialog {
      padding-block-start: var(--fsds-box-model-padding-block-start, var(--fsds-semantic-surface-size-padding-block, 16px));
      padding-block-end: var(--fsds-box-model-padding-block-end, var(--fsds-semantic-surface-size-padding-block, 16px));
      padding-inline-start: var(--fsds-box-model-padding-inline-start, var(--fsds-semantic-surface-size-padding-inline, 16px));
      padding-inline-end: var(--fsds-box-model-padding-inline-end, var(--fsds-semantic-surface-size-padding-inline, 16px));
      gap: var(--fsds-box-model-gap, var(--fsds-semantic-surface-size-gap, 8px));
      width: var(--fsds-box-model-width, auto);
      min-width: var(--fsds-box-model-min-width, var(--fsds-semantic-surface-size-min-width, 64px));
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, 0);
      max-height: var(--fsds-box-model-max-height, none);
      position: fixed;
      inset: 0;
      z-index: 1000;
      display: flex;
      align-items: center;
      justify-content: center;
      pointer-events: none;

      &:has(> .dialog__modal[aria-modal="false"]) > .dialog__backdrop {
        display: none;
      }
    }

    .dialog__backdrop {
      position: absolute;
      inset: 0;
      pointer-events: auto;
    }

    .dialog__modal {
      position: relative;
      display: flex;
      flex-direction: column;
      background-color: var(--fsds-dialog-design-modal-background-fill, var(--fsds-dialog-color-background-default, #ffffff));
      color: var(--fsds-dialog-design-modal-foreground-color, var(--fsds-dialog-color-foreground-default, #141414));
      border-color: var(--fsds-dialog-design-modal-border-color, var(--fsds-dialog-color-border-default, #d0d0d0));
      border-style: var(--fsds-dialog-design-modal-border-style, solid);
      border-width: var(--fsds-dialog-design-modal-border-width, 1px);
      border-radius: var(--fsds-dialog-design-modal-shape-radius, var(--fsds-dialog-size-radius-default, 16px));
      box-shadow: var(--fsds-dialog-design-modal-elevation-shadow, var(--fsds-dialog-elevation-default, 0px 12px 16px #0000000f, 0px 25px 50px #00000026));
      width: var(--fsds-dialog-design-modal-sizing-width, var(--fsds-dialog-size-md-width, 500px));
      max-width: var(--fsds-dialog-design-modal-sizing-max-width, var(--fsds-dialog-size-md-max-width, 90vw));
      max-height: var(--fsds-dialog-design-modal-sizing-max-height, 90dvh);
      pointer-events: auto;
      box-sizing: border-box;
      overflow: hidden;
      min-width: var(--fsds-dialog-design-modal-sizing-min-width, 0);
    }

    .dialog__header {
      display: flex;
      align-items: center;
      padding-top: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-right: var(--fsds-dialog-spacing-body-padding-right, 24px);
      padding-bottom: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-left: var(--fsds-dialog-spacing-body-padding-right, 24px);
      border-bottom-color: var(--fsds-dialog-design-header-border-bottom-color, var(--fsds-dialog-color-border-default, #d0d0d0));
      border-bottom-style: var(--fsds-dialog-design-header-border-bottom-style, solid);
      border-bottom-width: var(--fsds-dialog-design-header-border-bottom-width, 1px);
      flex-shrink: 0;
    }

    .dialog__title {
      margin: 0;
      font-size: var(--fsds-dialog-design-title-typography-size, var(--fsds-dialog-typography-title-font-size, 18px));
      font-weight: var(--fsds-dialog-design-title-typography-weight, var(--fsds-dialog-typography-title-font-weight, 700));
      line-height: var(--fsds-dialog-design-title-typography-line-height, var(--fsds-dialog-typography-title-line-height, 1));
      color: var(--fsds-dialog-design-title-foreground-color, var(--fsds-dialog-color-foreground-default, #141414));
    }

    .dialog__body {
      flex: 1 1 auto;
      padding-top: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-right: var(--fsds-dialog-spacing-body-padding-right, 24px);
      padding-bottom: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-left: var(--fsds-dialog-spacing-body-padding-right, 24px);
      overflow-y: auto;
      min-width: var(--fsds-dialog-design-body-sizing-min-width, 0);
      min-height: var(--fsds-dialog-design-body-sizing-min-height, 0);
      overflow-wrap: anywhere;
    }

    .dialog__footer {
      display: flex;
      justify-content: flex-end;
      align-items: center;
      gap: var(--fsds-dialog-design-footer-spacing-gap, var(--fsds-dialog-spacing-footer-gap, 4px));
      padding-top: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-right: var(--fsds-dialog-spacing-body-padding-right, 24px);
      padding-bottom: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-left: var(--fsds-dialog-spacing-body-padding-right, 24px);
      border-top-color: var(--fsds-dialog-design-footer-border-top-color, var(--fsds-dialog-color-border-default, #d0d0d0));
      border-top-style: var(--fsds-dialog-design-footer-border-top-style, solid);
      border-top-width: var(--fsds-dialog-design-footer-border-top-width, 1px);
      flex-shrink: 0;
    }

    .dialog__closeButton {
      position: absolute;
      top: var(--fsds-dialog-spacing-header-padding-top, 16px);
      right: var(--fsds-dialog-spacing-body-padding-right, 24px);
      width: var(--fsds-dialog-design-close-button-sizing-width, var(--fsds-dialog-size-close-button-size, 32px));
      height: var(--fsds-dialog-design-close-button-sizing-height, var(--fsds-dialog-size-close-button-size, 32px));
      display: inline-flex;
      align-items: center;
      justify-content: center;
      background-color: var(--fsds-dialog-design-close-button-background-fill, transparent);
      border: 0;
      border-radius: var(--fsds-dialog-design-close-button-shape-radius, 9999px);
      cursor: pointer;
    }

    .dialog--sm .dialog__modal {
      width: var(--fsds-dialog-design-condition-c6049c96ab74-sizing-width, var(--fsds-dialog-size-sm-width, 400px));
      max-width: var(--fsds-dialog-design-condition-c6049c96ab74-sizing-max-width, var(--fsds-dialog-size-sm-max-width, 90vw));
    }

    .dialog--lg .dialog__modal {
      width: var(--fsds-dialog-design-condition-3fb7229a17a8-sizing-width, var(--fsds-dialog-size-lg-width, 700px));
      max-width: var(--fsds-dialog-design-condition-3fb7229a17a8-sizing-max-width, var(--fsds-dialog-size-lg-max-width, 90vw));
    }

    .dialog--xl .dialog__modal {
      width: var(--fsds-dialog-design-condition-81887f72fc05-sizing-width, var(--fsds-dialog-size-xl-width, 900px));
      max-width: var(--fsds-dialog-design-condition-81887f72fc05-sizing-max-width, var(--fsds-dialog-size-xl-max-width, 95vw));
    }

    .dialog--full .dialog__modal {
      width: var(--fsds-dialog-design-condition-aa10b66155cb-sizing-width, var(--fsds-dialog-size-full-width, 100vw));
      height: var(--fsds-dialog-design-condition-aa10b66155cb-sizing-height, var(--fsds-dialog-size-full-height, 100vh));
      max-width: 100vw;
      max-height: 100vh;
      border-radius: var(--fsds-dialog-design-condition-aa10b66155cb-shape-radius, 0);
    }
    }
  `;

  override render() {
    return html`<fsds-stack class="dialog__header"><slot></slot></fsds-stack>`;
  }
}

customElements.define('fsds-dialog-header', DialogHeaderElement);

export class DialogTitleElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .dialog {
      --fsds-dialog-color-background-default: var(--fsds-semantic-color-background-primary, #ffffff);
      --fsds-dialog-color-foreground-default: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-dialog-color-border-default: var(--fsds-semantic-color-border-subtle, #d0d0d0);
      --fsds-dialog-size-radius-default: var(--fsds-semantic-shape-radius-large, 16px);
      --fsds-dialog-size-sm-width: 400px;
      --fsds-dialog-size-sm-max-width: 90vw;
      --fsds-dialog-size-md-width: 500px;
      --fsds-dialog-size-md-max-width: 90vw;
      --fsds-dialog-size-lg-width: 700px;
      --fsds-dialog-size-lg-max-width: 90vw;
      --fsds-dialog-size-xl-width: 900px;
      --fsds-dialog-size-xl-max-width: 95vw;
      --fsds-dialog-size-full-width: 100vw;
      --fsds-dialog-size-full-height: 100vh;
      --fsds-dialog-size-close-button-size: var(--fsds-core-spacing-size-08, 32px);
      --fsds-dialog-elevation-default: var(--fsds-semantic-elevation-surface-dialog, 0px 12px 16px #0000000f, 0px 25px 50px #00000026);
      --fsds-dialog-spacing-header-padding-top: var(--fsds-core-spacing-size-06, 16px);
      --fsds-dialog-spacing-body-padding-right: var(--fsds-core-spacing-size-07, 24px);
      --fsds-dialog-spacing-footer-gap: var(--fsds-core-spacing-size-03, 4px);
      --fsds-dialog-typography-title-font-size: var(--fsds-semantic-typography-heading-04, 18px);
      --fsds-dialog-typography-title-font-weight: var(--fsds-semantic-typography-font-weight-bold, 700);
      --fsds-dialog-typography-title-line-height: var(--fsds-semantic-typography-line-height-heading, 1);
    }

    .dialog__backdrop {
      --fsds-dialog-color-background-default: var(--fsds-semantic-color-overlay-scrim, #00000066);
    }

    .dialog__body {
      --fsds-dialog-color-foreground-default: var(--fsds-semantic-color-foreground-secondary, #474647);
    }

    .dialog__closeButton {
      --fsds-dialog-color-foreground-default: var(--fsds-semantic-color-foreground-secondary, #474647);
    }

    .dialog__closeButton:hover {
      --fsds-dialog-color-background-default: var(--fsds-semantic-color-background-hover, #f7f7f7);
    }

    @layer components.defaults {
    .dialog {
      padding-block-start: var(--fsds-box-model-padding-block-start, var(--fsds-semantic-surface-size-padding-block, 16px));
      padding-block-end: var(--fsds-box-model-padding-block-end, var(--fsds-semantic-surface-size-padding-block, 16px));
      padding-inline-start: var(--fsds-box-model-padding-inline-start, var(--fsds-semantic-surface-size-padding-inline, 16px));
      padding-inline-end: var(--fsds-box-model-padding-inline-end, var(--fsds-semantic-surface-size-padding-inline, 16px));
      gap: var(--fsds-box-model-gap, var(--fsds-semantic-surface-size-gap, 8px));
      width: var(--fsds-box-model-width, auto);
      min-width: var(--fsds-box-model-min-width, var(--fsds-semantic-surface-size-min-width, 64px));
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, 0);
      max-height: var(--fsds-box-model-max-height, none);
      position: fixed;
      inset: 0;
      z-index: 1000;
      display: flex;
      align-items: center;
      justify-content: center;
      pointer-events: none;

      &:has(> .dialog__modal[aria-modal="false"]) > .dialog__backdrop {
        display: none;
      }
    }

    .dialog__backdrop {
      position: absolute;
      inset: 0;
      pointer-events: auto;
    }

    .dialog__modal {
      position: relative;
      display: flex;
      flex-direction: column;
      background-color: var(--fsds-dialog-design-modal-background-fill, var(--fsds-dialog-color-background-default, #ffffff));
      color: var(--fsds-dialog-design-modal-foreground-color, var(--fsds-dialog-color-foreground-default, #141414));
      border-color: var(--fsds-dialog-design-modal-border-color, var(--fsds-dialog-color-border-default, #d0d0d0));
      border-style: var(--fsds-dialog-design-modal-border-style, solid);
      border-width: var(--fsds-dialog-design-modal-border-width, 1px);
      border-radius: var(--fsds-dialog-design-modal-shape-radius, var(--fsds-dialog-size-radius-default, 16px));
      box-shadow: var(--fsds-dialog-design-modal-elevation-shadow, var(--fsds-dialog-elevation-default, 0px 12px 16px #0000000f, 0px 25px 50px #00000026));
      width: var(--fsds-dialog-design-modal-sizing-width, var(--fsds-dialog-size-md-width, 500px));
      max-width: var(--fsds-dialog-design-modal-sizing-max-width, var(--fsds-dialog-size-md-max-width, 90vw));
      max-height: var(--fsds-dialog-design-modal-sizing-max-height, 90dvh);
      pointer-events: auto;
      box-sizing: border-box;
      overflow: hidden;
      min-width: var(--fsds-dialog-design-modal-sizing-min-width, 0);
    }

    .dialog__header {
      display: flex;
      align-items: center;
      padding-top: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-right: var(--fsds-dialog-spacing-body-padding-right, 24px);
      padding-bottom: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-left: var(--fsds-dialog-spacing-body-padding-right, 24px);
      border-bottom-color: var(--fsds-dialog-design-header-border-bottom-color, var(--fsds-dialog-color-border-default, #d0d0d0));
      border-bottom-style: var(--fsds-dialog-design-header-border-bottom-style, solid);
      border-bottom-width: var(--fsds-dialog-design-header-border-bottom-width, 1px);
      flex-shrink: 0;
    }

    .dialog__title {
      margin: 0;
      font-size: var(--fsds-dialog-design-title-typography-size, var(--fsds-dialog-typography-title-font-size, 18px));
      font-weight: var(--fsds-dialog-design-title-typography-weight, var(--fsds-dialog-typography-title-font-weight, 700));
      line-height: var(--fsds-dialog-design-title-typography-line-height, var(--fsds-dialog-typography-title-line-height, 1));
      color: var(--fsds-dialog-design-title-foreground-color, var(--fsds-dialog-color-foreground-default, #141414));
    }

    .dialog__body {
      flex: 1 1 auto;
      padding-top: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-right: var(--fsds-dialog-spacing-body-padding-right, 24px);
      padding-bottom: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-left: var(--fsds-dialog-spacing-body-padding-right, 24px);
      overflow-y: auto;
      min-width: var(--fsds-dialog-design-body-sizing-min-width, 0);
      min-height: var(--fsds-dialog-design-body-sizing-min-height, 0);
      overflow-wrap: anywhere;
    }

    .dialog__footer {
      display: flex;
      justify-content: flex-end;
      align-items: center;
      gap: var(--fsds-dialog-design-footer-spacing-gap, var(--fsds-dialog-spacing-footer-gap, 4px));
      padding-top: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-right: var(--fsds-dialog-spacing-body-padding-right, 24px);
      padding-bottom: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-left: var(--fsds-dialog-spacing-body-padding-right, 24px);
      border-top-color: var(--fsds-dialog-design-footer-border-top-color, var(--fsds-dialog-color-border-default, #d0d0d0));
      border-top-style: var(--fsds-dialog-design-footer-border-top-style, solid);
      border-top-width: var(--fsds-dialog-design-footer-border-top-width, 1px);
      flex-shrink: 0;
    }

    .dialog__closeButton {
      position: absolute;
      top: var(--fsds-dialog-spacing-header-padding-top, 16px);
      right: var(--fsds-dialog-spacing-body-padding-right, 24px);
      width: var(--fsds-dialog-design-close-button-sizing-width, var(--fsds-dialog-size-close-button-size, 32px));
      height: var(--fsds-dialog-design-close-button-sizing-height, var(--fsds-dialog-size-close-button-size, 32px));
      display: inline-flex;
      align-items: center;
      justify-content: center;
      background-color: var(--fsds-dialog-design-close-button-background-fill, transparent);
      border: 0;
      border-radius: var(--fsds-dialog-design-close-button-shape-radius, 9999px);
      cursor: pointer;
    }

    .dialog--sm .dialog__modal {
      width: var(--fsds-dialog-design-condition-c6049c96ab74-sizing-width, var(--fsds-dialog-size-sm-width, 400px));
      max-width: var(--fsds-dialog-design-condition-c6049c96ab74-sizing-max-width, var(--fsds-dialog-size-sm-max-width, 90vw));
    }

    .dialog--lg .dialog__modal {
      width: var(--fsds-dialog-design-condition-3fb7229a17a8-sizing-width, var(--fsds-dialog-size-lg-width, 700px));
      max-width: var(--fsds-dialog-design-condition-3fb7229a17a8-sizing-max-width, var(--fsds-dialog-size-lg-max-width, 90vw));
    }

    .dialog--xl .dialog__modal {
      width: var(--fsds-dialog-design-condition-81887f72fc05-sizing-width, var(--fsds-dialog-size-xl-width, 900px));
      max-width: var(--fsds-dialog-design-condition-81887f72fc05-sizing-max-width, var(--fsds-dialog-size-xl-max-width, 95vw));
    }

    .dialog--full .dialog__modal {
      width: var(--fsds-dialog-design-condition-aa10b66155cb-sizing-width, var(--fsds-dialog-size-full-width, 100vw));
      height: var(--fsds-dialog-design-condition-aa10b66155cb-sizing-height, var(--fsds-dialog-size-full-height, 100vh));
      max-width: 100vw;
      max-height: 100vh;
      border-radius: var(--fsds-dialog-design-condition-aa10b66155cb-shape-radius, 0);
    }
    }
  `;

  override render() {
    return html`<fsds-stack as="h3" class="dialog__title"><slot></slot></fsds-stack>`;
  }
}

customElements.define('fsds-dialog-title', DialogTitleElement);

export class DialogBodyElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .dialog {
      --fsds-dialog-color-background-default: var(--fsds-semantic-color-background-primary, #ffffff);
      --fsds-dialog-color-foreground-default: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-dialog-color-border-default: var(--fsds-semantic-color-border-subtle, #d0d0d0);
      --fsds-dialog-size-radius-default: var(--fsds-semantic-shape-radius-large, 16px);
      --fsds-dialog-size-sm-width: 400px;
      --fsds-dialog-size-sm-max-width: 90vw;
      --fsds-dialog-size-md-width: 500px;
      --fsds-dialog-size-md-max-width: 90vw;
      --fsds-dialog-size-lg-width: 700px;
      --fsds-dialog-size-lg-max-width: 90vw;
      --fsds-dialog-size-xl-width: 900px;
      --fsds-dialog-size-xl-max-width: 95vw;
      --fsds-dialog-size-full-width: 100vw;
      --fsds-dialog-size-full-height: 100vh;
      --fsds-dialog-size-close-button-size: var(--fsds-core-spacing-size-08, 32px);
      --fsds-dialog-elevation-default: var(--fsds-semantic-elevation-surface-dialog, 0px 12px 16px #0000000f, 0px 25px 50px #00000026);
      --fsds-dialog-spacing-header-padding-top: var(--fsds-core-spacing-size-06, 16px);
      --fsds-dialog-spacing-body-padding-right: var(--fsds-core-spacing-size-07, 24px);
      --fsds-dialog-spacing-footer-gap: var(--fsds-core-spacing-size-03, 4px);
      --fsds-dialog-typography-title-font-size: var(--fsds-semantic-typography-heading-04, 18px);
      --fsds-dialog-typography-title-font-weight: var(--fsds-semantic-typography-font-weight-bold, 700);
      --fsds-dialog-typography-title-line-height: var(--fsds-semantic-typography-line-height-heading, 1);
    }

    .dialog__backdrop {
      --fsds-dialog-color-background-default: var(--fsds-semantic-color-overlay-scrim, #00000066);
    }

    .dialog__body {
      --fsds-dialog-color-foreground-default: var(--fsds-semantic-color-foreground-secondary, #474647);
    }

    .dialog__closeButton {
      --fsds-dialog-color-foreground-default: var(--fsds-semantic-color-foreground-secondary, #474647);
    }

    .dialog__closeButton:hover {
      --fsds-dialog-color-background-default: var(--fsds-semantic-color-background-hover, #f7f7f7);
    }

    @layer components.defaults {
    .dialog {
      padding-block-start: var(--fsds-box-model-padding-block-start, var(--fsds-semantic-surface-size-padding-block, 16px));
      padding-block-end: var(--fsds-box-model-padding-block-end, var(--fsds-semantic-surface-size-padding-block, 16px));
      padding-inline-start: var(--fsds-box-model-padding-inline-start, var(--fsds-semantic-surface-size-padding-inline, 16px));
      padding-inline-end: var(--fsds-box-model-padding-inline-end, var(--fsds-semantic-surface-size-padding-inline, 16px));
      gap: var(--fsds-box-model-gap, var(--fsds-semantic-surface-size-gap, 8px));
      width: var(--fsds-box-model-width, auto);
      min-width: var(--fsds-box-model-min-width, var(--fsds-semantic-surface-size-min-width, 64px));
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, 0);
      max-height: var(--fsds-box-model-max-height, none);
      position: fixed;
      inset: 0;
      z-index: 1000;
      display: flex;
      align-items: center;
      justify-content: center;
      pointer-events: none;

      &:has(> .dialog__modal[aria-modal="false"]) > .dialog__backdrop {
        display: none;
      }
    }

    .dialog__backdrop {
      position: absolute;
      inset: 0;
      pointer-events: auto;
    }

    .dialog__modal {
      position: relative;
      display: flex;
      flex-direction: column;
      background-color: var(--fsds-dialog-design-modal-background-fill, var(--fsds-dialog-color-background-default, #ffffff));
      color: var(--fsds-dialog-design-modal-foreground-color, var(--fsds-dialog-color-foreground-default, #141414));
      border-color: var(--fsds-dialog-design-modal-border-color, var(--fsds-dialog-color-border-default, #d0d0d0));
      border-style: var(--fsds-dialog-design-modal-border-style, solid);
      border-width: var(--fsds-dialog-design-modal-border-width, 1px);
      border-radius: var(--fsds-dialog-design-modal-shape-radius, var(--fsds-dialog-size-radius-default, 16px));
      box-shadow: var(--fsds-dialog-design-modal-elevation-shadow, var(--fsds-dialog-elevation-default, 0px 12px 16px #0000000f, 0px 25px 50px #00000026));
      width: var(--fsds-dialog-design-modal-sizing-width, var(--fsds-dialog-size-md-width, 500px));
      max-width: var(--fsds-dialog-design-modal-sizing-max-width, var(--fsds-dialog-size-md-max-width, 90vw));
      max-height: var(--fsds-dialog-design-modal-sizing-max-height, 90dvh);
      pointer-events: auto;
      box-sizing: border-box;
      overflow: hidden;
      min-width: var(--fsds-dialog-design-modal-sizing-min-width, 0);
    }

    .dialog__header {
      display: flex;
      align-items: center;
      padding-top: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-right: var(--fsds-dialog-spacing-body-padding-right, 24px);
      padding-bottom: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-left: var(--fsds-dialog-spacing-body-padding-right, 24px);
      border-bottom-color: var(--fsds-dialog-design-header-border-bottom-color, var(--fsds-dialog-color-border-default, #d0d0d0));
      border-bottom-style: var(--fsds-dialog-design-header-border-bottom-style, solid);
      border-bottom-width: var(--fsds-dialog-design-header-border-bottom-width, 1px);
      flex-shrink: 0;
    }

    .dialog__title {
      margin: 0;
      font-size: var(--fsds-dialog-design-title-typography-size, var(--fsds-dialog-typography-title-font-size, 18px));
      font-weight: var(--fsds-dialog-design-title-typography-weight, var(--fsds-dialog-typography-title-font-weight, 700));
      line-height: var(--fsds-dialog-design-title-typography-line-height, var(--fsds-dialog-typography-title-line-height, 1));
      color: var(--fsds-dialog-design-title-foreground-color, var(--fsds-dialog-color-foreground-default, #141414));
    }

    .dialog__body {
      flex: 1 1 auto;
      padding-top: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-right: var(--fsds-dialog-spacing-body-padding-right, 24px);
      padding-bottom: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-left: var(--fsds-dialog-spacing-body-padding-right, 24px);
      overflow-y: auto;
      min-width: var(--fsds-dialog-design-body-sizing-min-width, 0);
      min-height: var(--fsds-dialog-design-body-sizing-min-height, 0);
      overflow-wrap: anywhere;
    }

    .dialog__footer {
      display: flex;
      justify-content: flex-end;
      align-items: center;
      gap: var(--fsds-dialog-design-footer-spacing-gap, var(--fsds-dialog-spacing-footer-gap, 4px));
      padding-top: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-right: var(--fsds-dialog-spacing-body-padding-right, 24px);
      padding-bottom: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-left: var(--fsds-dialog-spacing-body-padding-right, 24px);
      border-top-color: var(--fsds-dialog-design-footer-border-top-color, var(--fsds-dialog-color-border-default, #d0d0d0));
      border-top-style: var(--fsds-dialog-design-footer-border-top-style, solid);
      border-top-width: var(--fsds-dialog-design-footer-border-top-width, 1px);
      flex-shrink: 0;
    }

    .dialog__closeButton {
      position: absolute;
      top: var(--fsds-dialog-spacing-header-padding-top, 16px);
      right: var(--fsds-dialog-spacing-body-padding-right, 24px);
      width: var(--fsds-dialog-design-close-button-sizing-width, var(--fsds-dialog-size-close-button-size, 32px));
      height: var(--fsds-dialog-design-close-button-sizing-height, var(--fsds-dialog-size-close-button-size, 32px));
      display: inline-flex;
      align-items: center;
      justify-content: center;
      background-color: var(--fsds-dialog-design-close-button-background-fill, transparent);
      border: 0;
      border-radius: var(--fsds-dialog-design-close-button-shape-radius, 9999px);
      cursor: pointer;
    }

    .dialog--sm .dialog__modal {
      width: var(--fsds-dialog-design-condition-c6049c96ab74-sizing-width, var(--fsds-dialog-size-sm-width, 400px));
      max-width: var(--fsds-dialog-design-condition-c6049c96ab74-sizing-max-width, var(--fsds-dialog-size-sm-max-width, 90vw));
    }

    .dialog--lg .dialog__modal {
      width: var(--fsds-dialog-design-condition-3fb7229a17a8-sizing-width, var(--fsds-dialog-size-lg-width, 700px));
      max-width: var(--fsds-dialog-design-condition-3fb7229a17a8-sizing-max-width, var(--fsds-dialog-size-lg-max-width, 90vw));
    }

    .dialog--xl .dialog__modal {
      width: var(--fsds-dialog-design-condition-81887f72fc05-sizing-width, var(--fsds-dialog-size-xl-width, 900px));
      max-width: var(--fsds-dialog-design-condition-81887f72fc05-sizing-max-width, var(--fsds-dialog-size-xl-max-width, 95vw));
    }

    .dialog--full .dialog__modal {
      width: var(--fsds-dialog-design-condition-aa10b66155cb-sizing-width, var(--fsds-dialog-size-full-width, 100vw));
      height: var(--fsds-dialog-design-condition-aa10b66155cb-sizing-height, var(--fsds-dialog-size-full-height, 100vh));
      max-width: 100vw;
      max-height: 100vh;
      border-radius: var(--fsds-dialog-design-condition-aa10b66155cb-shape-radius, 0);
    }
    }
  `;

  override render() {
    return html`<fsds-stack class="dialog__body"><slot></slot></fsds-stack>`;
  }
}

customElements.define('fsds-dialog-body', DialogBodyElement);

export class DialogFooterElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .dialog {
      --fsds-dialog-color-background-default: var(--fsds-semantic-color-background-primary, #ffffff);
      --fsds-dialog-color-foreground-default: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-dialog-color-border-default: var(--fsds-semantic-color-border-subtle, #d0d0d0);
      --fsds-dialog-size-radius-default: var(--fsds-semantic-shape-radius-large, 16px);
      --fsds-dialog-size-sm-width: 400px;
      --fsds-dialog-size-sm-max-width: 90vw;
      --fsds-dialog-size-md-width: 500px;
      --fsds-dialog-size-md-max-width: 90vw;
      --fsds-dialog-size-lg-width: 700px;
      --fsds-dialog-size-lg-max-width: 90vw;
      --fsds-dialog-size-xl-width: 900px;
      --fsds-dialog-size-xl-max-width: 95vw;
      --fsds-dialog-size-full-width: 100vw;
      --fsds-dialog-size-full-height: 100vh;
      --fsds-dialog-size-close-button-size: var(--fsds-core-spacing-size-08, 32px);
      --fsds-dialog-elevation-default: var(--fsds-semantic-elevation-surface-dialog, 0px 12px 16px #0000000f, 0px 25px 50px #00000026);
      --fsds-dialog-spacing-header-padding-top: var(--fsds-core-spacing-size-06, 16px);
      --fsds-dialog-spacing-body-padding-right: var(--fsds-core-spacing-size-07, 24px);
      --fsds-dialog-spacing-footer-gap: var(--fsds-core-spacing-size-03, 4px);
      --fsds-dialog-typography-title-font-size: var(--fsds-semantic-typography-heading-04, 18px);
      --fsds-dialog-typography-title-font-weight: var(--fsds-semantic-typography-font-weight-bold, 700);
      --fsds-dialog-typography-title-line-height: var(--fsds-semantic-typography-line-height-heading, 1);
    }

    .dialog__backdrop {
      --fsds-dialog-color-background-default: var(--fsds-semantic-color-overlay-scrim, #00000066);
    }

    .dialog__body {
      --fsds-dialog-color-foreground-default: var(--fsds-semantic-color-foreground-secondary, #474647);
    }

    .dialog__closeButton {
      --fsds-dialog-color-foreground-default: var(--fsds-semantic-color-foreground-secondary, #474647);
    }

    .dialog__closeButton:hover {
      --fsds-dialog-color-background-default: var(--fsds-semantic-color-background-hover, #f7f7f7);
    }

    @layer components.defaults {
    .dialog {
      padding-block-start: var(--fsds-box-model-padding-block-start, var(--fsds-semantic-surface-size-padding-block, 16px));
      padding-block-end: var(--fsds-box-model-padding-block-end, var(--fsds-semantic-surface-size-padding-block, 16px));
      padding-inline-start: var(--fsds-box-model-padding-inline-start, var(--fsds-semantic-surface-size-padding-inline, 16px));
      padding-inline-end: var(--fsds-box-model-padding-inline-end, var(--fsds-semantic-surface-size-padding-inline, 16px));
      gap: var(--fsds-box-model-gap, var(--fsds-semantic-surface-size-gap, 8px));
      width: var(--fsds-box-model-width, auto);
      min-width: var(--fsds-box-model-min-width, var(--fsds-semantic-surface-size-min-width, 64px));
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, 0);
      max-height: var(--fsds-box-model-max-height, none);
      position: fixed;
      inset: 0;
      z-index: 1000;
      display: flex;
      align-items: center;
      justify-content: center;
      pointer-events: none;

      &:has(> .dialog__modal[aria-modal="false"]) > .dialog__backdrop {
        display: none;
      }
    }

    .dialog__backdrop {
      position: absolute;
      inset: 0;
      pointer-events: auto;
    }

    .dialog__modal {
      position: relative;
      display: flex;
      flex-direction: column;
      background-color: var(--fsds-dialog-design-modal-background-fill, var(--fsds-dialog-color-background-default, #ffffff));
      color: var(--fsds-dialog-design-modal-foreground-color, var(--fsds-dialog-color-foreground-default, #141414));
      border-color: var(--fsds-dialog-design-modal-border-color, var(--fsds-dialog-color-border-default, #d0d0d0));
      border-style: var(--fsds-dialog-design-modal-border-style, solid);
      border-width: var(--fsds-dialog-design-modal-border-width, 1px);
      border-radius: var(--fsds-dialog-design-modal-shape-radius, var(--fsds-dialog-size-radius-default, 16px));
      box-shadow: var(--fsds-dialog-design-modal-elevation-shadow, var(--fsds-dialog-elevation-default, 0px 12px 16px #0000000f, 0px 25px 50px #00000026));
      width: var(--fsds-dialog-design-modal-sizing-width, var(--fsds-dialog-size-md-width, 500px));
      max-width: var(--fsds-dialog-design-modal-sizing-max-width, var(--fsds-dialog-size-md-max-width, 90vw));
      max-height: var(--fsds-dialog-design-modal-sizing-max-height, 90dvh);
      pointer-events: auto;
      box-sizing: border-box;
      overflow: hidden;
      min-width: var(--fsds-dialog-design-modal-sizing-min-width, 0);
    }

    .dialog__header {
      display: flex;
      align-items: center;
      padding-top: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-right: var(--fsds-dialog-spacing-body-padding-right, 24px);
      padding-bottom: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-left: var(--fsds-dialog-spacing-body-padding-right, 24px);
      border-bottom-color: var(--fsds-dialog-design-header-border-bottom-color, var(--fsds-dialog-color-border-default, #d0d0d0));
      border-bottom-style: var(--fsds-dialog-design-header-border-bottom-style, solid);
      border-bottom-width: var(--fsds-dialog-design-header-border-bottom-width, 1px);
      flex-shrink: 0;
    }

    .dialog__title {
      margin: 0;
      font-size: var(--fsds-dialog-design-title-typography-size, var(--fsds-dialog-typography-title-font-size, 18px));
      font-weight: var(--fsds-dialog-design-title-typography-weight, var(--fsds-dialog-typography-title-font-weight, 700));
      line-height: var(--fsds-dialog-design-title-typography-line-height, var(--fsds-dialog-typography-title-line-height, 1));
      color: var(--fsds-dialog-design-title-foreground-color, var(--fsds-dialog-color-foreground-default, #141414));
    }

    .dialog__body {
      flex: 1 1 auto;
      padding-top: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-right: var(--fsds-dialog-spacing-body-padding-right, 24px);
      padding-bottom: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-left: var(--fsds-dialog-spacing-body-padding-right, 24px);
      overflow-y: auto;
      min-width: var(--fsds-dialog-design-body-sizing-min-width, 0);
      min-height: var(--fsds-dialog-design-body-sizing-min-height, 0);
      overflow-wrap: anywhere;
    }

    .dialog__footer {
      display: flex;
      justify-content: flex-end;
      align-items: center;
      gap: var(--fsds-dialog-design-footer-spacing-gap, var(--fsds-dialog-spacing-footer-gap, 4px));
      padding-top: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-right: var(--fsds-dialog-spacing-body-padding-right, 24px);
      padding-bottom: var(--fsds-dialog-spacing-header-padding-top, 16px);
      padding-left: var(--fsds-dialog-spacing-body-padding-right, 24px);
      border-top-color: var(--fsds-dialog-design-footer-border-top-color, var(--fsds-dialog-color-border-default, #d0d0d0));
      border-top-style: var(--fsds-dialog-design-footer-border-top-style, solid);
      border-top-width: var(--fsds-dialog-design-footer-border-top-width, 1px);
      flex-shrink: 0;
    }

    .dialog__closeButton {
      position: absolute;
      top: var(--fsds-dialog-spacing-header-padding-top, 16px);
      right: var(--fsds-dialog-spacing-body-padding-right, 24px);
      width: var(--fsds-dialog-design-close-button-sizing-width, var(--fsds-dialog-size-close-button-size, 32px));
      height: var(--fsds-dialog-design-close-button-sizing-height, var(--fsds-dialog-size-close-button-size, 32px));
      display: inline-flex;
      align-items: center;
      justify-content: center;
      background-color: var(--fsds-dialog-design-close-button-background-fill, transparent);
      border: 0;
      border-radius: var(--fsds-dialog-design-close-button-shape-radius, 9999px);
      cursor: pointer;
    }

    .dialog--sm .dialog__modal {
      width: var(--fsds-dialog-design-condition-c6049c96ab74-sizing-width, var(--fsds-dialog-size-sm-width, 400px));
      max-width: var(--fsds-dialog-design-condition-c6049c96ab74-sizing-max-width, var(--fsds-dialog-size-sm-max-width, 90vw));
    }

    .dialog--lg .dialog__modal {
      width: var(--fsds-dialog-design-condition-3fb7229a17a8-sizing-width, var(--fsds-dialog-size-lg-width, 700px));
      max-width: var(--fsds-dialog-design-condition-3fb7229a17a8-sizing-max-width, var(--fsds-dialog-size-lg-max-width, 90vw));
    }

    .dialog--xl .dialog__modal {
      width: var(--fsds-dialog-design-condition-81887f72fc05-sizing-width, var(--fsds-dialog-size-xl-width, 900px));
      max-width: var(--fsds-dialog-design-condition-81887f72fc05-sizing-max-width, var(--fsds-dialog-size-xl-max-width, 95vw));
    }

    .dialog--full .dialog__modal {
      width: var(--fsds-dialog-design-condition-aa10b66155cb-sizing-width, var(--fsds-dialog-size-full-width, 100vw));
      height: var(--fsds-dialog-design-condition-aa10b66155cb-sizing-height, var(--fsds-dialog-size-full-height, 100vh));
      max-width: 100vw;
      max-height: 100vh;
      border-radius: var(--fsds-dialog-design-condition-aa10b66155cb-shape-radius, 0);
    }
    }
  `;

  override render() {
    return html`<fsds-stack variant="horizontal" class="dialog__footer"><slot></slot></fsds-stack>`;
  }
}

customElements.define('fsds-dialog-footer', DialogFooterElement);
// @generated:end

// @custom:start trailing

// @custom:end