// @generated:start imports
import { LitElement, html, css, nothing } from 'lit';
import { property } from 'lit/decorators.js';
import '../Image/Image.js';
import { ifDefined } from 'lit/directives/if-defined.js';
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
export class AvatarElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .avatar {
      --fsds-avatar-size-default: var(--fsds-core-spacing-size-06, 16px);
      --fsds-avatar-size-small: var(--fsds-core-spacing-size-06, 16px);
      --fsds-avatar-size-medium: var(--fsds-core-spacing-size-07, 24px);
      --fsds-avatar-size-large: var(--fsds-core-spacing-size-08, 32px);
      --fsds-avatar-size-extra-large: var(--fsds-core-spacing-size-09, 48px);
      --fsds-avatar-size-radius-default: var(--fsds-semantic-shape-control-radius-pill, 9999px);
      --fsds-avatar-size-border-default: var(--fsds-semantic-shape-control-border-default-width, 1px);
      --fsds-avatar-color-background-default: var(--fsds-semantic-color-background-secondary, #f7f7f7);
      --fsds-avatar-color-foreground-primary: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-avatar-color-border-default: var(--fsds-semantic-color-border-light, #b8b8b8);
      --fsds-avatar-typography-font-weight-medium: var(--fsds-core-typography-weight-medium, 500);
      --fsds-avatar-typography-font-family-sans: var(--fsds-core-typography-font-family-sans, "Inter", sans-serif);
    }

    @layer components.defaults {
    .avatar {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      flex-shrink: 0;
      box-sizing: border-box;
      padding-block-start: var(--fsds-box-model-padding-block-start, 0);
      padding-block-end: var(--fsds-box-model-padding-block-end, 0);
      padding-inline-start: var(--fsds-box-model-padding-inline-start, 0);
      padding-inline-end: var(--fsds-box-model-padding-inline-end, 0);
      gap: var(--fsds-box-model-gap, 0);
      width: var(--fsds-avatar-design-root-sizing-width, var(--fsds-avatar-size-default, 16px));
      min-width: var(--fsds-box-model-min-width, 0);
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-avatar-design-root-sizing-height, var(--fsds-avatar-size-default, 16px));
      min-height: var(--fsds-box-model-min-height, 0);
      max-height: var(--fsds-box-model-max-height, none);
      overflow: hidden;
      position: relative;
      border-radius: var(--fsds-avatar-design-root-shape-radius, var(--fsds-avatar-size-radius-default, 9999px));
      background-color: var(--fsds-avatar-design-root-background-fill, var(--fsds-avatar-color-background-default, #f7f7f7));
      color: var(--fsds-avatar-design-root-foreground-color, var(--fsds-avatar-color-foreground-primary, #141414));
      border-color: var(--fsds-avatar-design-root-border-color, var(--fsds-avatar-color-border-default, #b8b8b8));
      border-style: var(--fsds-avatar-design-root-border-style, solid);
      border-width: var(--fsds-avatar-design-root-border-width, var(--fsds-avatar-size-border-default, 1px));
      font-weight: var(--fsds-avatar-design-root-typography-weight, var(--fsds-avatar-typography-font-weight-medium, 500));
      font-family: var(--fsds-avatar-design-root-typography-family, var(--fsds-avatar-typography-font-family-sans, "Inter", sans-serif));
    }

    .avatar__image {
      width: 100%;
      height: 100%;
      object-fit: cover;
      display: block;
    }

    .avatar--small {
      width: var(--fsds-avatar-design-condition-42b522a9c46e-sizing-width, var(--fsds-avatar-size-small, 16px));
      height: var(--fsds-avatar-design-condition-42b522a9c46e-sizing-height, var(--fsds-avatar-size-small, 16px));
    }

    .avatar--medium {
      width: var(--fsds-avatar-design-condition-a9821c9eea70-sizing-width, var(--fsds-avatar-size-medium, 24px));
      height: var(--fsds-avatar-design-condition-a9821c9eea70-sizing-height, var(--fsds-avatar-size-medium, 24px));
    }

    .avatar--large {
      width: var(--fsds-avatar-design-condition-cbbd2740a3e5-sizing-width, var(--fsds-avatar-size-large, 32px));
      height: var(--fsds-avatar-design-condition-cbbd2740a3e5-sizing-height, var(--fsds-avatar-size-large, 32px));
    }

    .avatar--extra-large {
      width: var(--fsds-avatar-design-condition-ee2a0b1d0aee-sizing-width, var(--fsds-avatar-size-extra-large, 48px));
      height: var(--fsds-avatar-design-condition-ee2a0b1d0aee-sizing-height, var(--fsds-avatar-size-extra-large, 48px));
    }
    }
  `;

  @property({ type: String }) src?: string;
  @property({ type: String }) name!: string;
  @property({ type: String }) initials?: string;
  @property({ type: Boolean }) priority?: boolean;
  @property() size?: string;

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute("data-fsds-component", "avatar");
  }

  private computeClasses(): string {
    return [
      "avatar",
      this.size ? `avatar--${this.size}` : null,
    ].filter(Boolean).join(" ");
  }

  override render() {
    return html`<div class="${this.computeClasses()}" role="img" aria-label=${ifDefined(this.name)} data-fsds-box="">
  ${this.src ? html`
  <fsds-image class=${'avatar__image'} .src=${this.src} alt=""></fsds-image>
  ` : nothing}
  ${this.initials ? html`
  <span class=${'avatar__initials'}>${this.initials}</span>
  ` : nothing}
</div>`;
  }
}

customElements.define('fsds-avatar', AvatarElement);

// @generated:end

// @custom:start trailing

// @custom:end