// @generated:start imports
import { LitElement, html, css, nothing } from 'lit';
import { property } from 'lit/decorators.js';
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types

// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
export class DividerElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .divider {
      --fsds-divider-color-default: var(--fsds-semantic-color-border-light, #b8b8b8);
      --fsds-divider-size-thickness: var(--fsds-semantic-shape-control-border-default-width, 1px);
      --fsds-divider-spacing-margin: var(--fsds-core-spacing-size-04, 8px);
    }

    @layer components.defaults {
    .divider {
      padding-block-start: var(--fsds-box-model-padding-block-start, 0);
      padding-block-end: var(--fsds-box-model-padding-block-end, 0);
      padding-inline-start: var(--fsds-box-model-padding-inline-start, 0);
      padding-inline-end: var(--fsds-box-model-padding-inline-end, 0);
      gap: var(--fsds-box-model-gap, var(--fsds-semantic-display-size-gap, 4px));
      width: 100%;
      min-width: var(--fsds-box-model-min-width, 0);
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, 0);
      max-height: var(--fsds-box-model-max-height, none);
      display: block;
      border-right-style: none;
      border-bottom-style: var(--fsds-divider-design-root-border-bottom-style, none);
      border-left-style: none;
      border-top-color: var(--fsds-divider-design-root-border-top-color, var(--fsds-divider-color-default, #b8b8b8));
      border-top-style: var(--fsds-divider-design-root-border-top-style, solid);
      border-top-width: var(--fsds-divider-design-root-border-top-width, var(--fsds-divider-size-thickness, 1px));
      margin-top: var(--fsds-divider-spacing-margin, 8px);
      margin-bottom: var(--fsds-divider-spacing-margin, 8px);
    }

    .divider--vertical {
      width: 1px;
      height: auto;
      align-self: stretch;
      min-height: 1em;
      border-top: none;
      border-left-color: var(--fsds-divider-color-default, #b8b8b8);
      border-left-style: solid;
      border-left-width: var(--fsds-divider-size-thickness, 1px);
      margin-top: 0;
      margin-bottom: 0;
      margin-left: var(--fsds-divider-spacing-margin, 8px);
      margin-right: var(--fsds-divider-spacing-margin, 8px);
    }
    }
  `;

  @property({ attribute: false }) orientation?: "horizontal" | "vertical";
  @property({ type: Boolean }) decorative?: boolean;
  @property({ type: String }) thickness?: string;

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute("data-fsds-component", "divider");
  }

  private computeClasses(): string {
    return [
      "divider",
      this.orientation ? `divider--${this.orientation}` : null,
    ].filter(Boolean).join(" ");
  }

  override render() {
    return html`<hr class="${this.computeClasses()}" role="separator" data-fsds-box="" />`;
  }
}

customElements.define('fsds-divider', DividerElement);

// @generated:end

// @custom:start trailing

// @custom:end