/**
 * Angular lowering for the shared layout primitive (Stack).
 *
 * Generates `primitives/Stack.component.ts` from the framework-neutral
 * `PrimitiveIR`. All layout facts (class prefix, display map, axis map,
 * token-driven gap) come from the IR; this emitter only knows how to render
 * them as an Angular standalone component using reactive host classes and layered styles. There
 * is no Stack-specific branching.
 */
import type { PrimitiveIR } from "../../primitive-contract.js";

/**
 * Banner marking the primitive as whole-file generated output. Unlike
 * components, the primitive is not preserve-merged — it is regenerated
 * byte-for-byte from the contract, so a plain leading comment is enough.
 */
const BANNER =
  "// @generated by ds-codegen from primitives/Stack.primitive.json — do not edit by hand.";

export function generateAngularStackPrimitiveSource(ir: PrimitiveIR): string {
  const block = `fsds-${ir.layout.classPrefix}`;
  const variants = Object.keys(ir.layout.axisByVariant);
  const modes = Object.keys(ir.layout.displayByMode);
  const defaultVariant =
    (ir.props.find((p) => p.kind === "layoutVariant")?.default as string) ??
    variants[0];
  const defaultMode =
    (ir.props.find((p) => p.kind === "layoutMode")?.default as string) ??
    modes[0];

  const variantUnion = variants.map((v) => `"${v}"`).join(" | ");
  const modeUnion = modes.map((m) => `"${m}"`).join(" | ");

  // Classes remain reactive host bindings; primitive style facts participate
  // in the same layer order as component defaults and consumer overrides.
  const rules = Object.entries(ir.layout.displayByMode)
    .filter(([, display]) => display !== null)
    .map(([mode, display]) => `:host(.${block}--layout-${mode}) { display: ${display}; }`);
  for (const mode of ir.axisModes) {
    if (ir.layout.gap) rules.push(`:host(.${block}--layout-${mode}) { gap: var(${ir.layout.gap.cssVar}, 0); }`);
    for (const [variant, axis] of Object.entries(ir.layout.axisByVariant)) {
      rules.push(`:host(.${block}--layout-${mode}.${block}--${variant}) { flex-direction: ${axis}; }`);
    }
  }
  const primitiveStyles = `@layer components.primitive {\n${rules.join("\n")}\n}`;

  return `${BANNER}
import {
  Component,
  Input,
  ChangeDetectionStrategy,
  HostBinding,
} from "@angular/core";

/**
 * Stack — the single layout primitive for Full Stack DS (Angular).
 *
 * All generated components render inside a <${block}> so that layout
 * direction and semantic element are declared in one place.
 *
 * \`role\` is forwarded to the host element via @HostBinding so that
 * generated components emitting \`<${block} role="...">\` get correct
 * accessibility semantics (e.g. \`getByRole('switch')\` resolves to the
 * ${block} host).
 *
 * \`as\` is accepted as a typed input, mirroring the Vue / Svelte Stack
 * API. Angular custom-element selectors are fixed (the host element is
 * always \`<${block}>\`), so the \`as\` value is currently advisory only:
 * downstream tooling can read it, but the rendered tag does not change.
 * Replacing this with a real semantic-element re-target requires either
 * an attribute-selector Stack or per-tag *ngSwitch wrapping; neither is
 * worth the churn until the generated components have render tests
 * exercising the difference.
 */
@Component({
  selector: "${block}",
  standalone: true,
  imports: [],
  template: \`<ng-content />\`,
  styles: [\`${primitiveStyles}\`],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ${ir.name}Component {
  @Input() variant: ${variantUnion} = "${defaultVariant}";
  @Input() layout: ${modeUnion} = "${defaultMode}";
  @Input() className?: string;
  @Input() as?: keyof HTMLElementTagNameMap;
  @Input() role?: string;

  @HostBinding("class")
  get hostClass(): string {
    return ["${block}", \`${block}--layout-\${this.layout}\`, \`${block}--\${this.variant}\`, this.className]
      .filter(Boolean)
      .join(" ");
  }

  @HostBinding("attr.role")
  get hostRole(): string | null {
    return this.role ?? null;
  }
}
`;
}
