# CAWS-MANAGED-HOOK
# hook_pack: shared
# hook_pack_version: 87
# caws_min_major: 11
# lineage_refs: 1,4,6,8,11,12,13,16,17,19,22,23,24,25,26,27,28,29,30,31
# edit_stance: GENERATED PROJECTION. Edit packages/caws-cli/surfaces/registry.json
#   and regenerate; caws init preserves local projection drift for manual reconciliation.
# @generated — DO NOT EDIT.
# Source: packages/caws-cli/surfaces/registry.json (version 1).
# Regenerated by scripts/generate-surface-registry.mjs (CAWS-DESIGN-GLOBAL-IDENTITY-HOME-001 A5).
_caws_surface_vendor_dir() {
  case "${1:-}" in
    claude-code) printf '%s\n' '.claude' ;;
    codex) printf '%s\n' '.codex' ;;
    opencode) printf '%s\n' '.opencode' ;;
    zcode) printf '%s\n' '.zcode' ;;
    kimi-code) printf '%s\n' '.kimi-code' ;;
    qwen-code) printf '%s\n' '.qwen' ;;
    dsh) printf '%s\n' '.dsh' ;;
    cursor) printf '%s\n' '.cursor' ;;
    windsurf) printf '%s\n' '.windsurf' ;;
    none) printf '%s\n' '.caws' ;;
    *) return 1 ;;
  esac
}
_caws_surface_pin_var() {
  case "${1:-}" in
    claude-code) printf '%s\n' 'CLAUDE_SESSION_ID' ;;
    codex) printf '%s\n' 'CODEX_THREAD_ID' ;;
    qwen-code) printf '%s\n' 'QWEN_CODE_SESSION_ID' ;;
    dsh) printf '%s\n' 'DSH_SESSION_ID' ;;
    *) return 1 ;;
  esac
}
_caws_surface_env_vars() {
  case "${1:-}" in
    claude-code) printf '%s\n' 'CLAUDE_SESSION_ID CLAUDE_CODE_SESSION_ID' ;;
    codex) printf '%s\n' 'CODEX_THREAD_ID' ;;
    qwen-code) printf '%s\n' 'QWEN_CODE_SESSION_ID' ;;
    dsh) printf '%s\n' 'DSH_SESSION_ID' ;;
    cursor) printf '%s\n' 'CURSOR_TRACE_ID' ;;
    *) return 1 ;;
  esac
}
