/**
 * Generated glyph catalog emission for Jetpack Compose — the Kotlin twin of
 * the SwiftUI catalog (swift/swiftui/icon-glyph.ts). Reads the iconography
 * corpus (packages/ds-iconography/icons/*.icon.json) and emits
 * FsdsGlyphCatalog.kt next to the committed FsdsSvgPath runtime: one data
 * table (name → grid variants with viewBox + stroke paths) plus the
 * `glyph(named, size, tint)` registry every iconGlyph-bearing surface
 * composes. The catalog is a SHARED SUBSTRATE, like FsdsTheme — icon parts
 * lower through the same registry by iconGlyph fact, never by emitting
 * their own glyph copies.
 *
 * Size policy mirrors swift: the catalog authors 16/24 grids; the size
 * hint maps to the rendered frame, the nearest authored grid ≤ the frame
 * renders, and the renderer scales to frame.
 *
 * Rides the CLI's primitives channel (writeWebPrimitives writes to the
 * package's `primitives/` root; `../glyph/` puts it beside FsdsSvgPath).
 */
import fs from "node:fs";
import path from "node:path";
import type { GeneratedFile } from "../../emitter.js";

interface IconPathSpec {
  d: string;
  strokeWidth?: number;
}

interface IconVariantSpec {
  name: string;
  width: number;
  height: number;
  viewBox: string;
  paths: IconPathSpec[];
}

interface IconSpec {
  name: string;
  decorativeDefault: boolean;
  variants: Record<string, IconVariantSpec>;
}

function loadIconCatalog(): IconSpec[] {
  const repoRoot = process.cwd();
  const iconsDir = path.resolve(repoRoot, "packages", "ds-iconography", "icons");
  if (!fs.existsSync(iconsDir)) return [];
  const specs: IconSpec[] = [];
  for (const entry of fs.readdirSync(iconsDir).sort()) {
    const file = path.join(iconsDir, entry, `${entry}.icon.json`);
    if (!fs.existsSync(file)) continue;
    const raw = JSON.parse(fs.readFileSync(file, "utf8")) as {
      name?: string;
      semantics?: { decorativeDefault?: boolean };
      variants?: Record<string, IconVariantSpec>;
    };
    if (!raw.name || !raw.variants) continue;
    specs.push({
      name: raw.name,
      decorativeDefault: raw.semantics?.decorativeDefault ?? true,
      variants: raw.variants,
    });
  }
  return specs;
}

/** Kotlin string literal with escaping (backslashes, quotes, dollars). */
function kotlinLiteral(value: string): string {
  return `"${value.replaceAll("\\", "\\\\").replaceAll("$", "\\$").replaceAll('"', '\\"')}"`;
}

export function generateComposeGlyphCatalogFile(): GeneratedFile | null {
  const icons = loadIconCatalog();
  if (icons.length === 0) return null;
  const lines: string[] = [];
  lines.push(
    `// @generated by ds-codegen from packages/ds-iconography — do not edit by hand.`,
  );
  lines.push(`package com.fullstackds.glyph`);
  lines.push(``);
  lines.push(`import androidx.compose.foundation.layout.Box`);
  lines.push(`import androidx.compose.foundation.layout.size`);
  lines.push(`import androidx.compose.runtime.Composable`);
  lines.push(`import androidx.compose.runtime.remember`);
  lines.push(`import androidx.compose.ui.Modifier`);
  lines.push(`import androidx.compose.ui.draw.drawBehind`);
  lines.push(`import androidx.compose.ui.geometry.Offset`);
  lines.push(`import androidx.compose.ui.graphics.Color`);
  lines.push(`import androidx.compose.ui.graphics.Path`);
  lines.push(`import androidx.compose.ui.graphics.PathEffect`);
  lines.push(`import androidx.compose.ui.graphics.StrokeCap`);
  lines.push(`import androidx.compose.ui.graphics.StrokeJoin`);
  lines.push(`import androidx.compose.ui.graphics.drawscope.Stroke`);
  lines.push(`import androidx.compose.ui.graphics.drawscope.scale`);
  lines.push(`import androidx.compose.ui.unit.Dp`);
  lines.push(`import androidx.compose.ui.unit.dp`);
  lines.push(``);
  lines.push(`// @generated:start catalog`);
  lines.push(`/** One stroked path of a glyph variant, in viewBox coordinates. */`);
  lines.push(`class FsdsGlyphStroke(val d: String, val width: Float)`);
  lines.push(``);
  lines.push(`/** One authored grid variant of a glyph. */`);
  lines.push(`class FsdsGlyphVariant(val viewBox: Float, val paths: List<FsdsGlyphStroke>)`);
  lines.push(``);
  lines.push(`object FsdsGlyphCatalog {`);
  lines.push(`    val variants: Map<String, Map<Int, FsdsGlyphVariant>> = mapOf(`);
  for (const icon of icons) {
    lines.push(`        ${kotlinLiteral(icon.name)} to mapOf(`);
    for (const [key, variant] of Object.entries(icon.variants)) {
      const vb = variant.viewBox.split(" ").map(Number);
      lines.push(`            ${key} to FsdsGlyphVariant(`);
      lines.push(`                viewBox = ${vb[2]}f,`);
      lines.push(`                paths = listOf(`);
      for (const p of variant.paths) {
        lines.push(
          `                    FsdsGlyphStroke(d = ${kotlinLiteral(p.d)}, width = ${p.strokeWidth ?? 1.5}f),`,
        );
      }
      lines.push(`                ),`);
      lines.push(`            ),`);
    }
    lines.push(`        ),`);
  }
  lines.push(`    )`);
  lines.push(``);
  lines.push(`    /** Decorative-by-default flags from the catalog semantics. */`);
  lines.push(`    val decorativeDefaults: Set<String> = setOf(`);
  for (const icon of icons.filter((i) => i.decorativeDefault)) {
    lines.push(`        ${kotlinLiteral(icon.name)},`);
  }
  lines.push(`    )`);
  lines.push(``);
  lines.push(`    /** Registry lookup every iconGlyph surface composes: the nearest`);
  lines.push(`     *  authored grid ≤ the requested size renders and scales to frame. */`);
  lines.push(`    fun variant(named: String, size: Dp): FsdsGlyphVariant? {`);
  lines.push(`        val byGrid = variants[named] ?: return null`);
  lines.push(`        if (byGrid.isEmpty()) return null`);
  lines.push(`        val grids = byGrid.keys.sorted()`);
  lines.push(`        val grid = grids.lastOrNull { it <= size.value } ?: grids.first()`);
  lines.push(`        return byGrid[grid]`);
  lines.push(`    }`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`/**`);
  lines.push(` * Painted glyph renderer: parses the variant's stroke paths through the`);
  lines.push(` * committed FsdsSvgPath runtime and strokes them scaled to the frame.`)
  lines.push(` * Stroke inherits the tint (the currentColor analog); unknown names`);
  lines.push(` * render a dashed placeholder so a typo surfaces instead of silently`);
  lines.push(` * disappearing. Decorative semantics belong to the composing surface.`);
  lines.push(` */`);
  lines.push(`@Composable`);
  lines.push(`fun FsdsGlyphIcon(`);
  lines.push(`    named: String,`);
  lines.push(`    size: Dp,`);
  lines.push(`    tint: Color,`);
  lines.push(`    modifier: Modifier = Modifier,`);
  lines.push(`) {`);
  lines.push(`    val variant = FsdsGlyphCatalog.variant(named, size)`);
  lines.push(`    val strokes: List<Pair<Path, Float>> = remember(named, variant) {`);
  lines.push(`        variant?.paths?.map { stroke ->`);
  lines.push(`            FsdsSvgPath.parse(stroke.d) to stroke.width`);
  lines.push(`        } ?: emptyList()`);
  lines.push(`    }`);
  lines.push(`    Box(`);
  lines.push(`        modifier.size(size).drawBehind {`);
  lines.push(`            if (variant == null) {`);
  lines.push(`                drawRoundRect(`);
  lines.push(`                    color = tint,`);
  lines.push(`                    topLeft = Offset.Zero,`);
  lines.push(`                    size = this.size,`);
  lines.push(`                    style = Stroke(`);
  lines.push(`                        width = 1f,`);
  lines.push(`                        pathEffect = PathEffect.dashPathEffect(floatArrayOf(2f, 2f)),`);
  lines.push(`                    ),`);
  lines.push(`                )`);
  lines.push(`                return@drawBehind`);
  lines.push(`            }`);
  lines.push(`            val glyphScale = this.size.minDimension / variant.viewBox`);
  lines.push(`            scale(glyphScale, pivot = Offset.Zero) {`);
  lines.push(`                for ((p, w) in strokes) {`);
  lines.push(`                    drawPath(`);
  lines.push(`                        path = p,`);
  lines.push(`                        color = tint,`);
  lines.push(`                        style = Stroke(`);
  lines.push(`                            width = w,`);
  lines.push(`                            cap = StrokeCap.Round,`);
  lines.push(`                            join = StrokeJoin.Round,`);
  lines.push(`                        ),`);
  lines.push(`                    )`);
  lines.push(`                }`);
  lines.push(`            }`);
  lines.push(`        },`);
  lines.push(`    )`);
  lines.push(`}`);
  lines.push(`// @generated:end`);
  return {
    relativePath: "../glyph/FsdsGlyphCatalog.kt",
    contents: lines.join("\n") + "\n",
  };
}
