/**
 * Lit lowering for the shared layout primitive (Stack).
 *
 * Generates `primitives/Stack.ts` from the framework-neutral `PrimitiveIR`.
 * Lit reflects `layout`/`variant` as host attributes (`reflect: true`), so
 * layout facts lower to `:host([layout="..."])` / `:host([variant="..."])`
 * attribute-selector rules inside `static styles`, not class names. All
 * layout facts (class prefix's role, display map, axis map, token-driven
 * gap) come from the IR; this emitter only knows how to render them as a
 * LitElement + tagged-template CSS. There is no Stack-specific branching.
 */
import type { PrimitiveIR } from "../../primitive-contract.js";

/**
 * Banner marking the primitive as whole-file generated output. Unlike
 * components, the primitive is not preserve-merged — it is regenerated
 * byte-for-byte from the contract, so a plain leading comment is enough.
 */
const BANNER =
  "// @generated by ds-codegen from primitives/Stack.primitive.json — do not edit by hand.";

/** Custom element tag name (e.g. Stack -> "fsds-stack"). */
function elementTag(ir: PrimitiveIR): string {
  return `fsds-${ir.name.toLowerCase()}`;
}

export function generateLitStackPrimitiveSource(ir: PrimitiveIR): string {
  const tag = elementTag(ir);
  const variants = Object.keys(ir.layout.axisByVariant);
  const modes = Object.keys(ir.layout.displayByMode);
  const defaultVariant =
    (ir.props.find((p) => p.kind === "layoutVariant")?.default as string) ??
    variants[0];
  const defaultMode =
    (ir.props.find((p) => p.kind === "layoutMode")?.default as string) ??
    modes[0];

  const variantUnion = variants.map((v) => `"${v}"`).join(" | ");
  const modeUnion = modes.map((m) => `"${m}"`).join(" | ");

  const baseDecls = ["box-sizing: border-box;"];
  if (ir.layout.gap) {
    baseDecls.push(`gap: var(${ir.layout.gap.cssVar});`);
  }

  const hostRules: string[] = [];
  for (const [mode, display] of Object.entries(ir.layout.displayByMode)) {
    if (display === null) continue;
    hostRules.push(
      `    :host([layout="${mode}"]) {\n      display: ${display};\n    }`,
    );
  }
  for (const [variant, axis] of Object.entries(ir.layout.axisByVariant)) {
    hostRules.push(
      `    :host([variant="${variant}"]) {\n      flex-direction: ${axis};\n    }`,
    );
  }

  return `${BANNER}
import { LitElement, html, css } from "lit";
import { property } from "lit/decorators.js";

/**
 * Stack layout primitive for Full Stack DS Lit components.
 *
 * Provides a layout container that maps to the contract-driven Stack
 * primitive used across all framework targets. The host element carries
 * BEM class names applied by the enclosing component; the Stack element
 * itself is transparent to layout via \`display: contents\`.
 *
 * \`role\` is reflected to the host attribute via attributeChangedCallback
 * (Lit's reflect: true) so that generated components emitting
 * \`<fsds-stack role="...">\` get correct accessibility semantics.
 *
 * \`as\` is accepted as a typed property mirroring the Vue / Svelte Stack
 * API. Custom-element tag names are fixed (the host is always
 * \`<fsds-stack>\`), so the \`as\` value is advisory only — the rendered tag
 * does not change. Real semantic-element re-target requires Lit's
 * \`unsafeStatic\` or a per-tag render branch; deferred until generated
 * Lit components have render tests exercising the difference.
 */
export class ${ir.name}Element extends LitElement {
  static styles = css\`
    :host {
      ${baseDecls.join("\n      ")}
    }

${hostRules.join("\n\n")}
  \`;

  @property({ type: String, reflect: true })
  variant: ${variantUnion} = "${defaultVariant}";

  @property({ type: String, reflect: true })
  layout: ${modeUnion} = "${defaultMode}";

  @property({ type: String, reflect: true })
  override role: string | null = null;

  @property({ type: String })
  as?: keyof HTMLElementTagNameMap;

  render() {
    return html\`<slot></slot>\`;
  }
}

customElements.define("${tag}", ${ir.name}Element);
`;
}
