// Hand-authored TypeScript mirror of the closed analytical schemas — the
// presentation-side twin of the governed sources. NOT authoritative:
//   structure  -> packages/ds-contracts/relation.contract.schema.json
//   assertions -> packages/ds-contracts/analytical-fixtures/assertion.schema.json
//   fixture    -> packages/ds-contracts/analytical-fixtures/fixture.schema.json
// All three are emitted from packages/ds-codegen/src/analytical/relation-model.ts.
// If the model changes, update this mirror in the same slice that changes it.
// fixtures.ts (the dump) is generated by scripts/sync-analytical-fixtures.mjs;
// this file is the only hand-written module in the directory.

// ---- relational structure (relation.contract.schema.json) -----------------

/** Admissible-transformation class (Stevens). */
export type Transformation = "nominal" | "ordinal" | "interval" | "ratio";

export interface UnitSpec {
  units?: string[];
  perRow?: boolean;
  /** Units convertible into the field's base unit. */
  conversions?: string[];
}

export interface Temporality {
  kind: "instant" | "interval";
  /** The grain the field's values are resolved to; members are earned per case. */
  grain?: "day" | "month";
}

export type Additivity =
  | { kind: "additive" }
  | { kind: "semi-additive"; nonAdditiveAlong: string[] }
  /** Admits no summation along any dimension. */
  | { kind: "non-additive" }
  | { kind: "ratio-measure" };

export interface Permits {
  null?: true;
  uncertainty?: true;
}

export interface FieldDef {
  transformation: Transformation;
  /** Values wrap around: a linear mean is meaningless. */
  cyclic?: true;
  /** Claims to be a proportion of a whole; the whole must be declared. */
  proportion?: true;
  /** Claims to be an index rebased to a base; the base must be declared. */
  index?: true;
  key?: boolean;
  unit?: UnitSpec;
  temporality?: Temporality;
  whole?: "fixed" | { perRow: string };
  base?: true;
  additivity?: Additivity;
  permits?: Permits;
}

/** L3: a typed operator whose result is itself a relation. */
export type Derivation =
  | { kind: "aggregate-to-grain"; from: string; toGrain: string[] }
  | { kind: "join"; from: string; with: string; cardinality: "one-to-one" | "one-to-many" | "many-to-one" | "many-to-many" }
  | { kind: "nest"; from: string; levels: string[] }
  | { kind: "bin"; from: string; field: string; closure?: "left-closed" | "right-closed" }
  | { kind: "normalize"; from: string; field: string }
  | { kind: "project"; from: string; keep: string[] }
  | {
      kind: "graph";
      from: string;
      edgeFrom: string;
      edgeTo: string;
      value?: string;
      /** A requirement on the derivation, never a record that anything checked it. */
      requiresConservation?: true;
    };

export interface RelationDef {
  grain: "unknown" | string[];
  fields: Record<string, FieldDef>;
  /** Present iff this relation is the result of a derivation. */
  derivedBy?: Derivation;
}

export interface RelationStructure {
  relations: Record<string, RelationDef>;
  /** Sets of relations declared to carry the same claim about one authority. */
  peers?: string[][];
}

// ---- assertions (assertion.schema.json, L0-L2 grammar) --------------------

export type Assertion =
  | {
      kind: "aggregate";
      relation: string;
      field: string;
      op: "sum" | "mean" | "count" | "min";
      along?: string[];
      nulls?: "exclude" | "as-zero" | "as-observed";
      uncertainty?: "propagate";
    }
  | { kind: "ratio-comparison"; relation: string; field: string };

// ---- evidence (fixture.schema.json definitions) ---------------------------

/**
 * `censored`: a bound, not a measurement. `suppressed`: withheld by policy, so
 * a value exists and is not zero. `absent`: any other missing kind.
 */
export type NullKind = "absent" | "censored" | "suppressed";

/** One observation: a bare primitive or the qualified object form. */
export type Observation =
  | number
  | string
  | boolean
  | {
      value?: number | string | boolean;
      unit?: string;
      null?: NullKind;
    };

export interface Evidence {
  /** relation name -> one row object per grain member, field -> observation. */
  rows?: Record<string, Record<string, Observation>[]>;
  /** relation name -> the fields that jointly identify one grain member. */
  grainWitness?: Record<string, string[]>;
}

// ---- the fixture itself (fixture.schema.json) -----------------------------

export interface AnalyticalFixture {
  id: string;
  structure: RelationStructure;
  assertions: Assertion[];
  evidence?: Evidence;
}
