// Hand-authored TypeScript mirror of the closed analytical schemas — the
// presentation-side twin of the governed sources. NOT authoritative:
//   structure  -> packages/ds-contracts/relation.contract.schema.json
//   assertions -> packages/ds-contracts/analytical-fixtures/assertion.schema.json
//   fixture    -> packages/ds-contracts/analytical-fixtures/fixture.schema.json
// If a schema changes, update this mirror in the same slice that changes it.
// fixtures.ts (the dump) is generated by scripts/sync-analytical-fixtures.mjs;
// this file is the only hand-written module in the directory.

// ---- relational structure (relation.contract.schema.json) -----------------

export type ScaleName =
  | "nominal"
  | "ordinal"
  | "cyclic"
  | "interval"
  | "ratio"
  | "count"
  | "proportion"
  | "index";

export type FieldShape = "scalar" | "interval" | "set" | "distribution" | "point";

export type Dimension =
  | "currency"
  | "time"
  | "length"
  | "mass"
  | "temperature"
  | "dimensionless";

export interface OrderSpec {
  kind: "total" | "partial";
  values?: Array<string | number>;
}

export interface UnitSpec {
  dimension: Dimension;
  unit?: string;
  units?: string[];
  perRow?: boolean;
  conversions?: Record<string, number>;
  rate?: { numerator: Dimension; denominator: Dimension };
}

export interface Temporality {
  kind: "instant" | "interval" | "duration";
  closure?: "half-open" | "closed" | "open";
  grain?: "second" | "minute" | "hour" | "day" | "week" | "month" | "quarter" | "year";
  calendar?: string;
}

export type Additivity =
  | { kind: "additive" }
  | { kind: "semi-additive"; nonAdditiveAlong: string[] }
  | { kind: "non-additive" }
  | { kind: "ratio-measure"; numerator: string; denominator: string };

export type NullKind =
  | "absent"
  | "not-applicable"
  | "censored"
  | "suppressed"
  | "unknown"
  | "missing-after-join";

export type ProvenanceKind = "observed" | "derived" | "imputed" | "layout-generated";

export type UncertaintyKind =
  | "none"
  | "interval"
  | "distribution"
  | "measurement-error"
  | "rounded";

export interface Permits {
  null?: NullKind[];
  provenance?: ProvenanceKind[];
  uncertainty?: UncertaintyKind[];
}

export interface FieldDef {
  scale: ScaleName;
  shape?: FieldShape;
  key?: boolean;
  unit?: UnitSpec;
  temporality?: Temporality;
  order?: OrderSpec;
  period?: number;
  whole?: string | { perRow: string };
  base?: string;
  additivity?: Additivity;
  permits?: Permits;
}

export interface RelationDef {
  grain: "unknown" | string[];
  fields: Record<string, FieldDef>;
}

export interface RefDef {
  relation: string;
  field: string;
}

export interface RelationshipDef {
  from: RefDef;
  to: RefDef;
  cardinality: "one-to-one" | "one-to-many" | "many-to-one" | "many-to-many";
}

export interface RelationStructure {
  relations: Record<string, RelationDef>;
  relationships?: RelationshipDef[];
}

// ---- assertions (assertion.schema.json, L0-L2 grammar) --------------------

export type Assertion =
  | {
      kind: "aggregate";
      relation: string;
      field: string;
      op: "sum" | "mean" | "count" | "min" | "max";
      along?: string[];
      nulls?: "exclude" | "as-zero" | "as-observed";
      uncertainty?: "propagate" | "drop";
    }
  | { kind: "ratio-comparison"; relation: string; field: string }
  | {
      kind: "rollup";
      relation: string;
      field: string;
      toGrain: string[];
      op: "sum" | "mean" | "rederive";
    };

// ---- evidence (fixture.schema.json definitions) ---------------------------

export interface UncertaintySpec {
  kind: UncertaintyKind;
  error?: number;
  low?: number;
  high?: number;
  level?: number;
}

/** One observation: a bare primitive or the qualified object form. */
export type Observation =
  | number
  | string
  | boolean
  | {
      value?: number | string | boolean;
      unit?: string;
      null?: NullKind;
      provenance?: ProvenanceKind;
      uncertainty?: UncertaintySpec;
    };

export interface Evidence {
  /** relation name -> one row object per grain member, field -> observation. */
  rows?: Record<string, Record<string, Observation>[]>;
  /** relation name -> the fields that jointly identify one grain member. */
  grainWitness?: Record<string, string[]>;
}

// ---- the fixture itself (fixture.schema.json) -----------------------------

export interface AnalyticalFixture {
  id: string;
  structure: RelationStructure;
  assertions: Assertion[];
  evidence?: Evidence;
}
