// @generated:start imports
import { LitElement, html, css, nothing } from 'lit';
import { property } from 'lit/decorators.js';
import { ifDefined } from 'lit/directives/if-defined.js';
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type LinkTarget = "_self" | "_blank" | "_parent" | "_top";
export type LinkSize = "small" | "medium" | "large";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
export class LinksElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .links {
      --fsds-links-color-foreground-default: var(--fsds-semantic-color-foreground-link, #d92d2e);
      --fsds-links-color-foreground-hover: var(--fsds-semantic-color-foreground-link-hover, #b31b1b);
      --fsds-links-color-foreground-visited: var(--fsds-semantic-color-foreground-link-visited, #e55b5a);
      --fsds-links-color-foreground-disabled: var(--fsds-semantic-color-foreground-disabled, #727272);
      --fsds-links-color-underline-default: var(--fsds-semantic-color-border-light, #b8b8b8);
      --fsds-links-spacing-gap-default: var(--fsds-core-spacing-size-02, 2px);
      --fsds-links-motion-duration-fast: var(--fsds-core-motion-duration-short, 150ms);
      --fsds-links-focus-ring-width: var(--fsds-semantic-focus-ring-width, 2px);
      --fsds-links-focus-ring-color: var(--fsds-semantic-focus-ring-color, #0566fe);
      --fsds-links-focus-ring-style: var(--fsds-semantic-focus-ring-style, solid);
      --fsds-links-focus-ring-offset: var(--fsds-semantic-focus-ring-offset, 2px);
      --fsds-links-focus-ring-radius: var(--fsds-semantic-shape-radius-small, 4px);
      --fsds-links-size-font-size-small: var(--fsds-core-typography-ramp-3, 0.875rem);
      --fsds-links-size-font-size-medium: var(--fsds-core-typography-ramp-4, 1rem);
      --fsds-links-size-font-size-large: var(--fsds-core-typography-ramp-5, 1.125rem);
    }

    .links--small {
      --fsds-links-size-font-size-medium: var(--fsds-links-size-font-size-small, 0.875rem);
    }

    .links--medium {
      --fsds-links-size-font-size-medium: var(--fsds-core-typography-ramp-4, 1rem);
    }

    .links--large {
      --fsds-links-size-font-size-medium: var(--fsds-links-size-font-size-large, 1.125rem);
    }

    @layer components.defaults {
    .links {
      padding-block-start: var(--fsds-box-model-padding-block-start, 0);
      padding-block-end: var(--fsds-box-model-padding-block-end, 0);
      padding-inline-start: var(--fsds-box-model-padding-inline-start, 0);
      padding-inline-end: var(--fsds-box-model-padding-inline-end, 0);
      gap: var(--fsds-links-design-root-spacing-gap, var(--fsds-links-spacing-gap-default, 2px));
      width: var(--fsds-box-model-width, auto);
      min-width: var(--fsds-box-model-min-width, 0);
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, 0);
      max-height: var(--fsds-box-model-max-height, none);
      color: var(--fsds-links-design-root-foreground-color, var(--fsds-links-color-foreground-default, #d92d2e));
      font-size: var(--fsds-links-design-root-typography-size, var(--fsds-links-size-font-size-medium, 1rem));
      text-decoration-color: var(--fsds-links-color-underline-default, #b8b8b8);
      text-decoration-line: underline;
      text-underline-offset: 2px;
      transition-property: color, text-decoration-color;
      transition-duration: var(--fsds-links-design-root-motion-duration, var(--fsds-links-motion-duration-fast, 150ms));
      cursor: pointer;

      &:hover:not([aria-disabled="true"]) {
        color: var(--fsds-links-design-hover-foreground-color, var(--fsds-links-color-foreground-hover, #b31b1b));
        text-decoration-color: var(--fsds-links-color-foreground-hover, #b31b1b);
      }

      &:visited {
        color: var(--fsds-links-design-visited-foreground-color, var(--fsds-links-color-foreground-visited, #e55b5a));
      }

      &[aria-disabled="true"] {
        color: var(--fsds-links-design-disabled-foreground-color, var(--fsds-links-color-foreground-disabled, #727272));
        cursor: not-allowed;
        text-decoration-line: none;
        pointer-events: none;
      }

      &:focus-visible:not([aria-disabled="true"]) {
        outline-width: var(--fsds-links-design-focus-focus-width, var(--fsds-links-focus-ring-width, 2px));
        outline-color: var(--fsds-links-design-focus-focus-color, var(--fsds-links-focus-ring-color, #0566fe));
        outline-style: var(--fsds-links-design-focus-focus-style, var(--fsds-links-focus-ring-style, solid));
        outline-offset: var(--fsds-links-design-focus-focus-offset, var(--fsds-links-focus-ring-offset, 2px));
        border-radius: var(--fsds-links-design-focus-shape-radius, var(--fsds-links-focus-ring-radius, 4px));
      }
    }

    .links--small {
      font-size: var(--fsds-links-design-condition-42b522a9c46e-typography-size, var(--fsds-links-size-font-size-medium, 1rem));
    }

    .links--medium {
      font-size: var(--fsds-links-design-condition-a9821c9eea70-typography-size, var(--fsds-links-size-font-size-medium, 1rem));
    }

    .links--large {
      font-size: var(--fsds-links-design-condition-cbbd2740a3e5-typography-size, var(--fsds-links-size-font-size-medium, 1rem));
    }
    }
  `;

  @property({ type: String }) href?: string;
  @property({ type: String }) target?: LinkTarget;
  @property({ type: String }) rel?: string;
  @property({ type: String }) size?: LinkSize;
  @property({ type: Boolean }) disabled?: boolean;

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute("data-fsds-component", "links");
  }

  private computeClasses(): string {
    return [
      "links",
      this.size ? `links--${this.size}` : null,
      this.disabled ? "links--disabled" : null,
    ].filter(Boolean).join(" ");
  }

  override render() {
    return html`<a class="${this.computeClasses()}" href=${ifDefined(this.href)} target=${ifDefined(this.target)} rel=${ifDefined(this.rel)} data-fsds-box="">
  <slot></slot>
</a>`;
  }
}

customElements.define('fsds-links', LinksElement);

// @generated:end

// @custom:start trailing

// @custom:end