// @generated:start imports
import { LitElement, html, css, nothing } from 'lit';
import { property } from 'lit/decorators.js';
import '../Button/Button.js';
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type AlertIntent = "info" | "success" | "warning" | "danger";
export type AlertLevel = "inline" | "section" | "page";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
export class AlertElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .alert {
      --fsds-alert-color-background-primary: var(--fsds-semantic-color-background-primary, #ffffff);
      --fsds-alert-color-foreground-primary: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-alert-color-border-primary: var(--fsds-semantic-color-border-primary, #a0a0a1);
      --fsds-alert-size-padding: var(--fsds-core-spacing-size-06, 16px);
      --fsds-alert-size-radius: var(--fsds-semantic-shape-control-radius-default, 6px);
      --fsds-alert-spacing-gap: var(--fsds-semantic-spacing-gap-grid-small, 8px);
      --fsds-alert-text-size: var(--fsds-semantic-typography-body-03, 14px);
      --fsds-alert-text-weight: var(--fsds-semantic-typography-font-weight-regular, 400);
      --fsds-alert-icon-size: var(--fsds-core-spacing-size-06, 16px);
      --fsds-alert-typography-title-font-weight: var(--fsds-semantic-typography-font-weight-bold, 700);
      --fsds-alert-typography-title-font-size: var(--fsds-semantic-typography-body-02, 16px);
      --fsds-alert-size-padding-inline: var(--fsds-core-spacing-size-04, 8px);
      --fsds-alert-size-padding-page: var(--fsds-core-spacing-size-07, 24px);
      --fsds-alert-typography-page-font-size: var(--fsds-semantic-typography-body-02, 16px);
      --fsds-alert-typography-page-title-font-size: var(--fsds-semantic-typography-body-01, 18px);
      --fsds-alert-typography-inline-font-size: var(--fsds-semantic-typography-body-04, 12px);
    }

    .alert--info {
      --fsds-alert-color-background-primary: var(--fsds-semantic-color-background-info-subtle, #95dafb);
      --fsds-alert-color-foreground-primary: var(--fsds-semantic-color-foreground-on-info-subtle, #013ab0);
      --fsds-alert-color-border-primary: var(--fsds-semantic-color-border-info, #034fd6);
    }

    .alert--success {
      --fsds-alert-color-background-primary: var(--fsds-semantic-color-background-success-subtle, #b3dba7);
      --fsds-alert-color-foreground-primary: var(--fsds-semantic-color-foreground-on-success-subtle, #2c4f09);
      --fsds-alert-color-border-primary: var(--fsds-semantic-color-border-success, #3a6614);
    }

    .alert--warning {
      --fsds-alert-color-background-primary: var(--fsds-semantic-color-background-warning-subtle, #fdc67f);
      --fsds-alert-color-foreground-primary: var(--fsds-semantic-color-foreground-on-warning-subtle, #6c3a00);
      --fsds-alert-color-border-primary: var(--fsds-semantic-color-border-warning, #8b4b00);
    }

    .alert--danger {
      --fsds-alert-color-background-primary: var(--fsds-semantic-color-background-danger-subtle, #fac2c2);
      --fsds-alert-color-foreground-primary: var(--fsds-semantic-color-foreground-on-danger-subtle, #900909);
      --fsds-alert-color-border-primary: var(--fsds-semantic-color-border-danger, #b31b1b);
    }

    .alert--inline {
      --fsds-alert-size-padding: var(--fsds-core-spacing-size-04, 8px);
      --fsds-alert-spacing-gap: var(--fsds-core-spacing-size-03, 4px);
      --fsds-alert-text-size: var(--fsds-semantic-typography-body-04, 12px);
      --fsds-alert-typography-title-font-size: var(--fsds-semantic-typography-body-03, 14px);
    }

    .alert--section {
      --fsds-alert-size-padding: var(--fsds-core-spacing-size-06, 16px);
      --fsds-alert-spacing-gap: var(--fsds-core-spacing-size-04, 8px);
      --fsds-alert-text-size: var(--fsds-semantic-typography-body-03, 14px);
      --fsds-alert-typography-title-font-size: var(--fsds-semantic-typography-body-02, 16px);
    }

    .alert--page {
      --fsds-alert-size-padding: var(--fsds-core-spacing-size-07, 24px);
      --fsds-alert-spacing-gap: var(--fsds-core-spacing-size-05, 12px);
      --fsds-alert-text-size: var(--fsds-semantic-typography-body-02, 16px);
      --fsds-alert-typography-title-font-size: var(--fsds-semantic-typography-body-01, 18px);
      --fsds-alert-typography-title-font-weight: var(--fsds-semantic-typography-font-weight-bold, 700);
    }

    @layer components.defaults {
    .alert {
      padding-block-start: var(--fsds-box-model-padding-block-start, var(--fsds-semantic-feedback-size-padding-block, 16px));
      padding-block-end: var(--fsds-box-model-padding-block-end, var(--fsds-semantic-feedback-size-padding-block, 16px));
      padding-inline-start: var(--fsds-box-model-padding-inline-start, var(--fsds-semantic-feedback-size-padding-inline, 16px));
      padding-inline-end: var(--fsds-box-model-padding-inline-end, var(--fsds-semantic-feedback-size-padding-inline, 16px));
      gap: var(--fsds-alert-design-root-spacing-gap, var(--fsds-alert-spacing-gap, 8px));
      width: var(--fsds-box-model-width, auto);
      min-width: var(--fsds-box-model-min-width, 0);
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, 0);
      max-height: var(--fsds-box-model-max-height, none);
      display: flex;
      flex-direction: column;
      align-items: flex-start;
      border-style: var(--fsds-alert-design-root-border-style, solid);
      border-width: var(--fsds-alert-design-root-border-width, 1px);
      box-sizing: border-box;
      padding: var(--fsds-alert-design-root-spacing-padding, var(--fsds-alert-size-padding, 16px));
      border-radius: var(--fsds-alert-design-root-shape-radius, var(--fsds-alert-size-radius, 6px));
      font-size: var(--fsds-alert-design-root-typography-size, var(--fsds-alert-text-size, 14px));
      font-weight: var(--fsds-alert-design-root-typography-weight, var(--fsds-alert-text-weight, 400));
      background-color: var(--fsds-alert-design-root-background-fill, var(--fsds-alert-color-background-primary, #ffffff));
      color: var(--fsds-alert-design-root-foreground-color, var(--fsds-alert-color-foreground-primary, #141414));
      border-color: var(--fsds-alert-design-root-border-color, var(--fsds-alert-color-border-primary, #a0a0a1));
    }

    .alert__icon {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      flex-shrink: 0;
    }

    .alert__body {
      flex: 1 1 auto;
      display: flex;
      flex-direction: column;
      gap: var(--fsds-alert-design-body-spacing-gap, var(--fsds-alert-spacing-gap, 8px));
    }

    .alert__dismiss {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      flex-shrink: 0;
      background: transparent;
      border: 0;
      padding: var(--fsds-alert-design-dismiss-spacing-padding, 0);
      margin-left: auto;
      color: var(--fsds-alert-design-dismiss-foreground-color, inherit);
      cursor: pointer;
      font: inherit;
      line-height: var(--fsds-alert-design-dismiss-typography-line-height, 1);
    }

    .alert__dismiss:hover {
      opacity: var(--fsds-alert-design-condition-713bb5876e6d-appearance-opacity, 0.7);
    }

    .alert__dismiss:focus-visible {
      outline: 2px solid currentColor;
      outline-offset: var(--fsds-alert-design-condition-366042b99cd1-focus-offset, 2px);
    }

    .alert__title {
      margin: 0;
      font-weight: var(--fsds-alert-design-title-typography-weight, var(--fsds-alert-typography-title-font-weight, 700));
      font-size: var(--fsds-alert-design-title-typography-size, var(--fsds-alert-typography-title-font-size, 16px));
    }
    }
  `;

  @property({ type: String }) intent?: AlertIntent;
  @property({ type: String }) level?: AlertLevel;
  @property({ type: Boolean }) dismissible?: boolean;
  @property({ attribute: false }) onDismiss?: () => void;
  @property({ type: String }) dismissLabel?: string = "Dismiss";
  @property({ attribute: false }) icon?: unknown;

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute("data-fsds-component", "alert");
  }

  private computeClasses(): string {
    return [
      "alert",
      this.intent ? `alert--${this.intent}` : null,
      this.level ? `alert--${this.level}` : null,
    ].filter(Boolean).join(" ");
  }

  override render() {
    return html`<div class="${this.computeClasses()}" role="alert" data-fsds-box="">
  ${this.icon ? html`
  <span class=${'alert__icon'} aria-hidden="true">${this.icon}</span>
  ` : nothing}
  <slot></slot>
  ${this.dismissible ? html`
  <fsds-button class=${'alert__dismiss'} type="button" @click=${this.onDismiss} .ariaLabel=${(this.dismissLabel ?? "Dismiss")}></fsds-button>
  ` : nothing}
</div>`;
  }
}

customElements.define('fsds-alert', AlertElement);


export class AlertBodyElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .alert {
      --fsds-alert-color-background-primary: var(--fsds-semantic-color-background-primary, #ffffff);
      --fsds-alert-color-foreground-primary: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-alert-color-border-primary: var(--fsds-semantic-color-border-primary, #a0a0a1);
      --fsds-alert-size-padding: var(--fsds-core-spacing-size-06, 16px);
      --fsds-alert-size-radius: var(--fsds-semantic-shape-control-radius-default, 6px);
      --fsds-alert-spacing-gap: var(--fsds-semantic-spacing-gap-grid-small, 8px);
      --fsds-alert-text-size: var(--fsds-semantic-typography-body-03, 14px);
      --fsds-alert-text-weight: var(--fsds-semantic-typography-font-weight-regular, 400);
      --fsds-alert-icon-size: var(--fsds-core-spacing-size-06, 16px);
      --fsds-alert-typography-title-font-weight: var(--fsds-semantic-typography-font-weight-bold, 700);
      --fsds-alert-typography-title-font-size: var(--fsds-semantic-typography-body-02, 16px);
      --fsds-alert-size-padding-inline: var(--fsds-core-spacing-size-04, 8px);
      --fsds-alert-size-padding-page: var(--fsds-core-spacing-size-07, 24px);
      --fsds-alert-typography-page-font-size: var(--fsds-semantic-typography-body-02, 16px);
      --fsds-alert-typography-page-title-font-size: var(--fsds-semantic-typography-body-01, 18px);
      --fsds-alert-typography-inline-font-size: var(--fsds-semantic-typography-body-04, 12px);
    }

    .alert--info {
      --fsds-alert-color-background-primary: var(--fsds-semantic-color-background-info-subtle, #95dafb);
      --fsds-alert-color-foreground-primary: var(--fsds-semantic-color-foreground-on-info-subtle, #013ab0);
      --fsds-alert-color-border-primary: var(--fsds-semantic-color-border-info, #034fd6);
    }

    .alert--success {
      --fsds-alert-color-background-primary: var(--fsds-semantic-color-background-success-subtle, #b3dba7);
      --fsds-alert-color-foreground-primary: var(--fsds-semantic-color-foreground-on-success-subtle, #2c4f09);
      --fsds-alert-color-border-primary: var(--fsds-semantic-color-border-success, #3a6614);
    }

    .alert--warning {
      --fsds-alert-color-background-primary: var(--fsds-semantic-color-background-warning-subtle, #fdc67f);
      --fsds-alert-color-foreground-primary: var(--fsds-semantic-color-foreground-on-warning-subtle, #6c3a00);
      --fsds-alert-color-border-primary: var(--fsds-semantic-color-border-warning, #8b4b00);
    }

    .alert--danger {
      --fsds-alert-color-background-primary: var(--fsds-semantic-color-background-danger-subtle, #fac2c2);
      --fsds-alert-color-foreground-primary: var(--fsds-semantic-color-foreground-on-danger-subtle, #900909);
      --fsds-alert-color-border-primary: var(--fsds-semantic-color-border-danger, #b31b1b);
    }

    .alert--inline {
      --fsds-alert-size-padding: var(--fsds-core-spacing-size-04, 8px);
      --fsds-alert-spacing-gap: var(--fsds-core-spacing-size-03, 4px);
      --fsds-alert-text-size: var(--fsds-semantic-typography-body-04, 12px);
      --fsds-alert-typography-title-font-size: var(--fsds-semantic-typography-body-03, 14px);
    }

    .alert--section {
      --fsds-alert-size-padding: var(--fsds-core-spacing-size-06, 16px);
      --fsds-alert-spacing-gap: var(--fsds-core-spacing-size-04, 8px);
      --fsds-alert-text-size: var(--fsds-semantic-typography-body-03, 14px);
      --fsds-alert-typography-title-font-size: var(--fsds-semantic-typography-body-02, 16px);
    }

    .alert--page {
      --fsds-alert-size-padding: var(--fsds-core-spacing-size-07, 24px);
      --fsds-alert-spacing-gap: var(--fsds-core-spacing-size-05, 12px);
      --fsds-alert-text-size: var(--fsds-semantic-typography-body-02, 16px);
      --fsds-alert-typography-title-font-size: var(--fsds-semantic-typography-body-01, 18px);
      --fsds-alert-typography-title-font-weight: var(--fsds-semantic-typography-font-weight-bold, 700);
    }

    @layer components.defaults {
    .alert {
      padding-block-start: var(--fsds-box-model-padding-block-start, var(--fsds-semantic-feedback-size-padding-block, 16px));
      padding-block-end: var(--fsds-box-model-padding-block-end, var(--fsds-semantic-feedback-size-padding-block, 16px));
      padding-inline-start: var(--fsds-box-model-padding-inline-start, var(--fsds-semantic-feedback-size-padding-inline, 16px));
      padding-inline-end: var(--fsds-box-model-padding-inline-end, var(--fsds-semantic-feedback-size-padding-inline, 16px));
      gap: var(--fsds-alert-design-root-spacing-gap, var(--fsds-alert-spacing-gap, 8px));
      width: var(--fsds-box-model-width, auto);
      min-width: var(--fsds-box-model-min-width, 0);
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, 0);
      max-height: var(--fsds-box-model-max-height, none);
      display: flex;
      flex-direction: column;
      align-items: flex-start;
      border-style: var(--fsds-alert-design-root-border-style, solid);
      border-width: var(--fsds-alert-design-root-border-width, 1px);
      box-sizing: border-box;
      padding: var(--fsds-alert-design-root-spacing-padding, var(--fsds-alert-size-padding, 16px));
      border-radius: var(--fsds-alert-design-root-shape-radius, var(--fsds-alert-size-radius, 6px));
      font-size: var(--fsds-alert-design-root-typography-size, var(--fsds-alert-text-size, 14px));
      font-weight: var(--fsds-alert-design-root-typography-weight, var(--fsds-alert-text-weight, 400));
      background-color: var(--fsds-alert-design-root-background-fill, var(--fsds-alert-color-background-primary, #ffffff));
      color: var(--fsds-alert-design-root-foreground-color, var(--fsds-alert-color-foreground-primary, #141414));
      border-color: var(--fsds-alert-design-root-border-color, var(--fsds-alert-color-border-primary, #a0a0a1));
    }

    .alert__icon {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      flex-shrink: 0;
    }

    .alert__body {
      flex: 1 1 auto;
      display: flex;
      flex-direction: column;
      gap: var(--fsds-alert-design-body-spacing-gap, var(--fsds-alert-spacing-gap, 8px));
    }

    .alert__dismiss {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      flex-shrink: 0;
      background: transparent;
      border: 0;
      padding: var(--fsds-alert-design-dismiss-spacing-padding, 0);
      margin-left: auto;
      color: var(--fsds-alert-design-dismiss-foreground-color, inherit);
      cursor: pointer;
      font: inherit;
      line-height: var(--fsds-alert-design-dismiss-typography-line-height, 1);
    }

    .alert__dismiss:hover {
      opacity: var(--fsds-alert-design-condition-713bb5876e6d-appearance-opacity, 0.7);
    }

    .alert__dismiss:focus-visible {
      outline: 2px solid currentColor;
      outline-offset: var(--fsds-alert-design-condition-366042b99cd1-focus-offset, 2px);
    }

    .alert__title {
      margin: 0;
      font-weight: var(--fsds-alert-design-title-typography-weight, var(--fsds-alert-typography-title-font-weight, 700));
      font-size: var(--fsds-alert-design-title-typography-size, var(--fsds-alert-typography-title-font-size, 16px));
    }
    }
  `;

  override render() {
    return html`<fsds-stack class="alert__body"><slot></slot></fsds-stack>`;
  }
}

customElements.define('fsds-alert-body', AlertBodyElement);

export class AlertTitleElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .alert {
      --fsds-alert-color-background-primary: var(--fsds-semantic-color-background-primary, #ffffff);
      --fsds-alert-color-foreground-primary: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-alert-color-border-primary: var(--fsds-semantic-color-border-primary, #a0a0a1);
      --fsds-alert-size-padding: var(--fsds-core-spacing-size-06, 16px);
      --fsds-alert-size-radius: var(--fsds-semantic-shape-control-radius-default, 6px);
      --fsds-alert-spacing-gap: var(--fsds-semantic-spacing-gap-grid-small, 8px);
      --fsds-alert-text-size: var(--fsds-semantic-typography-body-03, 14px);
      --fsds-alert-text-weight: var(--fsds-semantic-typography-font-weight-regular, 400);
      --fsds-alert-icon-size: var(--fsds-core-spacing-size-06, 16px);
      --fsds-alert-typography-title-font-weight: var(--fsds-semantic-typography-font-weight-bold, 700);
      --fsds-alert-typography-title-font-size: var(--fsds-semantic-typography-body-02, 16px);
      --fsds-alert-size-padding-inline: var(--fsds-core-spacing-size-04, 8px);
      --fsds-alert-size-padding-page: var(--fsds-core-spacing-size-07, 24px);
      --fsds-alert-typography-page-font-size: var(--fsds-semantic-typography-body-02, 16px);
      --fsds-alert-typography-page-title-font-size: var(--fsds-semantic-typography-body-01, 18px);
      --fsds-alert-typography-inline-font-size: var(--fsds-semantic-typography-body-04, 12px);
    }

    .alert--info {
      --fsds-alert-color-background-primary: var(--fsds-semantic-color-background-info-subtle, #95dafb);
      --fsds-alert-color-foreground-primary: var(--fsds-semantic-color-foreground-on-info-subtle, #013ab0);
      --fsds-alert-color-border-primary: var(--fsds-semantic-color-border-info, #034fd6);
    }

    .alert--success {
      --fsds-alert-color-background-primary: var(--fsds-semantic-color-background-success-subtle, #b3dba7);
      --fsds-alert-color-foreground-primary: var(--fsds-semantic-color-foreground-on-success-subtle, #2c4f09);
      --fsds-alert-color-border-primary: var(--fsds-semantic-color-border-success, #3a6614);
    }

    .alert--warning {
      --fsds-alert-color-background-primary: var(--fsds-semantic-color-background-warning-subtle, #fdc67f);
      --fsds-alert-color-foreground-primary: var(--fsds-semantic-color-foreground-on-warning-subtle, #6c3a00);
      --fsds-alert-color-border-primary: var(--fsds-semantic-color-border-warning, #8b4b00);
    }

    .alert--danger {
      --fsds-alert-color-background-primary: var(--fsds-semantic-color-background-danger-subtle, #fac2c2);
      --fsds-alert-color-foreground-primary: var(--fsds-semantic-color-foreground-on-danger-subtle, #900909);
      --fsds-alert-color-border-primary: var(--fsds-semantic-color-border-danger, #b31b1b);
    }

    .alert--inline {
      --fsds-alert-size-padding: var(--fsds-core-spacing-size-04, 8px);
      --fsds-alert-spacing-gap: var(--fsds-core-spacing-size-03, 4px);
      --fsds-alert-text-size: var(--fsds-semantic-typography-body-04, 12px);
      --fsds-alert-typography-title-font-size: var(--fsds-semantic-typography-body-03, 14px);
    }

    .alert--section {
      --fsds-alert-size-padding: var(--fsds-core-spacing-size-06, 16px);
      --fsds-alert-spacing-gap: var(--fsds-core-spacing-size-04, 8px);
      --fsds-alert-text-size: var(--fsds-semantic-typography-body-03, 14px);
      --fsds-alert-typography-title-font-size: var(--fsds-semantic-typography-body-02, 16px);
    }

    .alert--page {
      --fsds-alert-size-padding: var(--fsds-core-spacing-size-07, 24px);
      --fsds-alert-spacing-gap: var(--fsds-core-spacing-size-05, 12px);
      --fsds-alert-text-size: var(--fsds-semantic-typography-body-02, 16px);
      --fsds-alert-typography-title-font-size: var(--fsds-semantic-typography-body-01, 18px);
      --fsds-alert-typography-title-font-weight: var(--fsds-semantic-typography-font-weight-bold, 700);
    }

    @layer components.defaults {
    .alert {
      padding-block-start: var(--fsds-box-model-padding-block-start, var(--fsds-semantic-feedback-size-padding-block, 16px));
      padding-block-end: var(--fsds-box-model-padding-block-end, var(--fsds-semantic-feedback-size-padding-block, 16px));
      padding-inline-start: var(--fsds-box-model-padding-inline-start, var(--fsds-semantic-feedback-size-padding-inline, 16px));
      padding-inline-end: var(--fsds-box-model-padding-inline-end, var(--fsds-semantic-feedback-size-padding-inline, 16px));
      gap: var(--fsds-alert-design-root-spacing-gap, var(--fsds-alert-spacing-gap, 8px));
      width: var(--fsds-box-model-width, auto);
      min-width: var(--fsds-box-model-min-width, 0);
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, 0);
      max-height: var(--fsds-box-model-max-height, none);
      display: flex;
      flex-direction: column;
      align-items: flex-start;
      border-style: var(--fsds-alert-design-root-border-style, solid);
      border-width: var(--fsds-alert-design-root-border-width, 1px);
      box-sizing: border-box;
      padding: var(--fsds-alert-design-root-spacing-padding, var(--fsds-alert-size-padding, 16px));
      border-radius: var(--fsds-alert-design-root-shape-radius, var(--fsds-alert-size-radius, 6px));
      font-size: var(--fsds-alert-design-root-typography-size, var(--fsds-alert-text-size, 14px));
      font-weight: var(--fsds-alert-design-root-typography-weight, var(--fsds-alert-text-weight, 400));
      background-color: var(--fsds-alert-design-root-background-fill, var(--fsds-alert-color-background-primary, #ffffff));
      color: var(--fsds-alert-design-root-foreground-color, var(--fsds-alert-color-foreground-primary, #141414));
      border-color: var(--fsds-alert-design-root-border-color, var(--fsds-alert-color-border-primary, #a0a0a1));
    }

    .alert__icon {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      flex-shrink: 0;
    }

    .alert__body {
      flex: 1 1 auto;
      display: flex;
      flex-direction: column;
      gap: var(--fsds-alert-design-body-spacing-gap, var(--fsds-alert-spacing-gap, 8px));
    }

    .alert__dismiss {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      flex-shrink: 0;
      background: transparent;
      border: 0;
      padding: var(--fsds-alert-design-dismiss-spacing-padding, 0);
      margin-left: auto;
      color: var(--fsds-alert-design-dismiss-foreground-color, inherit);
      cursor: pointer;
      font: inherit;
      line-height: var(--fsds-alert-design-dismiss-typography-line-height, 1);
    }

    .alert__dismiss:hover {
      opacity: var(--fsds-alert-design-condition-713bb5876e6d-appearance-opacity, 0.7);
    }

    .alert__dismiss:focus-visible {
      outline: 2px solid currentColor;
      outline-offset: var(--fsds-alert-design-condition-366042b99cd1-focus-offset, 2px);
    }

    .alert__title {
      margin: 0;
      font-weight: var(--fsds-alert-design-title-typography-weight, var(--fsds-alert-typography-title-font-weight, 700));
      font-size: var(--fsds-alert-design-title-typography-size, var(--fsds-alert-typography-title-font-size, 16px));
    }
    }
  `;

  override render() {
    return html`<fsds-stack as="h3" class="alert__title"><slot></slot></fsds-stack>`;
  }
}

customElements.define('fsds-alert-title', AlertTitleElement);
// @generated:end

// @custom:start trailing

// @custom:end