// @generated:start imports
import { LitElement, html, css, nothing, type PropertyValues } from 'lit';
import { property } from 'lit/decorators.js';
import { WalkthroughBehavior } from './WalkthroughBehavior.js';
import { AnchoredPositionController } from '../../primitives/surfaces/AnchoredPositionController.js';
import { ifDefined } from 'lit/directives/if-defined.js';
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type WalkthroughStepSpec = { anchor: string; title: string; description?: string };
export type WalkthroughPlacement = "top" | "bottom" | "left" | "right" | "auto";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
export class WalkthroughElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .walkthrough {
      --fsds-walkthrough-surface-bg: var(--fsds-semantic-color-background-secondary, #f7f7f7);
      --fsds-walkthrough-surface-border: var(--fsds-semantic-color-border-subtle, #d0d0d0);
      --fsds-walkthrough-surface-radius: var(--fsds-semantic-shape-radius-large, 16px);
      --fsds-walkthrough-surface-shadow: var(--fsds-semantic-elevation-surface-floating, 0px 2px 4px #0000000f, 0px 4px 8px #0000001a);
      --fsds-walkthrough-surface-padding: var(--fsds-core-spacing-size-08, 32px);
      --fsds-walkthrough-title-font-size: var(--fsds-semantic-typography-heading-03, 20px);
      --fsds-walkthrough-title-font-weight: var(--fsds-semantic-typography-font-weight-bold, 700);
      --fsds-walkthrough-title-color: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-walkthrough-description-font-size: var(--fsds-semantic-typography-body-02, 16px);
      --fsds-walkthrough-description-color: var(--fsds-semantic-color-foreground-secondary, #474647);
      --fsds-walkthrough-description-margin-top: var(--fsds-core-spacing-size-04, 8px);
      --fsds-walkthrough-controls-gap: var(--fsds-core-spacing-size-05, 12px);
      --fsds-walkthrough-controls-margin-top: var(--fsds-core-spacing-size-06, 16px);
      --fsds-walkthrough-dots-size: var(--fsds-core-spacing-size-04, 8px);
      --fsds-walkthrough-dots-gap: var(--fsds-core-spacing-size-03, 4px);
      --fsds-walkthrough-dots-idle: var(--fsds-semantic-color-border-subtle, #d0d0d0);
      --fsds-walkthrough-button-primary-bg: var(--fsds-semantic-color-action-background-primary-default, #0566fe);
      --fsds-walkthrough-button-primary-color: var(--fsds-semantic-color-action-foreground-primary-default, #ffffff);
      --fsds-walkthrough-button-primary-radius: var(--fsds-semantic-shape-control-radius-default, 6px);
      --fsds-walkthrough-button-secondary-bg: var(--fsds-core-color-mode-transparent, #00000000);
      --fsds-walkthrough-button-secondary-color: var(--fsds-semantic-color-foreground-secondary, #474647);
      --fsds-walkthrough-button-secondary-border: var(--fsds-semantic-color-border-subtle, #d0d0d0);
    }

    @layer components.defaults {
    .walkthrough {
      padding-block-start: var(--fsds-box-model-padding-block-start, 0);
      padding-block-end: var(--fsds-box-model-padding-block-end, 0);
      padding-inline-start: var(--fsds-box-model-padding-inline-start, 0);
      padding-inline-end: var(--fsds-box-model-padding-inline-end, 0);
      gap: var(--fsds-walkthrough-design-root-spacing-gap, var(--fsds-walkthrough-dots-gap, 4px));
      width: var(--fsds-walkthrough-design-root-sizing-width, 360px);
      min-width: var(--fsds-box-model-min-width, 0);
      max-width: var(--fsds-walkthrough-design-root-sizing-max-width, calc(100vw - 32px));
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, 0);
      max-height: var(--fsds-walkthrough-design-root-sizing-max-height, calc(100dvh - 32px));
      position: relative;
      display: flex;
      flex-direction: column;
      background-color: var(--fsds-walkthrough-design-root-background-fill, var(--fsds-walkthrough-surface-bg, #f7f7f7));
      border-color: var(--fsds-walkthrough-design-root-border-color, var(--fsds-walkthrough-surface-border, #d0d0d0));
      border-style: var(--fsds-walkthrough-design-root-border-style, solid);
      border-width: var(--fsds-walkthrough-design-root-border-width, 1px);
      border-radius: var(--fsds-walkthrough-design-root-shape-radius, var(--fsds-walkthrough-surface-radius, 16px));
      box-shadow: var(--fsds-walkthrough-design-root-elevation-shadow, var(--fsds-walkthrough-surface-shadow, 0px 2px 4px #0000000f, 0px 4px 8px #0000001a));
      padding: var(--fsds-walkthrough-design-root-spacing-padding, var(--fsds-walkthrough-surface-padding, 32px));
      overflow-y: auto;
      box-sizing: border-box;
    }

    .walkthrough__content {
      display: flex;
      flex-direction: column;
      gap: var(--fsds-walkthrough-design-content-spacing-gap, var(--fsds-walkthrough-description-margin-top, 8px));
    }

    .walkthrough__title {
      margin: 0;
      font-size: var(--fsds-walkthrough-design-title-typography-size, var(--fsds-walkthrough-title-font-size, 20px));
      font-weight: var(--fsds-walkthrough-design-title-typography-weight, var(--fsds-walkthrough-title-font-weight, 700));
      color: var(--fsds-walkthrough-design-title-foreground-color, var(--fsds-walkthrough-title-color, #141414));
    }

    .walkthrough__description {
      margin: 0;
      font-size: var(--fsds-walkthrough-design-description-typography-size, var(--fsds-walkthrough-description-font-size, 16px));
      color: var(--fsds-walkthrough-design-description-foreground-color, var(--fsds-walkthrough-description-color, #474647));
      line-height: var(--fsds-walkthrough-design-description-typography-line-height, 1.5);
    }

    .walkthrough__controls {
      display: flex;
      flex-direction: row;
      align-items: center;
      gap: var(--fsds-walkthrough-design-controls-spacing-gap, var(--fsds-walkthrough-controls-gap, 12px));
      margin-top: var(--fsds-walkthrough-controls-margin-top, 16px);
      border-top-color: var(--fsds-walkthrough-design-controls-border-top-color, var(--fsds-walkthrough-surface-border, #d0d0d0));
      border-top-style: var(--fsds-walkthrough-design-controls-border-top-style, solid);
      border-top-width: var(--fsds-walkthrough-design-controls-border-top-width, 1px);
      padding-top: var(--fsds-walkthrough-controls-margin-top, 16px);
      flex-wrap: wrap;
    }

    .walkthrough__skip {
      background: transparent;
      border: none;
      color: var(--fsds-walkthrough-design-skip-foreground-color, var(--fsds-walkthrough-button-secondary-color, #474647));
      cursor: pointer;
      padding: var(--fsds-walkthrough-design-skip-spacing-padding, 0);
      margin-right: auto;
    }

    .walkthrough__prev {
      background-color: var(--fsds-walkthrough-design-prev-background-fill, var(--fsds-walkthrough-button-secondary-bg, #00000000));
      border-color: var(--fsds-walkthrough-design-prev-border-color, var(--fsds-walkthrough-button-secondary-border, #d0d0d0));
      border-style: var(--fsds-walkthrough-design-prev-border-style, solid);
      border-width: var(--fsds-walkthrough-design-prev-border-width, 1px);
      border-radius: var(--fsds-walkthrough-design-prev-shape-radius, var(--fsds-walkthrough-button-primary-radius, 6px));
      color: var(--fsds-walkthrough-design-prev-foreground-color, var(--fsds-walkthrough-button-secondary-color, #474647));
      cursor: pointer;
    }

    .walkthrough__next {
      background-color: var(--fsds-walkthrough-design-next-background-fill, var(--fsds-walkthrough-button-primary-bg, #0566fe));
      border: none;
      border-radius: var(--fsds-walkthrough-design-next-shape-radius, var(--fsds-walkthrough-button-primary-radius, 6px));
      color: var(--fsds-walkthrough-design-next-foreground-color, var(--fsds-walkthrough-button-primary-color, #ffffff));
      cursor: pointer;
    }

    .walkthrough__dots {
      display: flex;
      flex-direction: row;
      align-items: center;
      justify-content: center;
      gap: var(--fsds-walkthrough-design-dots-spacing-gap, var(--fsds-walkthrough-dots-gap, 4px));
    }

    .walkthrough__dot {
      display: block;
      width: var(--fsds-walkthrough-design-dot-sizing-width, var(--fsds-walkthrough-dots-size, 8px));
      height: var(--fsds-walkthrough-design-dot-sizing-height, var(--fsds-walkthrough-dots-size, 8px));
      border-radius: var(--fsds-walkthrough-design-dot-shape-radius, 50%);
      background-color: var(--fsds-walkthrough-design-dot-background-fill, var(--fsds-walkthrough-dots-idle, #d0d0d0));
      border: none;
      padding: var(--fsds-walkthrough-design-dot-spacing-padding, 0);
      cursor: pointer;
    }

    .walkthrough__counter {
      color: var(--fsds-walkthrough-design-counter-foreground-color, var(--fsds-walkthrough-description-color, #474647));
      font-size: var(--fsds-walkthrough-design-counter-typography-size, var(--fsds-walkthrough-description-font-size, 16px));
    }
    }
  `;

  @property({ attribute: false }) steps?: WalkthroughStepSpec[] = [{"anchor":"#step-1","title":"Welcome to the tour"},{"anchor":"#step-2","title":"Browse your dashboard"},{"anchor":"#step-3","title":"Configure preferences"}];
  @property({ type: Number }) index?: number;
  @property({ type: Number }) defaultIndex?: number = 0;
  @property({ attribute: false }) onStepChange?: (index: number) => void;
  @property({ attribute: false }) onComplete?: () => void;
  @property({ attribute: false }) onSkip?: () => void;
  @property({ type: String }) label?: string = "Feature tour";
  @property({ type: String }) storageKey?: string;
  @property({ type: Boolean }) autoStart?: boolean = false;
  @property({ type: Boolean }) closeOnOutsideClick?: boolean = false;
  @property({ type: String }) placement?: WalkthroughPlacement = "auto";
  @property({ attribute: false }) onPrevious?: () => void;
  @property({ attribute: false }) onNext?: () => void;
  @property({ type: Boolean }) previousDisabled?: boolean = false;
  @property({ type: String }) nextLabel?: string = "Next";
  @property({ type: String }) progressLabel?: string;

  private initializedBehavior?: WalkthroughBehavior;
  private get behavior(): WalkthroughBehavior {
    return this.initializedBehavior ??= new WalkthroughBehavior(this, {
    index: () => this.index,
    defaultIndex: this.defaultIndex,
    onStepChange: (v) => this.onStepChange?.(v),
    closeOnOutsideClick: this.closeOnOutsideClick,
  });
  }

  private _moving = false;
  private _portaled = false;
  private _portalOriginParent: Node | null = null;
  private _portalOriginNext: Node | null = null;

  private _anchorTargetEl: HTMLElement | null = null;
  private _position = new AnchoredPositionController(this, {
    anchor: () => this._anchorTargetEl,
    content: () => this,
    open: () => true,
    placement: () => ((this.placement ?? "auto") as "top" | "bottom" | "left" | "right" | "auto"),
    collision: () => "flip-shift",
    onChange: () => this.requestUpdate(),
  });

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute("data-fsds-component", "walkthrough");
    if (!this._portaled && typeof document !== "undefined" && this.parentNode && this.parentNode !== document.body) {
      this._portalOriginParent = this.parentNode;
      this._portalOriginNext = this.nextSibling;
      this._portaled = true;
      this._moving = true;
      document.body.appendChild(this);
      this._moving = false;
    }
  }

  override disconnectedCallback(): void {
    if (!this._moving) {
      if (this._portalOriginParent && this._portalOriginParent.isConnected) {
        this._portalOriginParent.insertBefore(this, this._portalOriginNext);
      }
      this._portaled = false;
      this._portalOriginParent = null;
      this._portalOriginNext = null;
    }
    super.disconnectedCallback();
  }

  override willUpdate(_changedProperties: PropertyValues<this>): void {
    // Re-query on every update pass — the anchor lives outside this
    // element's tree, so a per-property changed-set check can't see
    // mutations to the target page (only index/steps changes are
    // reactive triggers here, but re-resolving is cheap and idempotent).
    const selector = ((this.steps ?? [{"anchor":"#step-1","title":"Welcome to the tour"},{"anchor":"#step-2","title":"Browse your dashboard"},{"anchor":"#step-3","title":"Configure preferences"}]))[this.index ?? 0]?.anchor;
    this._anchorTargetEl = selector && typeof document !== "undefined" ? document.querySelector<HTMLElement>(selector) : null;
  }

  override updated(changedProperties: PropertyValues<this>): void {
    super.updated(changedProperties);
    // A stale scheduled update landing after a genuine disconnect must
    // be a no-op — it must NOT resurrect inline positioning on an
    // element that has already torn down.
    if (!this.isConnected) return;
    const pos = this._position.state;
    // The static :host rule is display: contents (no box), which would
    // make position: fixed a layout no-op. Give the host a real box
    // before applying fixed positioning.
    this.style.display = "block";
    this.style.position = "fixed";
    this.style.top = `${pos.top}px`;
    this.style.left = `${pos.left}px`;
    this.style.visibility = pos.ready ? "visible" : "hidden";
    this.setAttribute("data-placement", pos.placement);
  }

  private computeClasses(): string {
    return [
      "walkthrough",
      (this.placement ?? "auto") ? `walkthrough--${(this.placement ?? "auto")}` : null,
    ].filter(Boolean).join(" ");
  }

  override render() {
    return html`<div class="${this.computeClasses()}" role="status" aria-label=${ifDefined((this.label ?? "Feature tour"))} data-fsds-box="">
  <div class=${'walkthrough__content'} role="group" aria-labelledby=${ifDefined([this.querySelector('[slot="title"]') !== null ? 'walkthrough-title' : null].filter(Boolean).join(' ') || undefined)} aria-describedby=${ifDefined([this.querySelector('[slot="description"]') !== null ? 'walkthrough-description' : null].filter(Boolean).join(' ') || undefined)}>
    <h3 class=${'walkthrough__title'} aria-label=${ifDefined((this.label ?? "Feature tour"))} id="walkthrough-title">
      <slot name="title" @slotchange=${() => this.requestUpdate()}></slot>
    </h3>
    <p class=${'walkthrough__description'} id="walkthrough-description">
      <slot name="description" @slotchange=${() => this.requestUpdate()}></slot>
    </p>
  </div>
  <div class=${'walkthrough__controls'}>
    <button class=${'walkthrough__skip'} type="button" @click=${this.onSkip} aria-label="Skip tour">Skip</button>
    <button class=${'walkthrough__prev'} type="button" @click=${this.onPrevious} aria-label="Previous step" ?disabled=${(this.previousDisabled ?? false)}>Previous</button>
    <div class=${'walkthrough__dots'}>
      ${((this.steps ?? [{"anchor":"#step-1","title":"Welcome to the tour"},{"anchor":"#step-2","title":"Browse your dashboard"},{"anchor":"#step-3","title":"Configure preferences"}])).map((item, index) => html`
      <button class=${'walkthrough__dot'} type="button" @click=${() => this.behavior.setStep(index)} aria-label=${ifDefined(item.title)} data-step-index=${ifDefined(index)}></button>
      `)}
    </div>
    <span class=${'walkthrough__counter'}>${this.progressLabel}</span>
    <button class=${'walkthrough__next'} type="button" @click=${this.onNext} aria-label=${ifDefined((this.nextLabel ?? "Next"))}>${(this.nextLabel ?? "Next")}</button>
  </div>
</div>`;
  }
}

customElements.define('fsds-walkthrough', WalkthroughElement);


export class WalkthroughContentElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .walkthrough {
      --fsds-walkthrough-surface-bg: var(--fsds-semantic-color-background-secondary, #f7f7f7);
      --fsds-walkthrough-surface-border: var(--fsds-semantic-color-border-subtle, #d0d0d0);
      --fsds-walkthrough-surface-radius: var(--fsds-semantic-shape-radius-large, 16px);
      --fsds-walkthrough-surface-shadow: var(--fsds-semantic-elevation-surface-floating, 0px 2px 4px #0000000f, 0px 4px 8px #0000001a);
      --fsds-walkthrough-surface-padding: var(--fsds-core-spacing-size-08, 32px);
      --fsds-walkthrough-title-font-size: var(--fsds-semantic-typography-heading-03, 20px);
      --fsds-walkthrough-title-font-weight: var(--fsds-semantic-typography-font-weight-bold, 700);
      --fsds-walkthrough-title-color: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-walkthrough-description-font-size: var(--fsds-semantic-typography-body-02, 16px);
      --fsds-walkthrough-description-color: var(--fsds-semantic-color-foreground-secondary, #474647);
      --fsds-walkthrough-description-margin-top: var(--fsds-core-spacing-size-04, 8px);
      --fsds-walkthrough-controls-gap: var(--fsds-core-spacing-size-05, 12px);
      --fsds-walkthrough-controls-margin-top: var(--fsds-core-spacing-size-06, 16px);
      --fsds-walkthrough-dots-size: var(--fsds-core-spacing-size-04, 8px);
      --fsds-walkthrough-dots-gap: var(--fsds-core-spacing-size-03, 4px);
      --fsds-walkthrough-dots-idle: var(--fsds-semantic-color-border-subtle, #d0d0d0);
      --fsds-walkthrough-button-primary-bg: var(--fsds-semantic-color-action-background-primary-default, #0566fe);
      --fsds-walkthrough-button-primary-color: var(--fsds-semantic-color-action-foreground-primary-default, #ffffff);
      --fsds-walkthrough-button-primary-radius: var(--fsds-semantic-shape-control-radius-default, 6px);
      --fsds-walkthrough-button-secondary-bg: var(--fsds-core-color-mode-transparent, #00000000);
      --fsds-walkthrough-button-secondary-color: var(--fsds-semantic-color-foreground-secondary, #474647);
      --fsds-walkthrough-button-secondary-border: var(--fsds-semantic-color-border-subtle, #d0d0d0);
    }

    @layer components.defaults {
    .walkthrough {
      padding-block-start: var(--fsds-box-model-padding-block-start, 0);
      padding-block-end: var(--fsds-box-model-padding-block-end, 0);
      padding-inline-start: var(--fsds-box-model-padding-inline-start, 0);
      padding-inline-end: var(--fsds-box-model-padding-inline-end, 0);
      gap: var(--fsds-walkthrough-design-root-spacing-gap, var(--fsds-walkthrough-dots-gap, 4px));
      width: var(--fsds-walkthrough-design-root-sizing-width, 360px);
      min-width: var(--fsds-box-model-min-width, 0);
      max-width: var(--fsds-walkthrough-design-root-sizing-max-width, calc(100vw - 32px));
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, 0);
      max-height: var(--fsds-walkthrough-design-root-sizing-max-height, calc(100dvh - 32px));
      position: relative;
      display: flex;
      flex-direction: column;
      background-color: var(--fsds-walkthrough-design-root-background-fill, var(--fsds-walkthrough-surface-bg, #f7f7f7));
      border-color: var(--fsds-walkthrough-design-root-border-color, var(--fsds-walkthrough-surface-border, #d0d0d0));
      border-style: var(--fsds-walkthrough-design-root-border-style, solid);
      border-width: var(--fsds-walkthrough-design-root-border-width, 1px);
      border-radius: var(--fsds-walkthrough-design-root-shape-radius, var(--fsds-walkthrough-surface-radius, 16px));
      box-shadow: var(--fsds-walkthrough-design-root-elevation-shadow, var(--fsds-walkthrough-surface-shadow, 0px 2px 4px #0000000f, 0px 4px 8px #0000001a));
      padding: var(--fsds-walkthrough-design-root-spacing-padding, var(--fsds-walkthrough-surface-padding, 32px));
      overflow-y: auto;
      box-sizing: border-box;
    }

    .walkthrough__content {
      display: flex;
      flex-direction: column;
      gap: var(--fsds-walkthrough-design-content-spacing-gap, var(--fsds-walkthrough-description-margin-top, 8px));
    }

    .walkthrough__title {
      margin: 0;
      font-size: var(--fsds-walkthrough-design-title-typography-size, var(--fsds-walkthrough-title-font-size, 20px));
      font-weight: var(--fsds-walkthrough-design-title-typography-weight, var(--fsds-walkthrough-title-font-weight, 700));
      color: var(--fsds-walkthrough-design-title-foreground-color, var(--fsds-walkthrough-title-color, #141414));
    }

    .walkthrough__description {
      margin: 0;
      font-size: var(--fsds-walkthrough-design-description-typography-size, var(--fsds-walkthrough-description-font-size, 16px));
      color: var(--fsds-walkthrough-design-description-foreground-color, var(--fsds-walkthrough-description-color, #474647));
      line-height: var(--fsds-walkthrough-design-description-typography-line-height, 1.5);
    }

    .walkthrough__controls {
      display: flex;
      flex-direction: row;
      align-items: center;
      gap: var(--fsds-walkthrough-design-controls-spacing-gap, var(--fsds-walkthrough-controls-gap, 12px));
      margin-top: var(--fsds-walkthrough-controls-margin-top, 16px);
      border-top-color: var(--fsds-walkthrough-design-controls-border-top-color, var(--fsds-walkthrough-surface-border, #d0d0d0));
      border-top-style: var(--fsds-walkthrough-design-controls-border-top-style, solid);
      border-top-width: var(--fsds-walkthrough-design-controls-border-top-width, 1px);
      padding-top: var(--fsds-walkthrough-controls-margin-top, 16px);
      flex-wrap: wrap;
    }

    .walkthrough__skip {
      background: transparent;
      border: none;
      color: var(--fsds-walkthrough-design-skip-foreground-color, var(--fsds-walkthrough-button-secondary-color, #474647));
      cursor: pointer;
      padding: var(--fsds-walkthrough-design-skip-spacing-padding, 0);
      margin-right: auto;
    }

    .walkthrough__prev {
      background-color: var(--fsds-walkthrough-design-prev-background-fill, var(--fsds-walkthrough-button-secondary-bg, #00000000));
      border-color: var(--fsds-walkthrough-design-prev-border-color, var(--fsds-walkthrough-button-secondary-border, #d0d0d0));
      border-style: var(--fsds-walkthrough-design-prev-border-style, solid);
      border-width: var(--fsds-walkthrough-design-prev-border-width, 1px);
      border-radius: var(--fsds-walkthrough-design-prev-shape-radius, var(--fsds-walkthrough-button-primary-radius, 6px));
      color: var(--fsds-walkthrough-design-prev-foreground-color, var(--fsds-walkthrough-button-secondary-color, #474647));
      cursor: pointer;
    }

    .walkthrough__next {
      background-color: var(--fsds-walkthrough-design-next-background-fill, var(--fsds-walkthrough-button-primary-bg, #0566fe));
      border: none;
      border-radius: var(--fsds-walkthrough-design-next-shape-radius, var(--fsds-walkthrough-button-primary-radius, 6px));
      color: var(--fsds-walkthrough-design-next-foreground-color, var(--fsds-walkthrough-button-primary-color, #ffffff));
      cursor: pointer;
    }

    .walkthrough__dots {
      display: flex;
      flex-direction: row;
      align-items: center;
      justify-content: center;
      gap: var(--fsds-walkthrough-design-dots-spacing-gap, var(--fsds-walkthrough-dots-gap, 4px));
    }

    .walkthrough__dot {
      display: block;
      width: var(--fsds-walkthrough-design-dot-sizing-width, var(--fsds-walkthrough-dots-size, 8px));
      height: var(--fsds-walkthrough-design-dot-sizing-height, var(--fsds-walkthrough-dots-size, 8px));
      border-radius: var(--fsds-walkthrough-design-dot-shape-radius, 50%);
      background-color: var(--fsds-walkthrough-design-dot-background-fill, var(--fsds-walkthrough-dots-idle, #d0d0d0));
      border: none;
      padding: var(--fsds-walkthrough-design-dot-spacing-padding, 0);
      cursor: pointer;
    }

    .walkthrough__counter {
      color: var(--fsds-walkthrough-design-counter-foreground-color, var(--fsds-walkthrough-description-color, #474647));
      font-size: var(--fsds-walkthrough-design-counter-typography-size, var(--fsds-walkthrough-description-font-size, 16px));
    }
    }
  `;

  override render() {
    return html`<fsds-stack class="walkthrough__content"><slot></slot></fsds-stack>`;
  }
}

customElements.define('fsds-walkthrough-content', WalkthroughContentElement);

export class WalkthroughTitleElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .walkthrough {
      --fsds-walkthrough-surface-bg: var(--fsds-semantic-color-background-secondary, #f7f7f7);
      --fsds-walkthrough-surface-border: var(--fsds-semantic-color-border-subtle, #d0d0d0);
      --fsds-walkthrough-surface-radius: var(--fsds-semantic-shape-radius-large, 16px);
      --fsds-walkthrough-surface-shadow: var(--fsds-semantic-elevation-surface-floating, 0px 2px 4px #0000000f, 0px 4px 8px #0000001a);
      --fsds-walkthrough-surface-padding: var(--fsds-core-spacing-size-08, 32px);
      --fsds-walkthrough-title-font-size: var(--fsds-semantic-typography-heading-03, 20px);
      --fsds-walkthrough-title-font-weight: var(--fsds-semantic-typography-font-weight-bold, 700);
      --fsds-walkthrough-title-color: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-walkthrough-description-font-size: var(--fsds-semantic-typography-body-02, 16px);
      --fsds-walkthrough-description-color: var(--fsds-semantic-color-foreground-secondary, #474647);
      --fsds-walkthrough-description-margin-top: var(--fsds-core-spacing-size-04, 8px);
      --fsds-walkthrough-controls-gap: var(--fsds-core-spacing-size-05, 12px);
      --fsds-walkthrough-controls-margin-top: var(--fsds-core-spacing-size-06, 16px);
      --fsds-walkthrough-dots-size: var(--fsds-core-spacing-size-04, 8px);
      --fsds-walkthrough-dots-gap: var(--fsds-core-spacing-size-03, 4px);
      --fsds-walkthrough-dots-idle: var(--fsds-semantic-color-border-subtle, #d0d0d0);
      --fsds-walkthrough-button-primary-bg: var(--fsds-semantic-color-action-background-primary-default, #0566fe);
      --fsds-walkthrough-button-primary-color: var(--fsds-semantic-color-action-foreground-primary-default, #ffffff);
      --fsds-walkthrough-button-primary-radius: var(--fsds-semantic-shape-control-radius-default, 6px);
      --fsds-walkthrough-button-secondary-bg: var(--fsds-core-color-mode-transparent, #00000000);
      --fsds-walkthrough-button-secondary-color: var(--fsds-semantic-color-foreground-secondary, #474647);
      --fsds-walkthrough-button-secondary-border: var(--fsds-semantic-color-border-subtle, #d0d0d0);
    }

    @layer components.defaults {
    .walkthrough {
      padding-block-start: var(--fsds-box-model-padding-block-start, 0);
      padding-block-end: var(--fsds-box-model-padding-block-end, 0);
      padding-inline-start: var(--fsds-box-model-padding-inline-start, 0);
      padding-inline-end: var(--fsds-box-model-padding-inline-end, 0);
      gap: var(--fsds-walkthrough-design-root-spacing-gap, var(--fsds-walkthrough-dots-gap, 4px));
      width: var(--fsds-walkthrough-design-root-sizing-width, 360px);
      min-width: var(--fsds-box-model-min-width, 0);
      max-width: var(--fsds-walkthrough-design-root-sizing-max-width, calc(100vw - 32px));
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, 0);
      max-height: var(--fsds-walkthrough-design-root-sizing-max-height, calc(100dvh - 32px));
      position: relative;
      display: flex;
      flex-direction: column;
      background-color: var(--fsds-walkthrough-design-root-background-fill, var(--fsds-walkthrough-surface-bg, #f7f7f7));
      border-color: var(--fsds-walkthrough-design-root-border-color, var(--fsds-walkthrough-surface-border, #d0d0d0));
      border-style: var(--fsds-walkthrough-design-root-border-style, solid);
      border-width: var(--fsds-walkthrough-design-root-border-width, 1px);
      border-radius: var(--fsds-walkthrough-design-root-shape-radius, var(--fsds-walkthrough-surface-radius, 16px));
      box-shadow: var(--fsds-walkthrough-design-root-elevation-shadow, var(--fsds-walkthrough-surface-shadow, 0px 2px 4px #0000000f, 0px 4px 8px #0000001a));
      padding: var(--fsds-walkthrough-design-root-spacing-padding, var(--fsds-walkthrough-surface-padding, 32px));
      overflow-y: auto;
      box-sizing: border-box;
    }

    .walkthrough__content {
      display: flex;
      flex-direction: column;
      gap: var(--fsds-walkthrough-design-content-spacing-gap, var(--fsds-walkthrough-description-margin-top, 8px));
    }

    .walkthrough__title {
      margin: 0;
      font-size: var(--fsds-walkthrough-design-title-typography-size, var(--fsds-walkthrough-title-font-size, 20px));
      font-weight: var(--fsds-walkthrough-design-title-typography-weight, var(--fsds-walkthrough-title-font-weight, 700));
      color: var(--fsds-walkthrough-design-title-foreground-color, var(--fsds-walkthrough-title-color, #141414));
    }

    .walkthrough__description {
      margin: 0;
      font-size: var(--fsds-walkthrough-design-description-typography-size, var(--fsds-walkthrough-description-font-size, 16px));
      color: var(--fsds-walkthrough-design-description-foreground-color, var(--fsds-walkthrough-description-color, #474647));
      line-height: var(--fsds-walkthrough-design-description-typography-line-height, 1.5);
    }

    .walkthrough__controls {
      display: flex;
      flex-direction: row;
      align-items: center;
      gap: var(--fsds-walkthrough-design-controls-spacing-gap, var(--fsds-walkthrough-controls-gap, 12px));
      margin-top: var(--fsds-walkthrough-controls-margin-top, 16px);
      border-top-color: var(--fsds-walkthrough-design-controls-border-top-color, var(--fsds-walkthrough-surface-border, #d0d0d0));
      border-top-style: var(--fsds-walkthrough-design-controls-border-top-style, solid);
      border-top-width: var(--fsds-walkthrough-design-controls-border-top-width, 1px);
      padding-top: var(--fsds-walkthrough-controls-margin-top, 16px);
      flex-wrap: wrap;
    }

    .walkthrough__skip {
      background: transparent;
      border: none;
      color: var(--fsds-walkthrough-design-skip-foreground-color, var(--fsds-walkthrough-button-secondary-color, #474647));
      cursor: pointer;
      padding: var(--fsds-walkthrough-design-skip-spacing-padding, 0);
      margin-right: auto;
    }

    .walkthrough__prev {
      background-color: var(--fsds-walkthrough-design-prev-background-fill, var(--fsds-walkthrough-button-secondary-bg, #00000000));
      border-color: var(--fsds-walkthrough-design-prev-border-color, var(--fsds-walkthrough-button-secondary-border, #d0d0d0));
      border-style: var(--fsds-walkthrough-design-prev-border-style, solid);
      border-width: var(--fsds-walkthrough-design-prev-border-width, 1px);
      border-radius: var(--fsds-walkthrough-design-prev-shape-radius, var(--fsds-walkthrough-button-primary-radius, 6px));
      color: var(--fsds-walkthrough-design-prev-foreground-color, var(--fsds-walkthrough-button-secondary-color, #474647));
      cursor: pointer;
    }

    .walkthrough__next {
      background-color: var(--fsds-walkthrough-design-next-background-fill, var(--fsds-walkthrough-button-primary-bg, #0566fe));
      border: none;
      border-radius: var(--fsds-walkthrough-design-next-shape-radius, var(--fsds-walkthrough-button-primary-radius, 6px));
      color: var(--fsds-walkthrough-design-next-foreground-color, var(--fsds-walkthrough-button-primary-color, #ffffff));
      cursor: pointer;
    }

    .walkthrough__dots {
      display: flex;
      flex-direction: row;
      align-items: center;
      justify-content: center;
      gap: var(--fsds-walkthrough-design-dots-spacing-gap, var(--fsds-walkthrough-dots-gap, 4px));
    }

    .walkthrough__dot {
      display: block;
      width: var(--fsds-walkthrough-design-dot-sizing-width, var(--fsds-walkthrough-dots-size, 8px));
      height: var(--fsds-walkthrough-design-dot-sizing-height, var(--fsds-walkthrough-dots-size, 8px));
      border-radius: var(--fsds-walkthrough-design-dot-shape-radius, 50%);
      background-color: var(--fsds-walkthrough-design-dot-background-fill, var(--fsds-walkthrough-dots-idle, #d0d0d0));
      border: none;
      padding: var(--fsds-walkthrough-design-dot-spacing-padding, 0);
      cursor: pointer;
    }

    .walkthrough__counter {
      color: var(--fsds-walkthrough-design-counter-foreground-color, var(--fsds-walkthrough-description-color, #474647));
      font-size: var(--fsds-walkthrough-design-counter-typography-size, var(--fsds-walkthrough-description-font-size, 16px));
    }
    }
  `;

  override render() {
    return html`<fsds-stack as="h3" class="walkthrough__title"><slot></slot></fsds-stack>`;
  }
}

customElements.define('fsds-walkthrough-title', WalkthroughTitleElement);

export class WalkthroughDescriptionElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .walkthrough {
      --fsds-walkthrough-surface-bg: var(--fsds-semantic-color-background-secondary, #f7f7f7);
      --fsds-walkthrough-surface-border: var(--fsds-semantic-color-border-subtle, #d0d0d0);
      --fsds-walkthrough-surface-radius: var(--fsds-semantic-shape-radius-large, 16px);
      --fsds-walkthrough-surface-shadow: var(--fsds-semantic-elevation-surface-floating, 0px 2px 4px #0000000f, 0px 4px 8px #0000001a);
      --fsds-walkthrough-surface-padding: var(--fsds-core-spacing-size-08, 32px);
      --fsds-walkthrough-title-font-size: var(--fsds-semantic-typography-heading-03, 20px);
      --fsds-walkthrough-title-font-weight: var(--fsds-semantic-typography-font-weight-bold, 700);
      --fsds-walkthrough-title-color: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-walkthrough-description-font-size: var(--fsds-semantic-typography-body-02, 16px);
      --fsds-walkthrough-description-color: var(--fsds-semantic-color-foreground-secondary, #474647);
      --fsds-walkthrough-description-margin-top: var(--fsds-core-spacing-size-04, 8px);
      --fsds-walkthrough-controls-gap: var(--fsds-core-spacing-size-05, 12px);
      --fsds-walkthrough-controls-margin-top: var(--fsds-core-spacing-size-06, 16px);
      --fsds-walkthrough-dots-size: var(--fsds-core-spacing-size-04, 8px);
      --fsds-walkthrough-dots-gap: var(--fsds-core-spacing-size-03, 4px);
      --fsds-walkthrough-dots-idle: var(--fsds-semantic-color-border-subtle, #d0d0d0);
      --fsds-walkthrough-button-primary-bg: var(--fsds-semantic-color-action-background-primary-default, #0566fe);
      --fsds-walkthrough-button-primary-color: var(--fsds-semantic-color-action-foreground-primary-default, #ffffff);
      --fsds-walkthrough-button-primary-radius: var(--fsds-semantic-shape-control-radius-default, 6px);
      --fsds-walkthrough-button-secondary-bg: var(--fsds-core-color-mode-transparent, #00000000);
      --fsds-walkthrough-button-secondary-color: var(--fsds-semantic-color-foreground-secondary, #474647);
      --fsds-walkthrough-button-secondary-border: var(--fsds-semantic-color-border-subtle, #d0d0d0);
    }

    @layer components.defaults {
    .walkthrough {
      padding-block-start: var(--fsds-box-model-padding-block-start, 0);
      padding-block-end: var(--fsds-box-model-padding-block-end, 0);
      padding-inline-start: var(--fsds-box-model-padding-inline-start, 0);
      padding-inline-end: var(--fsds-box-model-padding-inline-end, 0);
      gap: var(--fsds-walkthrough-design-root-spacing-gap, var(--fsds-walkthrough-dots-gap, 4px));
      width: var(--fsds-walkthrough-design-root-sizing-width, 360px);
      min-width: var(--fsds-box-model-min-width, 0);
      max-width: var(--fsds-walkthrough-design-root-sizing-max-width, calc(100vw - 32px));
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, 0);
      max-height: var(--fsds-walkthrough-design-root-sizing-max-height, calc(100dvh - 32px));
      position: relative;
      display: flex;
      flex-direction: column;
      background-color: var(--fsds-walkthrough-design-root-background-fill, var(--fsds-walkthrough-surface-bg, #f7f7f7));
      border-color: var(--fsds-walkthrough-design-root-border-color, var(--fsds-walkthrough-surface-border, #d0d0d0));
      border-style: var(--fsds-walkthrough-design-root-border-style, solid);
      border-width: var(--fsds-walkthrough-design-root-border-width, 1px);
      border-radius: var(--fsds-walkthrough-design-root-shape-radius, var(--fsds-walkthrough-surface-radius, 16px));
      box-shadow: var(--fsds-walkthrough-design-root-elevation-shadow, var(--fsds-walkthrough-surface-shadow, 0px 2px 4px #0000000f, 0px 4px 8px #0000001a));
      padding: var(--fsds-walkthrough-design-root-spacing-padding, var(--fsds-walkthrough-surface-padding, 32px));
      overflow-y: auto;
      box-sizing: border-box;
    }

    .walkthrough__content {
      display: flex;
      flex-direction: column;
      gap: var(--fsds-walkthrough-design-content-spacing-gap, var(--fsds-walkthrough-description-margin-top, 8px));
    }

    .walkthrough__title {
      margin: 0;
      font-size: var(--fsds-walkthrough-design-title-typography-size, var(--fsds-walkthrough-title-font-size, 20px));
      font-weight: var(--fsds-walkthrough-design-title-typography-weight, var(--fsds-walkthrough-title-font-weight, 700));
      color: var(--fsds-walkthrough-design-title-foreground-color, var(--fsds-walkthrough-title-color, #141414));
    }

    .walkthrough__description {
      margin: 0;
      font-size: var(--fsds-walkthrough-design-description-typography-size, var(--fsds-walkthrough-description-font-size, 16px));
      color: var(--fsds-walkthrough-design-description-foreground-color, var(--fsds-walkthrough-description-color, #474647));
      line-height: var(--fsds-walkthrough-design-description-typography-line-height, 1.5);
    }

    .walkthrough__controls {
      display: flex;
      flex-direction: row;
      align-items: center;
      gap: var(--fsds-walkthrough-design-controls-spacing-gap, var(--fsds-walkthrough-controls-gap, 12px));
      margin-top: var(--fsds-walkthrough-controls-margin-top, 16px);
      border-top-color: var(--fsds-walkthrough-design-controls-border-top-color, var(--fsds-walkthrough-surface-border, #d0d0d0));
      border-top-style: var(--fsds-walkthrough-design-controls-border-top-style, solid);
      border-top-width: var(--fsds-walkthrough-design-controls-border-top-width, 1px);
      padding-top: var(--fsds-walkthrough-controls-margin-top, 16px);
      flex-wrap: wrap;
    }

    .walkthrough__skip {
      background: transparent;
      border: none;
      color: var(--fsds-walkthrough-design-skip-foreground-color, var(--fsds-walkthrough-button-secondary-color, #474647));
      cursor: pointer;
      padding: var(--fsds-walkthrough-design-skip-spacing-padding, 0);
      margin-right: auto;
    }

    .walkthrough__prev {
      background-color: var(--fsds-walkthrough-design-prev-background-fill, var(--fsds-walkthrough-button-secondary-bg, #00000000));
      border-color: var(--fsds-walkthrough-design-prev-border-color, var(--fsds-walkthrough-button-secondary-border, #d0d0d0));
      border-style: var(--fsds-walkthrough-design-prev-border-style, solid);
      border-width: var(--fsds-walkthrough-design-prev-border-width, 1px);
      border-radius: var(--fsds-walkthrough-design-prev-shape-radius, var(--fsds-walkthrough-button-primary-radius, 6px));
      color: var(--fsds-walkthrough-design-prev-foreground-color, var(--fsds-walkthrough-button-secondary-color, #474647));
      cursor: pointer;
    }

    .walkthrough__next {
      background-color: var(--fsds-walkthrough-design-next-background-fill, var(--fsds-walkthrough-button-primary-bg, #0566fe));
      border: none;
      border-radius: var(--fsds-walkthrough-design-next-shape-radius, var(--fsds-walkthrough-button-primary-radius, 6px));
      color: var(--fsds-walkthrough-design-next-foreground-color, var(--fsds-walkthrough-button-primary-color, #ffffff));
      cursor: pointer;
    }

    .walkthrough__dots {
      display: flex;
      flex-direction: row;
      align-items: center;
      justify-content: center;
      gap: var(--fsds-walkthrough-design-dots-spacing-gap, var(--fsds-walkthrough-dots-gap, 4px));
    }

    .walkthrough__dot {
      display: block;
      width: var(--fsds-walkthrough-design-dot-sizing-width, var(--fsds-walkthrough-dots-size, 8px));
      height: var(--fsds-walkthrough-design-dot-sizing-height, var(--fsds-walkthrough-dots-size, 8px));
      border-radius: var(--fsds-walkthrough-design-dot-shape-radius, 50%);
      background-color: var(--fsds-walkthrough-design-dot-background-fill, var(--fsds-walkthrough-dots-idle, #d0d0d0));
      border: none;
      padding: var(--fsds-walkthrough-design-dot-spacing-padding, 0);
      cursor: pointer;
    }

    .walkthrough__counter {
      color: var(--fsds-walkthrough-design-counter-foreground-color, var(--fsds-walkthrough-description-color, #474647));
      font-size: var(--fsds-walkthrough-design-counter-typography-size, var(--fsds-walkthrough-description-font-size, 16px));
    }
    }
  `;

  override render() {
    return html`<fsds-stack as="p" class="walkthrough__description"><slot></slot></fsds-stack>`;
  }
}

customElements.define('fsds-walkthrough-description', WalkthroughDescriptionElement);
// @generated:end

// @custom:start trailing

// @custom:end