// @generated:start imports
import { LitElement, html, css, nothing } from 'lit';
import { property } from 'lit/decorators.js';
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type ProfileFlagData = { id: string; username: string; full_name: string; first_name: string | null; last_name: string | null; avatar_url: string | null; bio: string; occupation: string | null; account_status: string; created_at: string; updated_at: string | null };
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
export class ProfileFlagElement extends LitElement {
  static override styles = css`
    :host { display: contents; }
    /* @generated by ds-codegen from the box-model primitive */
    @layer components {
      @layer primitive, defaults, box, axes, sides;
      :where([data-fsds-component]), :host([data-fsds-component]) {
        --fsds-box-model-padding: initial;
        --fsds-box-model-padding-block: initial;
        --fsds-box-model-padding-block-start: initial;
        --fsds-box-model-padding-block-end: initial;
        --fsds-box-model-padding-inline: initial;
        --fsds-box-model-padding-inline-start: initial;
        --fsds-box-model-padding-inline-end: initial;
        --fsds-box-model-gap: initial;
        --fsds-box-model-width: initial;
        --fsds-box-model-min-width: initial;
        --fsds-box-model-max-width: initial;
        --fsds-box-model-height: initial;
        --fsds-box-model-min-height: initial;
        --fsds-box-model-max-height: initial;
      }
      @layer box {
        :where([data-fsds-box]) {
          padding: var(--fsds-box-model-padding, revert-layer);
          gap: var(--fsds-box-model-gap, revert-layer);
          width: var(--fsds-box-model-width, revert-layer);
          min-width: var(--fsds-box-model-min-width, revert-layer);
          max-width: var(--fsds-box-model-max-width, revert-layer);
          height: var(--fsds-box-model-height, revert-layer);
          min-height: var(--fsds-box-model-min-height, revert-layer);
          max-height: var(--fsds-box-model-max-height, revert-layer);
        }
      }
      @layer axes {
        :where([data-fsds-box]) {
          padding-block: var(--fsds-box-model-padding-block, revert-layer);
          padding-inline: var(--fsds-box-model-padding-inline, revert-layer);
        }
      }
      @layer sides {
        :where([data-fsds-box]) {
          padding-block-start: var(--fsds-box-model-padding-block-start, revert-layer);
          padding-block-end: var(--fsds-box-model-padding-block-end, revert-layer);
          padding-inline-start: var(--fsds-box-model-padding-inline-start, revert-layer);
          padding-inline-end: var(--fsds-box-model-padding-inline-end, revert-layer);
        }
      }
    }


    .profile-flag {
      --fsds-profile-flag-color-background-default: var(--fsds-semantic-color-background-primary, #ffffff);
      --fsds-profile-flag-color-border-default: var(--fsds-semantic-color-border-light, #b8b8b8);
      --fsds-profile-flag-color-foreground-primary: var(--fsds-semantic-color-foreground-primary, #141414);
      --fsds-profile-flag-size-radius-default: var(--fsds-semantic-shape-control-radius-default, 6px);
      --fsds-profile-flag-spacing-gap-default: var(--fsds-core-spacing-size-03, 4px);
      --fsds-profile-flag-spacing-padding-right: var(--fsds-core-spacing-size-06, 16px);
      --fsds-profile-flag-color-border-hover: var(--fsds-semantic-color-border-bold, #888889);
    }

    @layer components.defaults {
    .profile-flag {
      display: inline-flex;
      flex-direction: row;
      align-items: center;
      box-sizing: border-box;
      padding-block-start: var(--fsds-box-model-padding-block-start, 2px);
      padding-block-end: var(--fsds-box-model-padding-block-end, 2px);
      padding-inline-start: var(--fsds-box-model-padding-inline-start, 4px);
      padding-inline-end: var(--fsds-box-model-padding-inline-end, 4px);
      gap: var(--fsds-profile-flag-design-root-spacing-gap, var(--fsds-profile-flag-spacing-gap-default, 4px));
      width: var(--fsds-box-model-width, auto);
      min-width: var(--fsds-box-model-min-width, 0);
      max-width: var(--fsds-box-model-max-width, none);
      height: var(--fsds-box-model-height, auto);
      min-height: var(--fsds-box-model-min-height, var(--fsds-semantic-glyph-size-medium-extent, 16px));
      max-height: var(--fsds-box-model-max-height, none);
      background-color: var(--fsds-profile-flag-design-root-background-fill, var(--fsds-profile-flag-color-background-default, #ffffff));
      border-color: var(--fsds-profile-flag-design-root-border-color, var(--fsds-profile-flag-color-border-default, #b8b8b8));
      color: var(--fsds-profile-flag-design-root-foreground-color, var(--fsds-profile-flag-color-foreground-primary, #141414));
      border-radius: var(--fsds-profile-flag-design-root-shape-radius, var(--fsds-profile-flag-size-radius-default, 6px));
      padding: var(--fsds-profile-flag-design-root-spacing-padding, var(--fsds-profile-flag-spacing-padding-right, 16px));

      &:hover {
        border-color: var(--fsds-profile-flag-design-hover-border-color, var(--fsds-profile-flag-color-border-hover, #888889));
      }
    }
    }
  `;

  @property({ attribute: false }) profile?: ProfileFlagData;

  override connectedCallback(): void {
    super.connectedCallback();
    this.setAttribute("data-fsds-component", "profile-flag");
  }

  private computeClasses(): string {
    return [
      "profile-flag",
    ].filter(Boolean).join(" ");
  }

  override render() {
    return html`<div class="${this.computeClasses()}" data-fsds-box="">
  <slot></slot>
</div>`;
  }
}

customElements.define('fsds-profile-flag', ProfileFlagElement);

// @generated:end

// @custom:start trailing

// @custom:end